Certificate tutorials
eclipse-arrowhead/core-java-spring pull request #114
Opened 2019-10-17 15:45 UTC by borditamas

2019-10-18 06:40 UTC, MaGaMeGa approved these changes
create cloud cert - typo - in 9th Step selest - select

2019-10-18 09:24 UTC, rbocsi approved these changes

2019-10-23 18:49 UTC, tsvetlin requested changes
Fix the typo, and it can be merged.

2019-10-23 18:49 UTC, tsvetlin commented on README.md
> +Currently Arrowhead communitiy have the possibility to create only "self signed" certifications. See the tutorials:
Typo: Community

2019-10-23 18:49 UTC, tsvetlin commented on README.md
> -            Same as the new version
Why is this change needed?

2019-10-24 07:59 UTC, borditamas commented on README.md
> -            Same as the new version
Have no idea..., but will discard this change

2019-10-24 08:04 UTC, borditamas commented on README.md
> -            Same as the new version
Actually, there is no change at all... don't know why Github highlight it....

2019-10-24 08:15 UTC, merged