Service Registry ping and ttl
eclipse-arrowhead/core-java-spring pull request #12
Opened 2019-05-31 11:54 UTC by borditamas

2019-05-31 12:07 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ProvidersReachabilityTask.java
> +		logger.info("STARTED: Providers reachability task");
use debug

2019-05-31 12:08 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ProvidersReachabilityTask.java
> +		logger.info("FINISHED: Providers reachability task. Number of removed service registry entry: " + removedServiceRegistryIDs.size());
and here too

2019-05-31 12:10 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ProvidersReachabilityTask.java
> +		} catch (IllegalArgumentException exception) {
final

2019-05-31 12:15 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ProvidersReachabilityTask.java
> +				serviceRegistryDBService.removeServiceRegistryEntryById(serviceRegistryEntry.getId());
consider deleting multiple entries at once

2019-05-31 12:27 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ProvidersReachabilityTaskConfig.java
> +        trigger.setRepeatInterval(pingInterval * 60000);
constant maybe

2019-05-31 12:28 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/AutoWiringSpringBeanQuartzTaskFactory.java
> +public final class AutoWiringSpringBeanQuartzTaskFactory extends SpringBeanJobFactory implements ApplicationContextAware {
no need for the interface

2019-05-31 12:30 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ProvidersReachabilityTaskConfig.java
> +	private final String nameOfTrigger = "Providers_Reachability_Task_Trigger";
static

2019-05-31 12:30 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ProvidersReachabilityTaskConfig.java
> +	private final String nameOfTask = "Providers_Reachability_Task_Detail";
static

2019-05-31 12:31 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ServiceEndOfValidityCheckTask.java
> +		logger.info("STARTED: Services end of validity check task");
debug

2019-05-31 12:31 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ServiceEndOfValidityCheckTask.java
> +		logger.info("FINISHED: Services end of validity check task. Number of removed service registry entry: " + removedServiceRegistryIDs.size());
debug

2019-05-31 12:31 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ServiceEndOfValidityCheckTask.java
> +				serviceRegistryDBService.removeServiceRegistryEntryById(serviceRegistryEntry.getId());
consider using bulk delete solution

2019-05-31 12:32 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ServiceEndOfValidityCheckTaskConfig.java
> +	private final String nameOfTrigger = "Services_End_OF_Validity_Check_Task_Trigger";
static

2019-05-31 12:32 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ServiceEndOfValidityCheckTaskConfig.java
> +	private final String nameOfTask = "Services_End_OF_Validity_Check_Task_Detail";
static

2019-05-31 12:32 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/quartz/task/ServiceEndOfValidityCheckTaskConfig.java
> +        trigger.setRepeatInterval(ttlInterval * 60000);
maybe constant

2019-05-31 12:34 UTC, rbocsi commented on serviceregistry/src/main/resources/application.properties
> +ping_interval=2
try not to push testing settings to the repository

2019-05-31 12:35 UTC, rbocsi requested changes
see comments

2019-05-31 13:58 UTC, borditamas commented
Changed as requested, please check again

2019-06-03 10:40 UTC, rbocsi approved these changes
seems ok

2019-06-03 10:52 UTC, merged