System endpoints implementations
eclipse-arrowhead/core-java-spring pull request #16
Opened 2019-06-05 12:24 UTC by MaGaMeGa

2019-06-05 12:26 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/CommonConstants.java
> +	public static final String REQUEST_PARAM_DIRECTION_DEFAULT_VALUE = "ASC";
move to Defaults

2019-06-05 12:29 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SystemRepository.java
> +	System findBySystemNameAndAddressAndPort(String systemName, String address, int port);
return with Optional<System>

2019-06-05 12:30 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/ServiceDefinitionRepository.java
> +	Optional<ServiceDefinition> findByServiceDefinition(String serviceDefinition);
final

2019-06-05 12:36 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
>  		if (!systemOption.isPresent()){
throw DataNotFoundException instead

2019-06-05 12:37 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		if (page < 0) {
change this to trenary operator

2019-06-05 12:38 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +	public Page<System> getSystemEntries(final int page, final int size, final String direction, final String sortField) {
direction's type is Direction not String

2019-06-05 12:39 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		if(sortField==null || "".equalsIgnoreCase(sortField)) {
Utilities.isEmpty()

2019-06-05 12:42 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +			if (! System.SORTABLE_FIELDS_BY.contains(sortField)) {
no space between ! and logical expression

2019-06-05 12:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +
systemName and address toLowerCase()
check UniqueConstraint in a private method that throws InvalidParameterException (new class, need to implement)

2019-06-05 12:58 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		  throw new BadPayloadException(COULD_NOT_CREATE_SYSTEM_ERROR_MESSAGE, e);
throw ArrowheadException instead.

2019-06-05 13:00 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +	public Page<ServiceDefinition> getAllServiceDefinitionEntries(final int page, final int size, final Direction direction, final String sortField) {
rename getServiceDefinitionEntries

2019-06-05 13:01 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		final int page_ = page < 0 ? 0 : page;
rename validated*

2019-06-05 13:02 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +	public ServiceDefinitionsListResponseDTO getAllServiceDefinitionEntriesResponse(final int page, final int size, final Direction direction, final String sortField) {
rename

2019-06-05 13:03 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		final List<ServiceDefinition> serviceDefinitionEntries = getAllServiceDefinitionEntries(page, size, direction, sortField).getContent();
need page to obtain totalCount value

2019-06-05 13:06 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		ServiceDefinition serviceDefinitionEntry;
move inside if

2019-06-05 13:08 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> -			throw new IllegalArgumentException("Sortable field with reference '" + sortField_ + "' is not available");
InvalidParameterException instead

2019-06-05 13:08 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
>  		final int page_ = page < 0 ? 0 : page;
validated*

2019-06-05 13:09 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		checkConstraintsOfServiceDefinitionTable(serviceDefinition);
lowercase

2019-06-05 13:09 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +			serviceDefinitionEntry.setServiceDefinition(serviceDefinition);
lowercase

2019-06-05 13:11 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +
logger debug message

2019-06-05 13:12 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		  throw new BadPayloadException(COULD_NOT_UPDATE_SYSTEM_ERROR_MESSAGE, e);
remove try/catch

2019-06-05 13:13 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		if (checkIfUniqValidationNeeded(system, validatedSystemName, validatedAddress, validatedPort)) {
typo UniquE

2019-06-05 13:13 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		return systemRepository.saveAndFlush(system);
try/catch here

2019-06-05 13:14 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +
lowercase and trim

2019-06-05 13:16 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		try {
remove try/catch

2019-06-05 13:17 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +
lowercase & trim

2019-06-05 13:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		return systemRepository.saveAndFlush(system);
try/catch here

2019-06-05 13:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +	private boolean checkIfUniqValidationNeeded(final System system, final String validatedSystemName, final String validatedAddress,
add System into the name

2019-06-05 13:26 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		if ( actualSystemName != null && validatedSystemName != null && !actualSystemName.equalsIgnoreCase(validatedSystemName)) {
actual values are not null and not empty (comes from the DB)

2019-06-05 13:27 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +				isUniqnessCheckNeeded = true;
you can return immediately

2019-06-05 13:28 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +			throw new BadPayloadException(serviceDefinition + "definition already exists");
illegalParameterException

2019-06-05 13:29 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		final System find = systemRepository.findBySystemNameAndAddressAndPort(validatedSystemName, validatedAddress, validatedPort);
use optional

2019-06-05 13:30 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +			throw new BadPayloadException("Service by name:"+validatedSystemName+
illegalParameterException

2019-06-05 13:33 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		if ( validatedAuthenticationInfo != null && !"".equalsIgnoreCase(validatedAuthenticationInfo)) {
no need for if

2019-06-05 13:33 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		Assert.notNull(serviceDefinition.getServiceDefinition(), "ServiceDefinition is null");
unneccessary

2019-06-05 13:38 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/ServiceDefinitionResponseDTO.java
> +	private Long id;
primitive long

2019-06-05 13:39 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/ServiceDefinitionsListResponseDTO.java
> +	private int count;
long

2019-06-05 13:40 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/SystemResponseDTO.java
> +	private long sytemId;
typo syStemId

2019-06-05 13:45 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +			throw new BadPayloadException(ID_MUST_BE_GREATER_THEN_ZERO_ERROR_MESSAGE, HttpStatus.SC_EXPECTATION_FAILED, CommonConstants.SERVICEREGISTRY_URI + SYSTEM_BY_ID_URI);
statuscode 400

2019-06-05 13:53 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +			return DTOConverter.convertSystemEntryListToSystemListResponseDTO(serviceRegistryDBService.getSystemEntries(validatedPage, validatedSize, direction, sortField));
move dto conversion to SRDBService

2019-06-05 13:53 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		} catch ( final IllegalArgumentException e) {
remove try/catch

2019-06-05 13:55 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@PostMapping(path = SYSTEMS_URI, consumes = "application/json", produces = "application/json")
MediaType.APPLICATION_JSON_VALUE

2019-06-05 13:56 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		} catch (final Exception e) {
remove try/catch

2019-06-05 13:59 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		final String validatedSortField = sortField.trim();
remove

2019-06-05 14:01 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		if (! ServiceDefinition.SORTABLE_FIELDS_BY.contains(validatedSortField)) {
remove this block

2019-06-05 14:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseBody public ServiceDefinitionResponseDTO  getServiceDefinition(@PathVariable(value = CommonConstants.COMMON_FIELD_NAME_ID) final long id) {
ById

2019-06-05 14:03 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseBody public ServiceDefinitionsListResponseDTO getBunchOfServiceDefinitions(
rename getServiceDefinitions

2019-06-05 14:04 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseBody public ServiceDefinitionResponseDTO registerServiceDefinition(@RequestBody final ServiceDefinitionRequestDTO serviceDefinitionRequestDTO) {
addSD

2019-06-05 14:05 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		serviceDefinition = serviceDefinition.trim().toLowerCase();
move to db method

2019-06-05 14:06 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		serviceDefinition = serviceDefinition.trim().toLowerCase();
move to db method

2019-06-05 14:06 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		//Currently ServiceDefinition has only one updatable field, therefore PUT and PATH do the same
typo PATcH

2019-06-05 14:07 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		final String validatedSystemName = request.getSystemName().toLowerCase();
move to db method

2019-06-05 14:08 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		final String validatedAuthenticationInfo = request.getAuthenticationInfo()!=null?request.getAuthenticationInfo():"";
no need for this

2019-06-05 14:10 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		if ( request.getAddress() == null || "".equalsIgnoreCase(request.getAddress().trim()) ) {
Utilities.isEmpty()

2019-06-05 14:11 UTC, rbocsi requested changes
see inline comments

2019-06-05 14:31 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/repository/ServiceDefinitionRepository.java
> +	Optional<ServiceDefinition> findByServiceDefinition(String serviceDefinition);
done

2019-06-05 14:35 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +	public Page<ServiceDefinition> getAllServiceDefinitionEntries(final int page, final int size, final Direction direction, final String sortField) {
done

2019-06-05 14:37 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		final int page_ = page < 0 ? 0 : page;
done

2019-06-05 14:40 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +	public ServiceDefinitionsListResponseDTO getAllServiceDefinitionEntriesResponse(final int page, final int size, final Direction direction, final String sortField) {
done

2019-06-05 14:42 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
>  		final int page_ = page < 0 ? 0 : page;
done

2019-06-05 14:43 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		Assert.notNull(serviceDefinition.getServiceDefinition(), "ServiceDefinition is null");
done

2019-06-05 14:46 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/ServiceDefinitionResponseDTO.java
> +	private Long id;
done

2019-06-05 14:47 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/ServiceDefinitionsListResponseDTO.java
> +	private int count;
done

2019-06-05 14:48 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseBody public ServiceDefinitionsListResponseDTO getBunchOfServiceDefinitions(
done

2019-06-05 14:49 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseBody public ServiceDefinitionResponseDTO  getServiceDefinition(@PathVariable(value = CommonConstants.COMMON_FIELD_NAME_ID) final long id) {
done

2019-06-05 14:50 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseBody public ServiceDefinitionResponseDTO registerServiceDefinition(@RequestBody final ServiceDefinitionRequestDTO serviceDefinitionRequestDTO) {
done

2019-06-05 14:50 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		//Currently ServiceDefinition has only one updatable field, therefore PUT and PATH do the same
done

2019-06-06 07:02 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/CommonConstants.java
> +	public static final String REQUEST_PARAM_DIRECTION_DEFAULT_VALUE = "ASC";
done

2019-06-06 07:08 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SystemRepository.java
> +	System findBySystemNameAndAddressAndPort(String systemName, String address, int port);
done

2019-06-06 07:11 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		final String validatedSortField = sortField.trim();
done

2019-06-06 07:12 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		if (! ServiceDefinition.SORTABLE_FIELDS_BY.contains(validatedSortField)) {
done

2019-06-06 07:12 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		if ( validatedAuthenticationInfo != null && !"".equalsIgnoreCase(validatedAuthenticationInfo)) {
done

2019-06-06 07:19 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/SystemResponseDTO.java
> +	private long sytemId;
done

2019-06-06 07:44 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +			throw new BadPayloadException(ID_MUST_BE_GREATER_THEN_ZERO_ERROR_MESSAGE, HttpStatus.SC_EXPECTATION_FAILED, CommonConstants.SERVICEREGISTRY_URI + SYSTEM_BY_ID_URI);
done

2019-06-06 07:45 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +			return DTOConverter.convertSystemEntryListToSystemListResponseDTO(serviceRegistryDBService.getSystemEntries(validatedPage, validatedSize, direction, sortField));
done

2019-06-06 07:45 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		} catch ( final IllegalArgumentException e) {
done

2019-06-06 07:53 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@PostMapping(path = SYSTEMS_URI, consumes = "application/json", produces = "application/json")
done

2019-06-06 07:53 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		} catch (final Exception e) {
done

2019-06-06 08:59 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		final List<ServiceDefinition> serviceDefinitionEntries = getAllServiceDefinitionEntries(page, size, direction, sortField).getContent();
done

2019-06-06 09:05 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		checkConstraintsOfServiceDefinitionTable(serviceDefinition);
done

2019-06-06 09:36 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +		ServiceDefinition serviceDefinitionEntry;
done

2019-06-06 09:36 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +			serviceDefinitionEntry.setServiceDefinition(serviceDefinition);
done

2019-06-06 09:37 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> -			throw new IllegalArgumentException("Sortable field with reference '" + sortField_ + "' is not available");
done

2019-06-06 09:37 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/service/ServiceRegistryDBService.java
> +			throw new BadPayloadException(serviceDefinition + "definition already exists");
done

2019-06-06 09:39 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		serviceDefinition = serviceDefinition.trim().toLowerCase();
done

2019-06-06 09:39 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		serviceDefinition = serviceDefinition.trim().toLowerCase();
done

2019-06-06 12:55 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		final String validatedSystemName = request.getSystemName().toLowerCase();
done

2019-06-06 12:56 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		final String validatedAuthenticationInfo = request.getAuthenticationInfo()!=null?request.getAuthenticationInfo():"";
done

2019-06-06 12:56 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		if ( request.getAddress() == null || "".equalsIgnoreCase(request.getAddress().trim()) ) {
done

2019-06-06 14:03 UTC, MaGaMeGa reviewed
please review changes

2019-06-06 14:08 UTC, rbocsi approved these changes
e

2019-06-06 14:08 UTC, merged