Eventhandler startup enhancement
eclipse-arrowhead/core-java-spring pull request #167
Opened 2020-01-15 12:52 UTC by MaGaMeGa

2020-01-15 13:50 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerApplicationInitListener.java
> +
missing logging

2020-01-15 13:51 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerApplicationInitListener.java
> +				} catch (ArrowheadException ex) {
missing final

2020-01-15 13:54 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerApplicationInitListener.java
> +		findCoreSystemServiceUri(CoreSystemService.AUTH_CONTROL_SUBSCRIPTION_SERVICE, queryUri);
try at least 3 (use a constant) times

2020-01-15 13:55 UTC, rbocsi requested changes
see inline comments

2020-01-23 11:12 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerApplicationInitListener.java
> +			} catch (Exception ex) {
missing final

2020-01-23 11:13 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerApplicationInitListener.java
> +				logger.info("Unsuccessful update SubscriberAuthorizations. Trys left: " + (max_retry - retry) );
typo : trys => tries

2020-01-23 11:13 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerApplicationInitListener.java
> +					logger.info("EventHandler could not start becouse of unsuccessful Subscribers Authorization: " + ex);
typo: becouse => because

2020-01-23 11:14 UTC, rbocsi requested changes
minor changes needed: typos and missing final

2020-02-12 13:51 UTC, MaGaMeGa commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerApplicationInitListener.java
> +					logger.info("EventHandler could not start becouse of unsuccessful Subscribers Authorization: " + ex);
fixed

2020-02-12 13:51 UTC, MaGaMeGa commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerApplicationInitListener.java
> +				logger.info("Unsuccessful update SubscriberAuthorizations. Trys left: " + (max_retry - retry) );
fixed

2020-02-12 13:51 UTC, MaGaMeGa commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerApplicationInitListener.java
> +			} catch (Exception ex) {
fixed

2020-04-15 12:15 UTC, merged