DeviceRegistry and SystemRegistry update
eclipse-arrowhead/core-java-spring pull request #171
Opened 2020-01-24 21:24 UTC by mzsilak

2020-01-24 22:26 UTC, tsvetlin commented
Dear Mario!

Thank you for opening the pull request, we will review your code as soon as possible. In the meantime, could you please add the documentation to the documentation folder and extend the README in a similar format as the other core systems?

Thank you!

2020-01-27 10:49 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/CoreUtilities.java
> +		private static final int MAX_BATCH_SIZE = 200;
This is a utility class used by a lot of web-services. Fixing the typo here is OK. But modifying the logic is not OK for us. The original logic was that if the page and the size parameters are not specified then we want all the records. With your modifications it is returned with the first 200 records.
If you want this logic, please implement it independently.

2020-01-27 10:51 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/Utilities.java
> +import java.util.*;
Please never use in the code base wildcard import.

2020-01-27 10:55 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/Utilities.java
> +	//-------------------------------------------------------------------------------------------------
Please follow out code convention (i.e opening brackets are end of the previous line and there is space after if, for, while, etc.).

2020-01-27 10:59 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/CoreUtilities.java
> +		private static final int MAX_BATCH_SIZE = 200;
Yes, that is true. I'll revert that change.

2020-01-27 10:59 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/Utilities.java
> +	public static  String firstNotNull(final String first, final String second)
It is not an error, just an observation. If both first and second are null this method returns with null, so not with the first not null element. Is this intentional?

2020-01-27 11:00 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/core/CoreSystem.java
> +import static eu.arrowhead.common.core.CoreSystemService.*;
no wildcard inputs

2020-01-27 11:00 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/Utilities.java
> +import java.util.*;
I'll adopt my IDE settings.

2020-01-27 11:03 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/core/CoreSystem.java
> +    //-------------------------------------------------------------------------------------------------
move this to assistant method section

2020-01-27 11:04 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/core/CoreSystem.java
> +    public List<CoreSystemService> getServices() { return services; }
move this to methods section

2020-01-27 11:04 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/core/CoreSystemService.java
> +import static eu.arrowhead.common.CommonConstants.*;
wildcard imports

2020-01-27 11:05 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/Utilities.java
> +	public static  String firstNotNull(final String first, final String second)
Yes it is intentional, but I agree that a different method name might be clearer.

2020-01-27 11:06 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Device.java
> +import javax.persistence.*;
wildcard import

2020-01-27 11:08 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/DeviceRegistry.java
> +import javax.persistence.*;
wildcard import

2020-01-27 11:13 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/core/CoreSystem.java
> +    //-------------------------------------------------------------------------------------------------
I would rather write a section "constructors" to avoid confusion. Its atypical to have a constructor after the methods.

2020-01-27 11:14 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/System.java
> +@Table(name = "system", uniqueConstraints = @UniqueConstraint(columnNames = { "systemName", "address", "port" }))
Please don't remove the _ from the table name. "SYSTEM" is a reserved word in mysql. Still, you can use as a table name if always use quotes. But to avoid confusion we decided to add an _ to the name. Some people are already use the Arrowhead and we don't want to force them to change the existing DB (except adding new tables).

2020-01-27 11:25 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/database/entity/System.java
> +@Table(name = "system", uniqueConstraints = @UniqueConstraint(columnNames = { "systemName", "address", "port" }))
ok

2020-01-27 11:29 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/core/CoreSystem.java
> +import static eu.arrowhead.common.core.CoreSystemService.*;
Just to clarify: static imports are still fine, right?

2020-01-27 11:30 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/core/CoreSystem.java
> +import static eu.arrowhead.common.core.CoreSystemService.*;
Yeah, static imports are fine.

2020-01-27 11:34 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/core/CoreSystem.java
> +    //-------------------------------------------------------------------------------------------------
The constructor is in the assistant methods section beacuse it is private. We'd like to put the public API of a class as top as possible. But you are right it is a little confusing, so I'm ok with the constructors section as long as it is AFTER the public API.

2020-01-27 11:48 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/DeviceRegistryRepository.java
> +    Page<DeviceRegistry> findAllByDevice(final List<Device> devices, final PageRequest pageRequest);
I think this one and the last one does not work, beacuse it expects exactly one Device as a parameter. Maybe you should try the name findAllByDeviceIsIn.

2020-01-27 11:56 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/database/repository/DeviceRegistryRepository.java
> +    Page<DeviceRegistry> findAllByDevice(final List<Device> devices, final PageRequest pageRequest);
yes, at least the intend will be clearer.

2020-01-27 11:58 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/database/repository/DeviceRegistryRepository.java
> +    Page<DeviceRegistry> findAllByDevice(final List<Device> devices, final PageRequest pageRequest);
The code was inspired by CrudRepository:     
`Iterable<T> findAllById(Iterable<ID> var1);`

2020-01-27 12:12 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/DeviceRegistryRepository.java
> +    Page<DeviceRegistry> findAllByDevice(final List<Device> devices, final PageRequest pageRequest);
It not just the intent. The findAllByDevice throws an exception, the findAllByDeviceIsIn probably will works. The findAllById works because somebody writes the correct implementation. But in your case, the implementation is generated using the NAME and the parameters as a specification. And the IN keyword will tell the generator to create a SELECT * FROM device_registry dr WHERE dr.device_id IN (...) query.

2020-01-27 13:02 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SystemRegistryRepository.java
> +    Optional<SystemRegistry> findBySystem(final System system);
return type should be List<SystemRegistry>

2020-01-27 13:02 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SystemRegistryRepository.java
> +	List<SystemRegistry> findAllBySystem(final List<System> systems);
rename the last two to findAllBySystemIsIn

2020-01-27 13:03 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/DTOConverter.java
> +import eu.arrowhead.common.database.entity.*;
wildcard imports

2020-01-27 13:16 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/OnboardingWithNameResponseDTO.java
> +public class OnboardingWithNameResponseDTO
should be Serializable

2020-01-27 13:16 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/ServiceEndpoint.java
> +public class ServiceEndpoint
should be Serializable

2020-01-27 13:23 UTC, rbocsi commented on deviceregistry/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_sr || true
you should use own db password field here, for example mysql_password_dr. Please note you have to modify the templates file in the core-common project to achieve that.

2020-01-27 13:26 UTC, rbocsi commented on deviceregistry/src/deb/control/postinst
> +		db_get arrowhead-core-common/mysql_password_sr; system_passwd=$RET || true
use your own password here

2020-01-27 13:26 UTC, rbocsi commented on deviceregistry/src/deb/control/postinst
> +		db_unregister arrowhead-core-common/mysql_password_sr
use your own password here

2020-01-27 13:28 UTC, rbocsi commented on deviceregistry/src/deb/control/postinst
> +		ah_cert_signed_system sysop
no need for creating sysop certificate again (SR already done that)

2020-01-27 13:29 UTC, rbocsi commented on deviceregistry/src/deb/control/postrm
> +            ${SYSTEM_DIR}/${SYSTEM_NAME}.p12 \
don't delete sysop cert here

2020-01-27 14:13 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/DeviceRegistryController.java
> +    public DeviceListResponseDTO getDeviceListByRequestParameters(
this method is mapped to the same URI than getDevices() before.  And it's like they are doing the same thing.

2020-01-27 14:18 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/DeviceRegistryController.java
> +        if (matcher.matches())
I think a negation (!) is missing here

2020-01-27 14:19 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/DeviceRegistryController.java
> +    private void checkUnregisterDeviceParameters(final String systemName, final String macAddress)
maybe you should rename systemName to deviceName (or simply name)

2020-01-27 14:22 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/DeviceRegistryController.java
> +        if (request.getVersion() <= 0) {
request.getVersion() != null check is necessary and > instead of <= I believe

2020-01-27 14:23 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +import eu.arrowhead.common.*;
wildcard imports

2020-01-27 14:37 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +                    devices = new ArrayList<>();
maybe you can use List.of(optionalDevice.get()) here

2020-01-27 14:37 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +                    return DTOConverter.convertDeviceRegistryListToDeviceQueryResultDTO(Collections.emptyList());
List.of() here

2020-01-27 14:38 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +                    return DTOConverter.convertDeviceRegistryListToDeviceQueryResultDTO(Collections.emptyList());
List.of() here

2020-01-27 14:38 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +                final String address = Utilities.lowerCaseTrim(form.getMacAddressRequirement());
I think you don't want to use macAddressRequirement here but addressRequirement

2020-01-27 14:44 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +
maybe you should check MAC address format here as well

2020-01-27 14:45 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +        final String validatedMacAddress = Utilities.lowerCaseTrim(macAddress);
check MAC address format before inserting into db

2020-01-27 14:47 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +        final String validatedAuthenticationInfo = Utilities.lowerCaseTrim(authenticationInfo);
the authenticationInfo is a public key in Base64 encoded format. Case sensitivity matters! So don't transform to lowercase here (or anywhere else).

2020-01-27 14:48 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +        return deviceRepository.save(device);
use saveAndFlush() instead

2020-01-27 14:51 UTC, rbocsi commented on deviceregistry/src/main/resources/application.properties
> +server.port=8443
server.port and domain.port should be the same (if you don't use any port forwarding)

2020-01-27 14:52 UTC, rbocsi commented on deviceregistry/src/main/resources/application.properties
> +# Service Registry has an optional feature to ping service providers in a fixed time interval,
comments are still mentions service registry

2020-01-27 14:52 UTC, rbocsi commented on deviceregistry/src/main/resources/application.properties
> +use_strict_service_intf_name_verifier=false
i think you don't need this parameter

2020-01-27 14:53 UTC, rbocsi commented on deviceregistry/src/main/resources/certificates/sysop.crt
> +-----BEGIN CERTIFICATE-----
you can delete this from here

2020-01-27 14:54 UTC, rbocsi commented on deviceregistry/src/main/resources/swagger/swagger-ui.html
> +  <title>Service Registry</title>
change the title here

2020-01-27 14:57 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
> -package eu.arrowhead.core.eventhandler;
github can't show what is changed here. I think it's just indentation, so i would be the safest just to revert it.

2020-01-27 15:26 UTC, rbocsi commented on onboarding/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_sr || true
use different password than SR

2020-01-27 15:27 UTC, rbocsi commented on onboarding/src/deb/control/postinst
> +		db_unregister arrowhead-core-common/mysql_password_sr
use different password here

2020-01-27 15:29 UTC, rbocsi commented on onboarding/src/deb/control/postinst
> +		ah_cert_signed_system sysop
don't create sysop cert here again

2020-01-27 15:30 UTC, rbocsi commented on onboarding/src/deb/control/postrm
> +			${AH_SYSTEMS_DIR}/sysop/sysop.p12
don't delete sysop here

2020-01-27 15:55 UTC, rbocsi commented on onboarding/src/main/resources/application.properties
> +server.port=8443
server.port and domain.port should be the same

2020-01-27 15:56 UTC, rbocsi commented on onboarding/src/main/resources/application.properties
> +
comments still mentioning SR
and I think there a lot of custom parameters here the this system does not (and will not) use, i.e ping, ttl, etc

2020-01-27 15:57 UTC, rbocsi commented on onboarding/src/main/resources/certificates/sysop.crt
> +-----BEGIN CERTIFICATE-----
remove sysop.crt and sysop.p12

2020-01-27 15:57 UTC, rbocsi commented on onboarding/src/main/resources/swagger/swagger-ui.html
> +  <title>Service Registry</title>
change title here

2020-01-27 16:00 UTC, rbocsi commented on scripts/create_empty_arrowhead_db.sql
> +
onboard user missing

2020-01-27 16:01 UTC, rbocsi commented on scripts/onboarding_controller_privileges.sql
> +## intentionally empty
at least give privileges to log table otherwise the console log will be flooded with warnings

2020-01-27 22:40 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SystemRegistryRepository.java
> +    Optional<SystemRegistry> findBySystem(final System system);
I'll double check this

2020-01-27 23:29 UTC, mzsilak commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +                    devices = new ArrayList<>();
its not possible to use here, because it returns an immutable list and we might modify (filter) the list later down the method

2020-01-27 23:55 UTC, mzsilak commented on onboarding/src/main/resources/application.properties
> +
Right. That was a missunderstanding on my part (in all files). I thought its literally the address/port of service registry.

2020-01-27 23:55 UTC, mzsilak commented on scripts/create_empty_arrowhead_db.sql
> +
Right now, onboarding does not need database access. I hope I modified the scripts correctly.

2020-01-28 00:30 UTC, mzsilak commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
> -package eu.arrowhead.core.eventhandler;
It was a typo in ValidatedPageParams.getValidatedDirection() which is on the far right side.

2020-01-28 08:16 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +                    devices = new ArrayList<>();
yes, you are right.

2020-01-28 08:16 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
> -package eu.arrowhead.core.eventhandler;
ok

2020-01-28 08:19 UTC, rbocsi commented on scripts/create_empty_arrowhead_db.sql
> +
actually, onboard is using the db, unless you change the log4j file accordingly. The current log settings of all core service contains db logging, and log4j uses the database settings of the application.properties file. So you can either disable the db logging in the log4j2.xml file, or create user for onboarding and add at least privileges to use the logs table.

2020-01-28 08:20 UTC, rbocsi commented on scripts/onboarding_controller_privileges.sql
> +## intentionally empty
actually, onboard is using the db, unless you change the log4j file accordingly. The current log settings of all core service contains db logging, and log4j uses the database settings of the application.properties file. So you can either disable the db logging in the log4j2.xml file, or create user for onboarding and add at least privileges to use the logs table.

2020-01-28 08:45 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +				throw new InvalidParameterException("Service Registry entry with id '" + id + "' does not exists");
You fix the missing does. Please remove the s from the end of exists as well.

2020-01-28 08:48 UTC, rbocsi commented on systemregistry/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_sr || true
use different db password than Service Registry, maybe arrowhead-core-common/mysql_password_sysr (you have to modify the templates file in the core common project to do that)

2020-01-28 08:49 UTC, rbocsi commented on systemregistry/src/deb/control/postinst
> +		db_unregister arrowhead-core-common/mysql_password_sr
use different password than Service Registry

2020-01-28 08:49 UTC, rbocsi commented on systemregistry/src/deb/control/postinst
> +		ah_cert_signed_system sysop
delete this part

2020-01-28 08:51 UTC, rbocsi commented on systemregistry/src/deb/control/postrm
> +			${AH_SYSTEMS_DIR}/sysop/sysop.p12
delete this line (and \ from the previous line)

2020-01-28 08:53 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/SystemRegistryController.java
> +    private static final String PATH_VARIABLE_SYSTEM_NAME = "systenName";
typo here "systemName"

2020-01-28 09:25 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/SystemRegistryController.java
> +        if (request.getVersion() <= 0) {
something is not right here. I believe you have to complete the merge if the version is a valid number, so greater than 0).

2020-01-28 09:26 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/database/service/SystemRegistryDBService.java
> +import eu.arrowhead.common.*;
wildcard imports

2020-01-28 09:31 UTC, mzsilak commented on scripts/create_empty_arrowhead_db.sql
> +
yes, I realized that. and changed the scripts accordingly.

2020-01-28 09:33 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/database/service/SystemRegistryDBService.java
> +                    // no service definition found
comment still mentions service definition

2020-01-28 09:34 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/database/service/SystemRegistryDBService.java
> +                    // no service definition found
also here

2020-01-28 09:37 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/database/service/SystemRegistryDBService.java
> +        final String validatedAuthenticationInfo = Utilities.lowerCaseTrim(authenticationInfo);
authentication info is case sensitive

2020-01-28 09:37 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/database/service/SystemRegistryDBService.java
> +        final String validatedAuthenticationInfo = Utilities.lowerCaseTrim(authenticationInfo);
authentication info is case sensitive

2020-01-28 09:38 UTC, mzsilak commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +				throw new InvalidParameterException("Service Registry entry with id '" + id + "' does not exists");
you are right :D

2020-01-28 09:40 UTC, rbocsi commented on systemregistry/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +{"properties": [
remove unused entries: use_strict_service_intf_name_verifier for sure (and ttl-s maybe)

2020-01-28 09:40 UTC, rbocsi commented on systemregistry/src/main/resources/application.properties
> +server.port=8443
sever.port and domain.port have the same value in default case

2020-01-28 09:41 UTC, rbocsi commented on systemregistry/src/main/resources/application.properties
> +# Service Registry has an optional feature to ping service providers in a fixed time interval,
modify comments accordingly

2020-01-28 09:43 UTC, rbocsi commented on systemregistry/src/main/resources/certificates/sysop.crt
> +-----BEGIN CERTIFICATE-----
remove this file (and the .p12 file too)

2020-01-28 09:49 UTC, rbocsi commented on systemregistry/src/main/resources/swagger/swagger-ui.html
> +  <title>Service Registry</title>
modify title here

2020-01-28 10:17 UTC, rbocsi requested changes
I just finished my first review (see inline comments for details). However, there are some issues I want to mention here:
* The Swagger needs a config class for each core system to work, and I don't find these in this pull request (see SRSwaggerConfig for example).
* Also need a security filter for each core system to force restricted access (web services can only be call from the same local cloud, all management services are restricted to sysop, other services may only be called by a predefined set of core systems). See examples in the other core systems.
* No unit tests here. At least you have to check that the web services and db services works exactly as intended when called them with bad payload/invalid parameters. There are a ton of examples for this in the other core systems.
* As Szvetlin mentions before no documentation.
* Code convention: this is lower priority but would be good if your code looks similar than ours (the biggest difference here is the positions of opening brackets).

2020-01-28 10:27 UTC, mzsilak commented
Thank you for your review. I'll work on the mentioned points.
I have a question regarding the unit tests. Are you guys ok with using an pre-loaded in-memory database for the unit tests?

2020-04-06 19:09 UTC, mzsilak commented
@tsvetlin Please start a new review.

2020-04-14 15:08 UTC, tsvetlin commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SystemRegistryRepository.java
> +    Optional<SystemRegistry> findBySystem(final System system);
@mzsilak

2020-04-15 13:56 UTC, rbocsi requested changes
See inline comments.

I don't finished the review (parts of the system registry are still on progress), but the github review tool is so f*cking slow now, so I try to submit this and then add new comments if I found anything else.

Edit: I managed to finish the review.

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SecurityUtilities.java
> +        final X509Certificate[] certificates = (X509Certificate[]) request.getAttribute(CommonConstants.ATTR_JAVAX_SERVLET_REQUEST_X509_CERTIFICATE);
potentional NullPointerException

You should check the input parameters in every public method. Please use an Assert at least.

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SecurityUtilities.java
> +        return Utilities.getCertCNFromSubject(principal.getName());
potentional NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SecurityUtilities.java
> +        final X509Certificate[] certificates = (X509Certificate[]) httpServletRequest.getAttribute(CommonConstants.ATTR_JAVAX_SERVLET_REQUEST_X509_CERTIFICATE);
potentional NullPointerExceptions

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SecurityUtilities.java
> +    public void authenticateCertificate(final String clientCN, final String requestTarget, final CertificateType minimumStrength) {
potentional NullPointerException (minimumStrength)

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SecurityUtilities.java
> +
check the inputs (in case of string you should check for empty string too)

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SecurityUtilities.java
> +        try {
potentional NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SecurityUtilities.java
> +        }
I know it never happens, but maybe you should throw an arrowheadexception

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SecurityUtilities.java
> +        final String commonName = creationRequestDTO.getCommonName();
potentional NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/CertificateAuthorityDriver.java
> +        logger.traceEntry("signCertificate: {}", request);
You should check the input before you try to connect to CA

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/DriverUtilities.java
> +        final ServiceQueryFormDTO form = new ServiceQueryFormDTO.Builder(service.getServiceDefinition())
potentional NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/DriverUtilities.java
> +        final ServiceQueryFormDTO serviceQueryForm = new ServiceQueryFormDTO.Builder(service.getServiceDefinition())
potentional NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/DriverUtilities.java
> +        return createUri(entry.getSecure(), entry.getProvider(), entry.getServiceUri());
potentional NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/DriverUtilities.java
> +        return createUri(entry.getSecure(), entry.getProvider(), entry.getServiceUri());
potentional NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/DriverUtilities.java
> +    public UriComponents createUri(final ServiceSecurityType securityType, final SystemResponseDTO system, final String serviceUri) {
potentional NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/DriverUtilities.java
> +        return UriComponentsBuilder.newInstance()
potentional NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/DriverUtilities.java
> +        return service.getServiceDefinition() + CoreCommonConstants.URI_SUFFIX;
potentional NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/OrchestrationDriver.java
> +        logger.traceEntry("orchestrate: {}", request);
you should check the input

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/ServiceRegistryDriver.java
> +        logger.traceEntry("queryRegistry: {}", form);
You should check the input

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/ServiceRegistryDriver.java
> +        logger.traceEntry("registerService: {}", request);
you should check the input

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/ServiceRegistryDriver.java
> +        logger.traceEntry("unregisterService: {}, {}, {}, {}", serviceDefinition, providerName, providerAddress, providerPort);
you should check the inputs

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/DTOConverter.java
> +
you should check the input

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/DTOConverter.java
> +	{
you should check the input

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/DTOConverter.java
> +
you should check the input

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/DTOConverter.java
> +		final List<DeviceRegistryResponseDTO> list = new ArrayList<>();
you should check the input

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/CertificateType.java
> +        final String[] split = commonName.split("\\.");
possible NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/CertificateType.java
> +        return this.strength >= minimumStrengthType.strength;
possible NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/DeviceRegistryOnboardingResponseDTO.java
> +        setId(dto.getId());
possible NPE

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/SystemQueryFormDTO.java
> +			this.deiceNameRequirements = deiceNameRequirements;
typo in the parameter name

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/SystemQueryFormDTO.java
> +		private String deiceNameRequirements;
typo in the member name

2020-04-15 13:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/SystemRegistryOnboardingResponseDTO.java
> +        this.setId(dto.getId());
possible NPE

2020-04-15 13:56 UTC, rbocsi commented on deviceregistry/pom.xml
> +		</dependency>
this dependency is in the parent pom as well

2020-04-15 13:56 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +    public DeviceRegistryOnboardingWithNameResponseDTO onboardAndRegisterDeviceRegistry(final DeviceRegistryOnboardingWithNameRequestDTO request,
I don't see any database-related line in this method. So why is this in the database service?
You should create a new class for non db services, mabe DeviceRegistryService

2020-04-15 13:56 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +    //-------------------------------------------------------------------------------------------------
In every public method in this class, you should check the input parameters at least with Asserts. I know you already check them in the ws layer, but these are public methods, and that means they can be called anywhere from the program. And in the future somebody may call them to implement a new feature (for example register devices based on a file), and that new feature will skip all the validations.

2020-04-15 13:56 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +        final var signingResponse = signCertificate(certificateSigningRequest);
This is NOT an error, just a personal comment. 

Please don't use this var nonsense in the code, it's lazy and makes more difficult to understand the code. Any decent IDE can insert the appropriate type into the source file almost automatically so please use proper type names. When I see this line, I want to know what is the return value of signCertificate, and yes, I can find it, but I shouldn't have.

2020-04-15 13:56 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +    public DeviceRegistryOnboardingWithCsrResponseDTO onboardAndRegisterDeviceRegistry(final DeviceRegistryOnboardingWithCsrRequestDTO request) {
not db-related

2020-04-15 13:56 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +                    // no service definition found
update or delete comment

2020-04-15 13:56 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +            logger.debug("Potential system providers after filtering: {}", registryList.size());
update the debug message

2020-04-15 13:56 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +            final Optional<DeviceRegistry> systemRegistry = deviceRegistryRepository.findById(id);
rename the variable

2020-04-15 13:56 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +            return systemRegistry.orElseThrow(() -> new InvalidParameterException("System Registry with id of '" + id + "' does not exist"));
change the error message

2020-04-15 13:56 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +        final Optional<Device> optProvider = deviceRepository.findByDeviceNameAndMacAddress(validateName, validatedMacAddress);
is a device a provider? Maybe you should rename these variables

2020-04-15 13:56 UTC, rbocsi commented on deviceregistry/src/deb/arrowhead-deviceregistry.service
> +After=network.target mysql.target arrowhead-serviceregistry
This assumes that the service registry runs on the same machine thant the device registry.

2020-04-15 13:56 UTC, rbocsi commented on onboarding/src/deb/arrowhead-onboarding.service
> +After=network.target mysql.target arrowhead-serviceregistry arrowhead-authorization arrowhead-certificate-authority arrowhead-orchestration
This assumes that all these arrowhead systems runs on the same machine than the onboarding

2020-04-15 13:56 UTC, rbocsi commented on onboarding/src/main/java/eu/arrowhead/core/onboarding/OnboardingApplicationInitListener.java
> +                       CoreSystemService.SERVICE_REGISTRY_REGISTER_SERVICE);
`This last one won't work, since the SR does not register its own services into the db, so the mechanism (UriCrawler) won't find it. You have to create this URL manually and and it to the arrowheadContext in the customInit method

2020-04-15 13:56 UTC, rbocsi commented on onboarding/src/main/java/eu/arrowhead/core/onboarding/database/service/OnboardingDBService.java
> +public class OnboardingDBService {
Why is this name to DB service, there is no database related code anywhere (package name is also wrong)
Check inputs in the public methods

2020-04-15 13:56 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorDriver.java
> +		// disabled for demo purposes
restore the original functionality

2020-04-15 13:56 UTC, rbocsi commented on scripts/onboarding_controller_privileges.sql
> +REVOKE ALL, GRANT OPTION FROM 'onboarding_controller'@'localhost';
the onboarding does not use the database at all (except the log table). So, remove all grant lines except for the log table.

2020-04-15 13:56 UTC, rbocsi commented on scripts/system_registry_privileges.sql
> +REVOKE ALL, GRANT OPTION FROM 'service_registry'@'%';
not service_registry, but system_registry

2020-04-15 13:56 UTC, rbocsi commented on systemregistry/pom.xml
> +		<dependency>
this one is already in the parent pom.

2020-04-15 13:56 UTC, rbocsi commented on systemregistry/src/deb/arrowhead-systemregistry.service
> +After=network.target mysql.target arrowhead-serviceregistry
It assumes that the service registry is on the same machine than the system registry

2020-04-15 14:09 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/database/service/SystemRegistryDBService.java
> +    public SystemRegistryOnboardingWithNameResponseDTO onboardAndRegisterSystemRegistry(final SystemRegistryOnboardingWithNameRequestDTO request,
no db-related code here

2020-04-15 14:12 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/database/service/SystemRegistryDBService.java
> +        final Optional<System> optionalSystem = systemRepository.findBySystemNameAndAddressAndPort(systemName, address, port);
when we create a system we convert its name and address to lowercase. So before you try to find a system, you have to make the same modifications on  the input parameters.

2020-04-15 14:14 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/database/service/SystemRegistryDBService.java
> +        final String validatedMacAddress = Utilities.lowerCaseTrim(macAddress);
validate mac address format just like in the device registry

2020-04-15 14:15 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/database/service/SystemRegistryDBService.java
> +        final Optional<Device> optProvider = deviceRepository.findByDeviceNameAndMacAddress(validateName, validatedMacAddress);
mac address pattern validation

2020-04-17 09:04 UTC, mzsilak commented
@rbocsi I performed the requested changes

2020-04-17 09:15 UTC, rbocsi commented
@mzsilak Sorry, I don't see any new commits. Are you sure you push them?

2020-04-17 10:35 UTC, mzsilak commented
@rbocsi I am not sure what I am doing wrong in Github. I pushed the commit to https://github.com/mzsilak/core-java-spring/commits/onboarding

2020-04-17 11:25 UTC, rbocsi commented
I've checked your modifications in your repository (because it doesn't not appear in the pull request for some unknown reasons). I find some issues:

1. The database privigileges files are wrong (except the onboarding). In the system_registry_privileges.sql this line revokes the privileges from the wrong db user
REVOKE ALL, GRANT OPTION FROM 'service_registry'@'%';
From the device_registry_privileges and system_registry_priviliges files you removed to much grant lines. For example, the Device entity in the code references the SystemRegistry entity, so the device_registry user needs permission to the system_registry table. And the SystemRegistry entity references the System, so the device_registry users need permission to the system_ table, and so on. Same problems with the system_registry db user.

2. Not addressed issue: SecurityUtilities.extractAndSetPublicKey()

 } catch (final IOException e) {
    logger.fatal("ByteArrayInputStream should never throw an IOException, but it just did ..");
 }
 
 I know it never happens, but maybe you should throw an arrowheadexception
 
3. Not addressed issue: SecurityUtilities.extractOrGenerateKeyPair

  Possible NPE: final String commonName = creationRequestDTO.getCommonName();

4. Not addressed issue: CertificateAuthorityDriver.signCertificate

  You should check the input before you try to connect to CA
  
5. Not addressed issues: DriverUtilities.findByServiceRegistry, DriverUtilities.findUriByOrchestrator, DriverUtilities.createUri (all of them), DriverUtilities.createEchoUri, DriverUtilities.getCoreSystemServiceKey

  potentional NPE because of the lack of input check

5. Not addressed issue: OrchestrationDriver.orchestrate

  you should check the input

6. Not addressed issues: ServiceRegistryDriver (3x input checking, see comments above, I'm to lazy to write it down again)
7. Not addressed issues: DTOConverter (4x input checking, see comments above)  
8. Not addressed issues: in various DTO classes (4x input checking, 2x typo, see comments above)
9. Not addressed issue: deviceregistry/pom.xml unnecessary dependency
10. Not addressed issues: DeviceRegistryDBService: none of the previously mentioned issues are fixed, only some changes because of some refactoring
11. Not addressed issue: OnboardApplicationInitListener
12. Not addressed issues: OnboardingDBService: none of the the previously mentioned issues are fixed, only some changes because of some refactoring
13. Why did you change the orchestrator's pom. By removing the dependency the orchestrator will not work anymore. Please revert this change
14. Not addresses issue: systemregistry/pom.xml unnecessary dependency

I don't find other new commit since the last review, but github has some issues with this pull request, so maybe I just don't see it. But commit 81094bdd67774acb2dcfeeb23d89b6b191ab4096 does not address most of the original requests and introduces at least two new issues.

In the future, please communicate explicitly if you want a code review beacuse it seems to me that this commit is just a small step to address the issues. On the other hand, the comment "I performed the requested changes" suggests to me that you have finished the fixes but you clearly don't.

2020-04-17 11:41 UTC, mzsilak commented
I am sorry, I actually missed a lot of comments.
I am not sure what is wrong with github or my local copy right now. I am even missing some classes in the code.

2020-04-17 11:58 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/drivers/CertificateAuthorityDriver.java
> +        logger.traceEntry("signCertificate: {}", request);
I have to disagree here and on all other driver classes. I see the caller and the target system responsible for any check. The CertificateAuthorityDriver (for example) should not need to know which if any parameters are mandatory.

2020-04-17 12:06 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/drivers/CertificateAuthorityDriver.java
> +        logger.traceEntry("signCertificate: {}", request);
Ok, here I just suggest that the request is null or not, nothing more. Because if the request is null, you can spare the web service request.

2020-04-17 12:08 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/drivers/ServiceRegistryDriver.java
> +        logger.traceEntry("queryRegistry: {}", form);
I see the caller and the target system responsible for any check. The ServiceRegistryDriver should not need to know which, if any, parameters are mandatory.

2020-04-17 12:08 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/drivers/ServiceRegistryDriver.java
> +        logger.traceEntry("registerService: {}", request);
I see the caller and the target system responsible for any check. The ServiceRegistryDriver should not need to know which, if any, parameters are mandatory.

2020-04-17 12:08 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/drivers/ServiceRegistryDriver.java
> +        logger.traceEntry("unregisterService: {}, {}, {}, {}", serviceDefinition, providerName, providerAddress, providerPort);
I see the caller and the target system responsible for any check. The ServiceRegistryDriver should not need to know which, if any, parameters are mandatory.

2020-04-17 12:12 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/drivers/OrchestrationDriver.java
> +        logger.traceEntry("orchestrate: {}", request);
I see the caller and the target system responsible for any check. The OrchestrationDriver should not need to know which, if any, parameters are mandatory.

2020-04-17 12:28 UTC, mzsilak commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +    public DeviceRegistryOnboardingWithNameResponseDTO onboardAndRegisterDeviceRegistry(final DeviceRegistryOnboardingWithNameRequestDTO request,
It is further down the line at `retValue.load(registerDeviceRegistry(request));`. I know that `registerDeviceRegistry` is itself Transactional, so the classes could be split, but I'd like to keep the 2 methods of onboardAndRegisterDeviceRegistry(...) in the same place.

2020-04-17 12:40 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +    public DeviceRegistryOnboardingWithNameResponseDTO onboardAndRegisterDeviceRegistry(final DeviceRegistryOnboardingWithNameRequestDTO request,
Ok, sorry, I missed that line.

2020-04-17 12:50 UTC, rbocsi commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +    public DeviceRegistryOnboardingWithCsrResponseDTO onboardAndRegisterDeviceRegistry(final DeviceRegistryOnboardingWithCsrRequestDTO request) {
Ok, I find the db-related line here too. So you can ignore this comment.

2020-04-17 13:01 UTC, mzsilak commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +    //-------------------------------------------------------------------------------------------------
I've added the Assertion checks for Objects where it was missing. Most methods already had a validation further down below.

2020-04-17 13:03 UTC, mzsilak commented on deviceregistry/src/main/java/eu/arrowhead/core/deviceregistry/database/service/DeviceRegistryDBService.java
> +    public DeviceRegistryOnboardingWithCsrResponseDTO onboardAndRegisterDeviceRegistry(final DeviceRegistryOnboardingWithCsrRequestDTO request) {
It is further down the line at retValue.load(registerDeviceRegistry(request));. I know that registerDeviceRegistry is itself Transactional, so the classes could be split, but I'd like to keep the 2 methods of onboardAndRegisterDeviceRegistry(...) in the same place.

2020-04-17 13:08 UTC, mzsilak commented on onboarding/src/main/java/eu/arrowhead/core/onboarding/OnboardingApplicationInitListener.java
> +                       CoreSystemService.SERVICE_REGISTRY_REGISTER_SERVICE);
Yes, I remember that. What is the reason behind this? AFAIK I updated the ServiceRegistryApplicationInitListener to register all its services.

I don't see a point in a service registry if I have to create uri manually _in some cases_.

2020-04-17 13:20 UTC, mzsilak commented
@rbocsi I think I resolved all but one inline comment now.
Please see my question/solution on regarding onboarding/src/main/java/eu/arrowhead/core/onboarding/OnboardingApplicationInitListener.java

2020-04-17 13:43 UTC, rbocsi commented on onboarding/src/main/java/eu/arrowhead/core/onboarding/OnboardingApplicationInitListener.java
> +                       CoreSystemService.SERVICE_REGISTRY_REGISTER_SERVICE);
To be honest, I missed it that you add new code to the ServiceRegistryApplicationInitListener. With SR the modification there is no problem in the OnboardingApplicationInitListener.

When we wrote the Service Registry we didn't think that the SR should register its services into its own db. Because to access the SR from an other system, you should call the SR's query web-service (so you have to know where is the SR is, and how to call the query). So why would we put the query service into the db? And this is true for the query service. 

But it is not true for the register/unregister. So you are right to put those into the db to minimize the exceptional cases.

2020-04-20 09:43 UTC, rbocsi requested changes
Thanks @mzsilak. These changes (and our discussion about the url creation) addressed all but one issue: the privilileges of the db users. The users device_registry and system_registry needs a lot more privileges.

I try to explain. Let's take a look to the Device entity. To create such entity, the related db_user (device_registry) needs to rights to the device table, but it is not enough. Because of this line (and its annotations)
`private Set<SystemRegistry> systemRegistryEntries = new HashSet<>();`
it needs rights to the system_registry table, and the whole thing is transitive, so it needs rights to the system_ table (because of SystemRegistry entity), service_registy, authorization_intra_cloud, authorization_inter_cloud (because of System entity) tables, and so on.

It's crazy, and you have to do it even if the fetch is set to lazy. We try to figure out something to reduce the number of rights (maybe in 5.0), but for now, you have to do this.

2020-04-21 07:45 UTC, mzsilak commented
Hello @rbocsi, I did the changes to the device and system privileges scripts (2 commits). Please verify if my changes are sufficient.

2020-04-21 11:34 UTC, rbocsi approved these changes
seems ok to me.

@tsvetlin I think you can make the merge.

2020-04-22 14:26 UTC, merged