Qos monitoring tasks
eclipse-arrowhead/core-java-spring pull request #172
Opened 2020-01-31 11:01 UTC by MaGaMeGa

2020-01-31 11:11 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/QoSIntraPingMeasurementLog.java
> +	private QoSMeasurementType measurementType;
why? It's value never change

2020-01-31 11:13 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/QoSIntraPingMeasurementLogDetails.java
> +	private String measuredSystemAddress;
this is a duplicate of the parent entry's field

2020-01-31 11:35 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/QoSIntraMeasurementRepository.java
> +	public Optional<QoSIntraMeasurement> findBySystemAndMeasurementType(final System systemToCheck,final QoSMeasurementType ping);
rename second parameter

2020-01-31 11:36 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/QoSIntraPingMeasurementLogRepository.java
> +	Optional<QoSIntraPingMeasurementLog> findByMeasuredAt(final ZonedDateTime aroundNow);
missing public
rename parameter

2020-01-31 11:39 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/CountRestarterTask.java
> +	private QoSIntraMeasurementPingRepository qoSIntraMeasurementPingRepository;
refactor to a db service class

2020-01-31 11:39 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/CountRestarterTask.java
> +	@Transactional (rollbackFor = ArrowheadException.class)
refactor to a db service class

2020-01-31 11:40 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/CountRestarterTask.java
> +			qoSIntraMeasurementPingRepository.saveAndFlush(qoSIntraPingMeasurement);
don't save one at a time, use list save instead

2020-01-31 11:41 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/CountRestarterTaskConfig.java
>  	private boolean ttlScheduled;
remove if not used

2020-01-31 11:41 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/CountRestarterTaskConfig.java
>  	private int ttlInterval;
remove if not used

2020-01-31 11:42 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/CountRestarterTaskConfig.java
> +	private static final String CRONE_EXPRESSION_MIDNIGHT_EVERY_DAY= "0 0 0 ? * * *";
it's not crone, it's CRON

2020-01-31 11:43 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/CountRestarterTaskConfig.java
>  		if (ttlScheduled) {
why the if?

2020-01-31 11:44 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/CountRestarterTaskConfig.java
> +			logger.info("Pin task adjusted with ttl interval: {} minutes", ttlInterval);
it's not a pin task (not even PING)

2020-01-31 11:45 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +	@Autowired
refactor every repository usage to a db service

2020-01-31 11:46 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		final Set<SystemResponseDTO> systems = getSystemsToMessure();
typo messure => measure

2020-01-31 11:46 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		logger.debug("getSystemToMessure started...");
same typo here

2020-01-31 11:47 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +	@Transactional (rollbackFor = ArrowheadException.class)
refactor to a db service.

A note here: @Transactional on private methods means nothing. Spring will not notice it nor use it.

2020-01-31 11:48 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		measurement.setMeasurementType(QoSMeasurementType.PING);
you already set these in the constructor

2020-01-31 11:49 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		final int jitterWithoutTimeout = calculateJitterWithoutTimeout(responseList);
these values shoud be calculated in one method (in one for loop)

2020-01-31 11:50 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		final int receivedInThisPing = getReceivedInThisPing(responseList);
and these two in the same for loop

2020-01-31 11:50 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		final int lostPerMeasurementPercent = (int) (receivedInThisPing == 0 ? 1 : ((double)receivedInThisPing / (double)sentInThisPing) * 100);
as well as this one

2020-01-31 11:52 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		}
why do you need this? You already have a measurement object

2020-01-31 11:54 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		pingMeasurement.setReceivedAll(receivedAll + getReceivedInThisPing(responseList));
it seems to me that sent, sentAll, etc.. is unnecessary, because they are always 0.
Also, getReceivedInThisPing is recalculated. Why?

2020-01-31 11:56 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		return measurement;
need try/catch block to handle db errors in every db methods

2020-01-31 11:58 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		handelPingMeasurement(address, measurement, responseList, aroundNow);
type handel => handle (or Händel, if you mean the composer)

2020-01-31 11:59 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		final int jitterWithoutTimeout = calculateJitterWithoutTimeout(responseList);
in one method, in one for loop

2020-01-31 11:59 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +
in the previously mentioned method

2020-01-31 11:59 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		final int lostPerMeasurementPercent = (int) (receivedInThisPing == 0 ? 100 : 100 - ( (double)receivedInThisPing / (double)sentInThisPing ) * 100);
and this one two

2020-01-31 12:00 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +			pingMeasurement = createPingMeasurement(measurement, responseList, aroundNow);
not good, now createPingMeasurement will calculate all statistics again you just calculated here

2020-01-31 12:03 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		try {
don't need try/catch here

2020-01-31 12:04 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +				logger.info(formattedResponse);
debug

2020-01-31 12:05 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +			request.setHost (address);
you have a ping timeout constant  but you don't use it.

2020-01-31 12:07 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +			}
this is the same than accessedAt  = pingMeasurement.getLastAccessAt();

2020-01-31 12:08 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		mean = (double)sum / (double)count;
one cast is enough

2020-01-31 12:09 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		mean = (double)sum / (double)responseList.size();
one cast

2020-01-31 12:10 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +					min = (int) icmpPingResponse.getDuration();
maybe round here

2020-01-31 12:10 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +					max = (int) icmpPingResponse.getDuration();
maybe round here

2020-01-31 12:11 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		final int jitter = (int) Math.sqrt(sumOfDiffs / responseList.size());
maybe round

2020-01-31 12:13 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +	private int calculateJitterWithTimeout(final List<IcmpPingResponse> responseList) {
in mean, jitter calculations you should use double internally, and cast the result to int to minimalize error in the calculation

2020-01-31 12:14 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTaskConfig.java
>  	private boolean ttlScheduled;
no need for that

2020-01-31 12:14 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTaskConfig.java
>  		if (ttlScheduled) {
remove if, if qos is active we need this task to run

2020-01-31 12:31 UTC, rbocsi requested changes
see inline comments

2020-02-10 16:04 UTC, MaGaMeGa commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/CountRestarterTask.java
> +	@Transactional (rollbackFor = ArrowheadException.class)
fixed

2020-02-10 16:04 UTC, MaGaMeGa commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/CountRestarterTask.java
> +	private QoSIntraMeasurementPingRepository qoSIntraMeasurementPingRepository;
fixed

2020-02-10 16:04 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/repository/QoSIntraPingMeasurementLogRepository.java
> +	Optional<QoSIntraPingMeasurementLog> findByMeasuredAt(final ZonedDateTime aroundNow);
fixed

2020-02-10 16:04 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/repository/QoSIntraMeasurementRepository.java
> +	public Optional<QoSIntraMeasurement> findBySystemAndMeasurementType(final System systemToCheck,final QoSMeasurementType ping);
fixed

2020-02-10 16:04 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/entity/QoSIntraPingMeasurementLogDetails.java
> +	private String measuredSystemAddress;
fixed

2020-02-10 16:04 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/entity/QoSIntraPingMeasurementLog.java
> +	private QoSMeasurementType measurementType;
fixed

2020-02-18 13:45 UTC, rbocsi commented on README.md
> +| `countStartedAt` | TimeSatmp value of the last reset of sent and received fields|
same field twice, delete one

2020-02-18 13:45 UTC, rbocsi commented on README.md
> +| `countStartedAt` | TimeSatmp value of the last reset of sent and received fields|
same field twice

2020-02-18 13:54 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +				result.setMetadata( new HashMap<String, String>());
use diamond here

2020-02-18 13:57 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/QoSMonitorController.java
> +	@ApiOperation(value = GET_QOS_MONITOR_PING_MEASUREMENTS_MGMT_DESCRIPTION, response = Page.class, tags = { CoreCommonConstants.SWAGGER_TAG_MGMT })
it doesn't return a Page, it returns a PingMeasurementListResponseDTO

2020-02-18 14:03 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/database/service/QoSDBService.java
> +			throw new ArrowheadException("Requested system" + NOT_IN_DB_ERROR_MESSAGE);
maybe use InvalidParameterException here

2020-02-18 14:05 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/database/service/QoSDBService.java
> +	public QoSIntraMeasurement getMeasurement(final SystemResponseDTO systemResponseDTO) {
maybe rename to getOrCreate...

2020-02-18 14:10 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/measurement/properties/PingMeasurementProperties.java
> +	private int availableFromSuccessPercet;
maybe typo here perceNt

2020-02-18 14:17 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
>  		logger.debug("getSystemToMessure started...");
typo in debug message: messure => measure

2020-02-18 14:24 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		final double meanResponseTimeWithoutTimeout = sumOfDurationForMeanResponseTimeWithoutTimeout / meanResponseTimeWithoutTimeoutMembersCount;
possible division by zero

2020-02-18 14:25 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		final double jitterWithTimeout = Math.sqrt(sumOfDiffsForJitterWithTimeout / meanResponseTimeWithoutTimeoutMembersCount);
possible division by zero

2020-02-18 14:31 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		} catch (final Throwable ex) {
is this necessary?

2020-02-18 14:33 UTC, rbocsi commented on qos-monitor/src/main/java/eu/arrowhead/core/qos/quartz/task/PingTask.java
> +		if (availableFromSuccessPercent <= Math.round(availablePercent)) {
change this if/else to return availableFromSuccessPercent <= Math.round(availablePercent)

2020-02-18 14:35 UTC, rbocsi commented on qos-monitor/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +    "name": "ping.available_from_success_percet",
typo

2020-02-18 14:35 UTC, rbocsi commented on qos-monitor/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +    "description": "A description for 'ping.available_from_success_percet'"
typo

2020-02-18 14:36 UTC, rbocsi commented on qos-monitor/src/main/resources/application.properties
> +ping.available_from_success_percet=1
typo

2020-02-18 14:39 UTC, rbocsi commented on qos-monitor/src/test/java/eu/arrowhead/core/qos/database/service/QoSDBServiceTest.java
> +	private static final String NOT_AVAILABLE_SORTABLE_FIELD_ERROR_MESSAGE = " sortable field  is not available.";
there is two spaces between field and is. Remove one (you have to do the same is QoSDBService too)

2020-02-18 14:44 UTC, rbocsi requested changes
see inline comments

2020-02-20 08:59 UTC, rbocsi approved these changes

2020-02-20 09:00 UTC, merged