Certificate authority
eclipse-arrowhead/core-java-spring pull request #188
Opened 2020-02-26 14:57 UTC by kovacskristof

Updated Certificate Authority to version 4.1.3

2020-02-27 10:00 UTC, tsvetlin commented
Hello! 

Thank you for submitting the request. We will review it shortly. Could you please provide documentation? 

* README, check it for examples of other core systems
* Documents to the documentation folder

2020-03-04 10:00 UTC, rbocsi commented on certificate-authority/src/deb/control/postinst
> +		ah_cert_signed_system sysop
unnecessary (sysop is created when SR is installed)

2020-03-04 10:01 UTC, rbocsi commented on certificate-authority/src/deb/control/postrm
> +			${AH_SYSTEMS_DIR}/sysop/sysop.p12
unnecessary

2020-03-04 10:03 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityController.java
> +		return certificateAuthorityService.signCertificate(request);
need some validation about request object (checking mandatory fields are filled, invariants, etc.)

2020-03-04 10:11 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityService.java
> +    }
you should check cloud certificate for problems here (not in the getCloudCommonName), this will cause exception early at startup, not when somebody wants to use the CA

2020-03-04 10:12 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityService.java
> +            throw new ServiceConfigurationError("Cannot get cloud common name from server cert.", e);
make sure this can't happen at this time (check earlier)

2020-03-04 10:12 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityService.java
> +        final JcaPKCS10CertificationRequest csr = CertificateAuthorityUtils.decodePKCS10CSR(request);
input validation here, before anything else

2020-03-04 10:14 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            final byte[] csrBytes = Base64.getDecoder().decode(csr.getEncodedCSR());
potential NullPointerException if csr is null

2020-03-04 10:16 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            return Base64.getEncoder().encodeToString(certificate.getEncoded());
if certificate is null this is an unhandled NPE

2020-03-04 10:17 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        final String clientCN = Utilities.getCertCNFromSubject(csr.getSubject().toString());
potentional NPE (csr, maybe cloudCN too)

2020-03-04 10:21 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        Security.addProvider(new BouncyCastleProvider());
It is unnecessary to add provider more than once. Maybe you shoud do this in the CertificateAuthorityApplicationInitListnener's customInit() method.

2020-03-04 10:22 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            ContentVerifierProvider verifierProvider = new JcaContentVerifierProviderBuilder().setProvider("BC")
Please don't use string literals in the code (except for log messages and exception messages). Use constants instead.

2020-03-04 10:23 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            if (!csr.isSignatureValid(verifierProvider)) {
potentional NPE

2020-03-04 10:23 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            return csr.getPublicKey();
potentional NPE

2020-03-04 10:24 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        /**
don't use documentation comments inside of a method use /* */ instead.

2020-03-04 10:30 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            builder.addExtension(Extension.basicConstraints, true, new BasicConstraints(false));
not enough extension. We need Subject Alternative Name (SAN) extensions as well because otherwise the hostname verifiers will always reject the certificates because the an Arrowhead system not necesserally run on a computer that's hostname match with the common name of that system. You need to provider a set of hostnames and IP addresses as an input and add every element of this input set to the certificate as a SAN.

2020-03-04 10:30 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        JcaContentSignerBuilder signerBuilder = new JcaContentSignerBuilder("SHA512withRSA").setProvider("BC");
use constants

2020-03-04 10:32 UTC, rbocsi commented on certificate-authority/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +  },
these are unnecessery in the system I think

2020-03-04 10:32 UTC, rbocsi commented on certificate-authority/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +  },
and this one too

2020-03-04 10:40 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/CertificateSigningRequestDTO.java
> +
maybe this would be a good place to add the hostname/IP addess set/list for the SAN extensions

2020-03-04 10:42 UTC, rbocsi commented on docker-all/example/sql/setup.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`subscription_publisher_connection` TO 'certificate_authority'@'localhost';
since CA does not use DB, it only need access to the logs table

2020-03-04 10:42 UTC, rbocsi commented on docker-all/example/sql/setup.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`subscription_publisher_connection` TO 'certificate_authority'@'%';
since CA does not use DB, it only need access to the logs table

2020-03-04 10:43 UTC, rbocsi commented on scripts/certificate_authority_privileges.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`subscription_publisher_connection` TO 'certificate_authority'@'localhost';
since CA does not use DB, it only need access to the logs table

2020-03-04 10:43 UTC, rbocsi commented on scripts/certificate_authority_privileges.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`subscription_publisher_connection` TO 'certificate_authority'@'%';
since CA does not use DB, it only need access to the logs table

2020-03-04 10:44 UTC, rbocsi requested changes
See inline comments

2020-03-04 15:17 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityService.java
> +    }
That was the plan, somehow managed to miss it. Now it should work like that...

2020-03-04 15:18 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityService.java
> +            throw new ServiceConfigurationError("Cannot get cloud common name from server cert.", e);
Fixed.

2020-03-04 15:19 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        Security.addProvider(new BouncyCastleProvider());
Good point, fixed.

2020-03-04 15:19 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            ContentVerifierProvider verifierProvider = new JcaContentVerifierProviderBuilder().setProvider("BC")
Done

2020-03-04 15:20 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        /**
Fixed

2020-03-04 15:20 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        JcaContentSignerBuilder signerBuilder = new JcaContentSignerBuilder("SHA512withRSA").setProvider("BC");
Done

2020-03-05 16:38 UTC, kovacskristof commented on certificate-authority/src/deb/control/postinst
> +		ah_cert_signed_system sysop
Copy-paste issue, removed it.

2020-03-05 16:39 UTC, kovacskristof commented on certificate-authority/src/deb/control/postrm
> +			${AH_SYSTEMS_DIR}/sysop/sysop.p12
Copy-paste issue, removed it.

2020-03-05 16:42 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            builder.addExtension(Extension.basicConstraints, true, new BasicConstraints(false));
SAN extensions are added from the CSR now

2020-03-05 16:43 UTC, kovacskristof commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/CertificateSigningRequestDTO.java
> +
SAN extensions are added to the certificate from the CSR now

2020-03-05 16:43 UTC, kovacskristof commented on docker-all/example/sql/setup.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`subscription_publisher_connection` TO 'certificate_authority'@'localhost';
Copy-paste issue, removed it.

2020-03-05 16:43 UTC, kovacskristof commented on docker-all/example/sql/setup.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`subscription_publisher_connection` TO 'certificate_authority'@'%';
Copy-paste issue, removed it.

2020-03-05 16:43 UTC, kovacskristof commented on scripts/certificate_authority_privileges.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`subscription_publisher_connection` TO 'certificate_authority'@'localhost';
Copy-paste issue, removed it.

2020-03-05 16:44 UTC, kovacskristof commented on scripts/certificate_authority_privileges.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`subscription_publisher_connection` TO 'certificate_authority'@'%';
Copy-paste issue, removed it.

2020-03-05 16:44 UTC, kovacskristof commented on certificate-authority/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +  },
Copy-paste issue, removed it. Added the CA properties.

2020-03-05 16:45 UTC, kovacskristof commented on certificate-authority/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +  },
Copy-paste issue, removed it. Added the CA properties.

2020-03-10 14:45 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityController.java
> +		return certificateAuthorityService.signCertificate(request);
Added validation

2020-03-10 14:49 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            final byte[] csrBytes = Base64.getDecoder().decode(csr.getEncodedCSR());
The NPE is handled

2020-03-10 14:49 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            return Base64.getEncoder().encodeToString(certificate.getEncoded());
The NPE is handled

2020-03-10 14:49 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        final String clientCN = Utilities.getCertCNFromSubject(csr.getSubject().toString());
Added checks for null

2020-03-10 14:50 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            if (!csr.isSignatureValid(verifierProvider)) {
The NPE is handled.

2020-03-10 14:50 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            return csr.getPublicKey();
The NPE is handled.

2020-03-10 15:37 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityService.java
> +        final JcaPKCS10CertificationRequest csr = CertificateAuthorityUtils.decodePKCS10CSR(request);
Added validation

2020-03-16 10:41 UTC, kovacskristof commented
Added the requested modifications.

2020-03-18 10:55 UTC, rbocsi commented on certificate-authority/src/deb/control/postrm
> +        rmdir ${AH_SYSTEMS_DIR}/sysop 2>/dev/null || true
why CA delete this folder? Not its responsibility

2020-03-18 11:03 UTC, rbocsi approved these changes
I found only one small issue (see inline comment). After fixing that you can merge to development

2020-03-18 11:28 UTC, kovacskristof commented on certificate-authority/src/deb/control/postrm
> +        rmdir ${AH_SYSTEMS_DIR}/sysop 2>/dev/null || true
Sorry, copy-paste residue...

2020-03-18 11:31 UTC, kovacskristof commented
Thank you for the review!

2020-03-31 14:16 UTC, tsvetlin commented
Thank you for your contribution @kovacskristof!

2020-03-31 14:16 UTC, merged