Choreographer v2.1
eclipse-arrowhead/core-java-spring pull request #201
Opened 2020-04-01 13:57 UTC by szkris

Added plan execution with Choreographer with one major dependency. Each provider endpoint that wants to use the Choreographer must provide a structure to receive input from the Choreographer and when done call back to the respective endpoint. More about this in the documentation later. New features will be added continuously.

2020-04-02 11:26 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerApplicationInitListener.java
> +    public JmsListenerContainerFactory<?> myFactory(ConnectionFactory connectionFactory,
use method name to tell the reader what the method does

2020-04-02 11:28 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +import org.springframework.web.bind.annotation.*;
don't use wildcards in import

2020-04-02 11:39 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +        for (final ChoreographerPlanRequestDTO request : requests) {
this means partially creation is possible. For example you have 3 plans in the list, and the second one is not valid. In this case the first plan will be stored in the DB, the second one fails, the request will return an error, the third one will be ignored.

You have two choices here:
1) The whole request is one transaction. This means you have to check ALL plans first, the call ONE method in the DB service leayer that stores the plans in one transaction.
2) Multiple transactions. This means validation can't return error immediately. You have to collect results/errors. You have to create a return object which tells the user, that for example the first and third plan was ok, but second one failed because of this error.

2020-04-02 11:54 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +            JmsTemplate jmsTemplate = applicationContext.getBean(JmsTemplate.class);
this one always the same object, so you can use @Autowired instead of this line

If you want different object, you have to create a bean definition with prototype score somewhere, and then use the getBean(name,class) version here.

2020-04-02 11:56 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +            JmsTemplate jmsTemplate = applicationContext.getBean(JmsTemplate.class);
same here

2020-04-02 11:57 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +        JmsTemplate jmsTemplate = applicationContext.getBean(JmsTemplate.class);
same here

2020-04-02 13:26 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +            if (Utilities.isEmpty(name)) {
I suggest to make one try/catch block from the two, beacuse the error handlings are the same

2020-04-02 13:30 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +            final Optional<ChoreographerStep> stepOptional = choreographerStepRepository.findByNameAndActionId(name, actionId);
Are you sure this will work? The Srping Data JPA works on entites not on tables. And the entity ChoreographerStep has not have a long field names actionId. It has a ChoreographerAction field named action. So this one should be findByNameAndAction with a ChoreographerAction second parameter.

For that reason I suggest to load the action first, then check the unique constraint

2020-04-02 13:34 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +        	final Optional<ChoreographerStep> stepOptional = choreographerStepRepository.findByNameAndActionId(stepName, actionId);
same here twice (findByNameAndAction)

2020-04-02 13:35 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +                        choreographerStepNextStepConnectionRepository.save(new ChoreographerStepNextStepConnection(stepEntry, nextStep));
there is a version of save that can save a collection of entities which is more effective. So in the loop just create and collect the entities then use that version

2020-04-02 13:46 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
>              final ChoreographerAction actionEntry = choreographerActionRepository.save(action);
safer to use saveAndFlush here

2020-04-02 13:54 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +        if (!ChoreographerPlan.SORTABLE_FIELDS_BY.contains(validatedSortField)) {
sort by names would be useful

2020-04-02 14:01 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +    public ChoreographerRunningStep setRunningStepStatus(final long runningStepId, final String status, final String message) {
no check for status and message (in the previous method you check these)

2020-04-02 14:04 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +                ChoreographerSession sessionEntry = choreographerSessionRepository.saveAndFlush(new ChoreographerSession(planOptional.get(), "Initiated"));
Please don't use hard-coded strings in the code (except for error and log messages). Use constants instead

In this particular case (statuses), it would be best to use enum values instead

2020-04-02 14:05 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +                session.setStatus("Done");
same here

2020-04-02 14:09 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +                createWorklog("Session with ID of " + sessionId + " finished successfully.", "");
How do you know that the state param means the the session is finished successfully?

2020-04-03 08:02 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +    @JmsListener(destination = "start-session")
I don't familiar with @JmsListener but sources on the internet suggests you need to use an @EnableJMS annotation on the main class to make sure Spring searches for @JmsListener annotations

2020-04-03 08:03 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        choreographerDBService.setSessionStatus(sessionId, "Running");
use constants or enums instead of hard-coded string literals

2020-04-03 08:05 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +                e.printStackTrace();
this one writes stacktrace to the  standard error.
use logger to make sure error messages go to the log file (and the db)

2020-04-03 08:06 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        System.out.println(sessionFinishedStepDataDTO.getSessionId() + " " + sessionFinishedStepDataDTO.getRunningStepId());
this one writes the message to the standard output
use logger instead

2020-04-03 08:07 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        choreographerDBService.setRunningStepStatus(runningStepId, "Done", "Step execution is done.");
use constant or enum for the status

2020-04-03 08:08 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        System.out.println(currentStep.getName());
use log

2020-04-03 08:08 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +            System.out.println("Step has no next steps therefore it should be checked if can go to next action.");
use log

2020-04-03 08:09 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +                System.out.println(runningStepInstance.getId());
use log

2020-04-03 08:11 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +                if (!runningStepInstance.getStatus().equals("Done")) {
use constant/enum

2020-04-03 08:16 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +                    System.out.println("canGoToNextStep should be set to false");
use log

2020-04-03 08:17 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +                if (runningStepInstance.getStep().getNextSteps().isEmpty() && !runningStep.getStatus().equals("Done")) {
use enum/constant

2020-04-03 08:24 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +                    System.out.println("-------------------  canGoToNextAction should be set to false!!!! --------------------");
use log

2020-04-03 08:25 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +                System.out.println("If there is next Action then it should run now! Testing needed.");
log

2020-04-03 08:25 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +            System.out.println(nextStep.getNextStepEntry().getName() + " in for");
log

2020-04-03 08:25 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +                // TODO: 2020. 03. 18. Test what happens if there is multiple Actions in a plan.
did you do that test? Then delete the todo

2020-04-03 08:26 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +                if (!prevRunningStep.getStatus().equals("Done")) {
use constant/enum

2020-04-03 08:46 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +    public void receiveStartSessionMessage(ChoreographerStartSessionDTO startSessionDTO) {
This one works as intended only if something is guaranteed that messages are processed sequentially. I'm not famailiar with JMSListener, but you should check this. Maybe you need a different Listener Container or set the "concurrentConsumers" property of the DefaultMessageListenerContainer to 1 (according to the result of  a quick Google search)

2020-04-03 08:49 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        }
since requesterSystem is always the same you should make it to the member and export this to an init method (annotated with @PostConstruct)

2020-04-03 08:55 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        }
what if the orchestrationResultList is empty? What happens with the plan execution? Aborted? In that case you should store that in the db.

2020-04-03 08:55 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +            httpService.sendRequest(uri, HttpMethod.POST, Void.class, runningStepDataDTO);
Are you sure that every service in a plan is a POST request with no result?

2020-04-03 08:56 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        return choreographerDBService.registerRunningStep(stepId, sessionId, "Running", "Step running is initiated and search for provider started.");
enum/constant for status

2020-04-03 08:57 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        final OrchestrationResponseDTO orchestrationResponse = queryOrchestrator(orchestrationForm);
what if error happens in this step (an ArrowheadException occurs)? You need to handle that.

2020-04-03 09:00 UTC, rbocsi commented on choreographer/src/test/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBServiceTest.java
>  import eu.arrowhead.common.Utilities;
I skip the review of the tests because it is possible that these will change as the production code changes

2020-04-03 09:06 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerAction.java
> +import javax.persistence.*;
don't use wildcards in imports

2020-04-03 09:08 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerPlan.java
> +import javax.persistence.*;
wildcard

2020-04-03 09:09 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerRunningStep.java
> +import javax.persistence.*;
wildcard

2020-04-03 09:10 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerRunningStep.java
> +
maybe a finishDate or an updatedAt like in the other tables

2020-04-03 09:11 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerSession.java
> +import javax.persistence.*;
wildcards

2020-04-03 09:12 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerSession.java
> +
maybe a finishedAt or updatedAt like in the other tables

maybe a message for possible errors (if a plan execution is failed or aborted)

2020-04-03 09:12 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerStep.java
> +import javax.persistence.*;
wildcard

2020-04-03 09:14 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerStep.java
> +    private String parameters;
these two are currently not used when you call the service in the Receiver

2020-04-03 09:16 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerStep.java
> +    private int quantity;
I don't find any usage of this one in the Receiver

2020-04-03 09:17 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerWorklog.java
> +    private String message;
should be not null

2020-04-03 09:20 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/ChoreographerStartSessionDTO.java
> +import javax.jms.Session;
remove unused imports

2020-04-03 09:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/ChoreographerStepRequestDTO.java
> +        this.quantity = quantity;
this one should use the other constructor instead of a partial copy.

this(name, serviceName, null, null, nextStepNames, quantity);

2020-04-03 09:25 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/DTOConverter.java
> +		final List<ChoreographerNextStepResponseDTO> result = new ArrayList<>(nextSteps.size());
I'd check here for null just to be safe.

2020-04-03 09:31 UTC, rbocsi commented on scripts/create_arrowhead_tables.sql
>  ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
missing foreign key constaint for first_action_id

2020-04-03 09:34 UTC, rbocsi requested changes
see inline comments

2020-04-17 08:23 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerApplicationInitListener.java
> +    public JmsListenerContainerFactory<?> myFactory(ConnectionFactory connectionFactory,
ok

2020-04-17 08:27 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +import org.springframework.web.bind.annotation.*;
ok

2020-04-17 08:50 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +            JmsTemplate jmsTemplate = applicationContext.getBean(JmsTemplate.class);
Used @Autowired.

2020-04-17 08:51 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +        JmsTemplate jmsTemplate = applicationContext.getBean(JmsTemplate.class);
same

2020-04-17 09:01 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +            if (Utilities.isEmpty(name)) {
All multiple try/catch blocks with the same error handling merged to one block.

2020-04-17 09:16 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +                        choreographerStepNextStepConnectionRepository.save(new ChoreographerStepNextStepConnection(stepEntry, nextStep));
Collected connections and used saveAll for saving in one transaction.

2020-04-17 09:21 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +        if (!ChoreographerPlan.SORTABLE_FIELDS_BY.contains(validatedSortField)) {
Sort by name enabled.

2020-04-17 09:22 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +    public ChoreographerRunningStep setRunningStepStatus(final long runningStepId, final String status, final String message) {
Added input check.

2020-04-17 09:27 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +                ChoreographerSession sessionEntry = choreographerSessionRepository.saveAndFlush(new ChoreographerSession(planOptional.get(), "Initiated"));
Used enum and got messages from there.

2020-04-17 09:27 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +                session.setStatus("Done");
same here

2020-04-17 09:36 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +                createWorklog("Session with ID of " + sessionId + " finished successfully.", "");
Rewrote the worklog message to reflect new status.

2020-04-17 09:36 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +    @JmsListener(destination = "start-session")
It works like this too.

2020-04-17 09:39 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        choreographerDBService.setSessionStatus(sessionId, "Running");
ok

2020-04-17 09:40 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +                e.printStackTrace();
Used logger.

2020-04-17 09:42 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +    public void receiveStartSessionMessage(ChoreographerStartSessionDTO startSessionDTO) {
It is processed sequentially by default.

2020-04-17 09:43 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +            httpService.sendRequest(uri, HttpMethod.POST, Void.class, runningStepDataDTO);
By implementation only these services can use the Choreographer now.

2020-04-17 09:46 UTC, szkris commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerAction.java
> +import javax.persistence.*;
Removed wildcards which should not be there by settings but IntelliJ is shit.

2020-04-17 09:47 UTC, szkris commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerPlan.java
> +import javax.persistence.*;
same

2020-04-17 09:50 UTC, szkris commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerStep.java
> +    private String parameters;
Will be used in future version.

2020-04-17 09:54 UTC, szkris commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerStep.java
> +    private int quantity;
Will be implemented in future releases.

2020-04-17 09:54 UTC, szkris commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerWorklog.java
> +    private String message;
ok

2020-04-17 09:55 UTC, szkris commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/ChoreographerStepRequestDTO.java
> +        this.quantity = quantity;
ok

2020-04-17 10:06 UTC, szkris commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/DTOConverter.java
> +		final List<ChoreographerNextStepResponseDTO> result = new ArrayList<>(nextSteps.size());
ok

2020-04-17 10:10 UTC, szkris commented on scripts/create_arrowhead_tables.sql
>  ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
Guess I did that with a faulty merge.

2020-04-17 11:21 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        }
Added requesterSystem private field and moved initalization to a @PostConstruct init method.

2020-04-17 13:55 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +        for (final ChoreographerPlanRequestDTO request : requests) {
Removed bulk creation because it was not consistent with other CoreSystems. Next version will be more consistent to other coresystems.

2020-04-17 15:07 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        final OrchestrationResponseDTO orchestrationResponse = queryOrchestrator(orchestrationForm);
If an error happens than it should stop execution because the Orchestrator must run for the Choreographer to work.

2020-04-17 15:13 UTC, szkris commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerRunningStep.java
> +
Added updatedAt field.

2020-04-17 15:17 UTC, szkris commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ChoreographerSession.java
> +
added updatedAt field.

I think a message field is unneccesary because the running step in the session already has a status field which would be the same here leading to redundant and possibly not consistent error messages.

2020-04-17 15:30 UTC, szkris commented
PR is mergable, fixed all minor errors and bugs, added functions according to suggestions.

2020-04-20 08:41 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +    @ResponseBody public void registerPlans(@RequestBody final ChoreographerPlanRequestDTO request) {
rename to registerPlan

2020-04-20 08:51 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +                session.setStatus(StepStatus.DONE.toString());
it would be better if the Session entity has an enum field instead of a String. See Relay't type field for example.

2020-04-20 08:53 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
>      public ChoreographerSession setSessionStatus(final long sessionId, final String state) {
use the enum as a parameter. The enum type must be public in that case and in the common module

2020-04-20 08:56 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +        choreographerDBService.setSessionStatus(sessionId, StepStatus.RUNNING.toString());
use the enum as parameter (and entry field). Enum type should be public and in the common module

2020-04-20 08:59 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/jms/Receiver.java
> +                if (!runningStepInstance.getStatus().equals(StepStatus.DONE.toString())) {
if you really use enums (in the runningStepInstance too), you can use == instead of equals on enum values.

2020-04-20 09:04 UTC, rbocsi requested changes
One minor typo, and a lazy way of using enums. 
If you use enums to represent status (sesson and action), you should use it everywhere (in entities, in method parameters, etc), not just use the enumValue.toString().

2020-04-20 09:54 UTC, szkris commented
Typo fixed, enum usage is more sophisticated.

2020-04-20 11:01 UTC, rbocsi approved these changes
Seems ok to me.

2020-04-20 12:04 UTC, merged