Service registry mgmt impl
eclipse-arrowhead/core-java-spring pull request #21
Opened 2019-06-20 07:02 UTC by MaGaMeGa

2019-06-20 08:43 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +	public static ServiceRegistryGrouppedResponseDTO convertServiceRegistryEntriesToServiceRegistryGrouppedResponseDTO(final Page<ServiceRegistry> serviceRegistryEntries) {
grouped is one p

2019-06-20 08:44 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		final Map<Long, ServicesGrouppedBySystemsResponseDTO> servicesBySystemId= new HashMap<>();
space before =

2019-06-20 08:44 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +			//Creating ServicesGrouppedBySystemsResponseDTO
space after //

2019-06-20 08:46 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +			//Filling up AutoCompleteDataResponseDTO
space after //

2019-06-20 08:47 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +				//Creating ServicesGrouppedByServiceDefinitionAndInterfaceResponseDTO
space after //

2019-06-20 08:49 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		final List<ServicesGrouppedBySystemsResponseDTO> servicesGrouppedBySystemsResponseDTOList = new ArrayList<>();
grouped is one p

2019-06-20 08:49 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		final List<ServicesGrouppedByServiceDefinitionAndInterfaceResponseDTO> servicesGrouppedByServiceDefinitionAndInterfaceResponseDTOList = new ArrayList<>();
grouped is one p

2019-06-20 08:50 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/ServiceRegistryGrouppedResponseDTO.java
> +package eu.arrowhead.common.dto;
rename group is one p

2019-06-20 08:52 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/ServicesGrouppedByServiceDefinitionAndInterfaceResponseDTO.java
> +package eu.arrowhead.common.dto;
rename class group is one p

2019-06-20 08:54 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/ServicesGrouppedBySystemsResponseDTO.java
> +package eu.arrowhead.common.dto;
rename class grouped is one p

2019-06-20 08:58 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	private static final String SERVICE_REGISTRY_MGMT_URI = CommonConstants.MGMT_URI;
remove just use the common contant

2019-06-20 08:59 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	private static final String SERVICE_REGISTRY_MGMT_GROUPPED_URI = SERVICE_REGISTRY_MGMT_URI + "/groupped";
rename grouped is one p

2019-06-20 09:00 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	private static final String GET_SERVICE_REGISTRY_HTTP_400_MESSAGE = "Could not retrive service registry entries";
type retriEve

2019-06-20 09:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("New Service Registry get request recieved with page: {} and item_per page: {}", page, size);
check this (maybe throws NullPointerException if page or size is not specified)

2019-06-20 09:03 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("Service Registry entries with page: {} and item_per page: {} succesfully retrived", page, size);
check this for possible NPE

2019-06-20 09:03 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("Service Registry entry with id: {} succesfully retrived", id);
typo retriEved

2019-06-20 09:06 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("New Service Registry get by Service Defintition request recieved with page: {} and item_per page: {}", page, size);
typo receive

2019-06-20 09:07 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("Service Registry entries with page: {} and item_per page: {} succesfully retrived", page, size);
typo retrieved
check for possible NPE

2019-06-20 09:07 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ApiOperation(value = "Return all service registry entries groupped for frontend usage", response = ServiceRegistryGrouppedResponseDTO.class)
grouped is one p

2019-06-20 09:08 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@GetMapping(path = SERVICE_REGISTRY_MGMT_GROUPPED_URI)
grouped is one p

2019-06-20 09:09 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseBody public ServiceRegistryGrouppedResponseDTO getServiceRegistryGrouppedData() {
rename method group is one p

2019-06-20 09:09 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("New get request for groupped service registry data");
group is one p

2019-06-20 09:09 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("Groupped service registry data succesfully retrived");
group is one p

+typo retrieved

2019-06-20 09:12 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	public @ResponseBody ServiceRegistryResponseDTO registerMgmtService(@RequestBody final ServiceRegistryRequestDTO request) {
rename addServiceRegistry

2019-06-20 09:13 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseStatus(value = org.springframework.http.HttpStatus.OK)
remove this line

2019-06-20 09:14 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	public @ResponseBody ServiceRegistryResponseDTO updateMgmtService(@PathVariable(value = PATH_VARIABLE_ID) final long id,
rename updateServiceRegistry

2019-06-20 09:15 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseStatus(value = org.springframework.http.HttpStatus.OK)
remove this line

2019-06-20 09:15 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	public @ResponseBody ServiceRegistryResponseDTO mergeMgmtService(@PathVariable(value = PATH_VARIABLE_ID) final long id,
rename to mergeServiceRegistry

2019-06-20 09:20 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		if ( request.getProviderSystem() != null && !Utilities.isEmpty(request.getProviderSystem().getAddress())) {
no need space after ( and before )

2019-06-20 09:23 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +	public ServiceRegistryGrouppedResponseDTO getServiceReqistryEntriesForServiceRegistryGrouppedResponse() {
rename group is one p

2019-06-20 09:25 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		Assert.notNull(serviceDefinition, "serviceDefinition is null");
not enough check for blank too using Assert.isTrue instead

2019-06-20 09:28 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		final eu.arrowhead.common.database.entity.ServiceRegistry srEntry;
remove fully qualified name

2019-06-20 09:31 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			updateServiceRegistry(srEntry, serviceDefinition, provider, request.getServiceUri(), endOfValidity, request.getSecure(), metadataStr, version,
srEntry = update...

2019-06-20 09:32 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		} catch (final DateTimeParseException ex) {
catch InvalidParameterException and rethrow

2019-06-20 09:33 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		final eu.arrowhead.common.database.entity.ServiceRegistry srEntry;
use simple name & import

2019-06-20 09:42 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			final String metadataStr = Utilities.map2Text(request.getMetadata());
check if null and use metadata from db

2019-06-20 09:42 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			final int version = request.getVersion() == null ? 1 : request.getVersion().intValue();
if null use value from db

2019-06-20 09:42 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			final List<String> valideatedInterfacesTemp = new ArrayList<>(srEntry.getInterfaceConnections().size());
type validated

2019-06-20 09:43 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			final List<String> valideatedInterfaces = request.getInterfaces() != null && request.getInterfaces().size() > 0 ? request.getInterfaces() : valideatedInterfacesTemp;
typo validated

2019-06-20 09:45 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			mergeServiceRegistry(srEntry, serviceDefinition, provider, request.getServiceUri(), endOfValidity, request.getSecure(), metadataStr, version,
srEnty = merge...

2019-06-20 09:45 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		} catch (final DateTimeParseException ex) {
catch InvalidParameterException and rethrow

2019-06-20 09:46 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		Assert.notNull(serviceDefinition, "Service definition is not specified.");
Assert.notNull to srEntry

2019-06-20 09:48 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if( serviceDefinition != null ) {
unneccessary if body needed

2019-06-20 09:49 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if ( validatedServiceUri != null ) {
unneccessary if body needed

2019-06-20 09:49 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if( metadataStr != null ) {
unneccessary if body needed

2019-06-20 09:51 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +
check if  intf connections set of srEntry is empty

2019-06-20 09:52 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +	private ServiceRegistry mergeServiceRegistry(final ServiceRegistry srEntry, final ServiceDefinition serviceDefinition, final System provider,
this is public and transactional

2019-06-20 09:53 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		Assert.notNull(serviceDefinition, "Service definition is not specified.");
srEntry not null assert

2019-06-20 09:57 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if( serviceDefinition != null ) {
unneccessary if body needed

2019-06-20 09:57 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if ( validatedServiceUri != null ) {
unneccessary if body needed

2019-06-20 09:58 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if( metadataStr != null ) {
unneccessary if body needed

2019-06-20 10:00 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +
check if srEntry's set is empty after the delete

2019-06-20 10:02 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +	//-------------------------------------------------------------------------------------------------
call this method from the previous one (replace for loop)

2019-06-20 10:08 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			final ServiceDefinition serviceDefinition, final System provider) {
replace body to check equality using serviceDef and system ids

2019-06-20 10:10 UTC, rbocsi commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/ServiceRegistryControllerServiceRegistryTest.java
> +	private static final String SERVICE_REGISTRY_MGMT_GROUPPED_URI = CommonConstants.SERVICE_REGISTRY_URI + CommonConstants.MGMT_URI + "/groupped";
group is one p

2019-06-20 10:19 UTC, rbocsi commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/ServiceRegistryControllerServiceRegistryTest.java
> +				.param("service_definition", "test")
unneccessary query param

2019-06-20 10:19 UTC, rbocsi commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/ServiceRegistryControllerServiceRegistryTest.java
> +				.param("service_definition", "test")
unneccessary query param

2019-06-20 10:20 UTC, rbocsi commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/ServiceRegistryControllerServiceRegistryTest.java
> +				.param("service_definition", "test")
unneccessary query param

2019-06-20 10:20 UTC, rbocsi commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/ServiceRegistryControllerServiceRegistryTest.java
> +	public void testGetServiceRegistryGrouppedDataToCheckDTO() throws Exception {
rename group is one p

2019-06-20 10:23 UTC, rbocsi commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBServiceServiceRegistryTest.java
> +	//Tests of getServiceReqistryEntries
q = g

2019-06-20 10:24 UTC, rbocsi commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBServiceServiceRegistryTest.java
> +	//Tests of getServiceReqistryEntriesByServiceDefintion
q = g

2019-06-20 10:24 UTC, rbocsi commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBServiceServiceRegistryTest.java
> +	public void testGetServiceReqistryEntriesWithNotValidSortField() {
q = g

2019-06-20 10:24 UTC, rbocsi commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBServiceServiceRegistryTest.java
> +	public void testGetServiceReqistryEntriesByServiceDefintionWithNotValidSortField() {
q = g

2019-06-20 10:25 UTC, rbocsi commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBServiceServiceRegistryTest.java
> +	public void testGetServiceReqistryEntriesByServiceDefintionWithNotValidServiceDefinition() {
q = g

2019-06-20 11:10 UTC, rbocsi requested changes
Tomi

Please check ServiceRegistryDBService and rename all methods the contains Reqistry instead of Registry
Also there is a typo in DefinItion in some of those names

2019-06-20 11:21 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	private static final String SERVICE_REGISTRY_MGMT_URI = CommonConstants.MGMT_URI;
done

2019-06-20 11:23 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	public @ResponseBody ServiceRegistryResponseDTO registerMgmtService(@RequestBody final ServiceRegistryRequestDTO request) {
done

2019-06-20 11:25 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseStatus(value = org.springframework.http.HttpStatus.OK)
done

2019-06-20 11:27 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	public @ResponseBody ServiceRegistryResponseDTO updateMgmtService(@PathVariable(value = PATH_VARIABLE_ID) final long id,
done

2019-06-20 11:27 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseStatus(value = org.springframework.http.HttpStatus.OK)
done

2019-06-20 11:29 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	public @ResponseBody ServiceRegistryResponseDTO mergeMgmtService(@PathVariable(value = PATH_VARIABLE_ID) final long id,
done

2019-06-20 11:31 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		if ( request.getProviderSystem() != null && !Utilities.isEmpty(request.getProviderSystem().getAddress())) {
done

2019-06-20 11:35 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			updateServiceRegistry(srEntry, serviceDefinition, provider, request.getServiceUri(), endOfValidity, request.getSecure(), metadataStr, version,
done

2019-06-20 11:39 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		} catch (final DateTimeParseException ex) {
done

2019-06-20 11:42 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		final eu.arrowhead.common.database.entity.ServiceRegistry srEntry;
done

2019-06-20 11:48 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			final String metadataStr = Utilities.map2Text(request.getMetadata());
done

2019-06-20 11:49 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			final int version = request.getVersion() == null ? 1 : request.getVersion().intValue();
done

2019-06-20 11:51 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			final List<String> valideatedInterfacesTemp = new ArrayList<>(srEntry.getInterfaceConnections().size());
done

2019-06-20 11:51 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			final List<String> valideatedInterfaces = request.getInterfaces() != null && request.getInterfaces().size() > 0 ? request.getInterfaces() : valideatedInterfacesTemp;
done

2019-06-20 11:53 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			mergeServiceRegistry(srEntry, serviceDefinition, provider, request.getServiceUri(), endOfValidity, request.getSecure(), metadataStr, version,
done

2019-06-20 11:55 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		} catch (final DateTimeParseException ex) {
done

2019-06-20 11:57 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		Assert.notNull(serviceDefinition, "Service definition is not specified.");
done

2019-06-20 12:00 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if( serviceDefinition != null ) {
done

2019-06-20 12:00 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if ( validatedServiceUri != null ) {
done

2019-06-20 12:00 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if( metadataStr != null ) {
done

2019-06-20 13:46 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +
done

2019-06-20 13:48 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +	private ServiceRegistry mergeServiceRegistry(final ServiceRegistry srEntry, final ServiceDefinition serviceDefinition, final System provider,
done

2019-06-20 13:49 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		Assert.notNull(serviceDefinition, "Service definition is not specified.");
done

2019-06-20 13:52 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if( serviceDefinition != null ) {
done

2019-06-20 13:52 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if ( validatedServiceUri != null ) {
done

2019-06-20 13:52 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			if( metadataStr != null ) {
done

2019-06-20 13:52 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +
done

2019-06-20 13:57 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +	//-------------------------------------------------------------------------------------------------
done

2019-06-20 14:16 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +			final ServiceDefinition serviceDefinition, final System provider) {
done

2019-06-21 07:09 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +	public static ServiceRegistryGrouppedResponseDTO convertServiceRegistryEntriesToServiceRegistryGrouppedResponseDTO(final Page<ServiceRegistry> serviceRegistryEntries) {
done

2019-06-21 07:10 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		final Map<Long, ServicesGrouppedBySystemsResponseDTO> servicesBySystemId= new HashMap<>();
done

2019-06-21 07:10 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +			//Creating ServicesGrouppedBySystemsResponseDTO
done

2019-06-21 07:10 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +			//Filling up AutoCompleteDataResponseDTO
done

2019-06-21 07:10 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +				//Creating ServicesGrouppedByServiceDefinitionAndInterfaceResponseDTO
done

2019-06-21 07:11 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		final List<ServicesGrouppedBySystemsResponseDTO> servicesGrouppedBySystemsResponseDTOList = new ArrayList<>();
done

2019-06-21 07:12 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		final List<ServicesGrouppedByServiceDefinitionAndInterfaceResponseDTO> servicesGrouppedByServiceDefinitionAndInterfaceResponseDTOList = new ArrayList<>();
done

2019-06-21 07:22 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/ServiceRegistryGrouppedResponseDTO.java
> +package eu.arrowhead.common.dto;
done

2019-06-21 07:27 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/ServicesGrouppedByServiceDefinitionAndInterfaceResponseDTO.java
> +package eu.arrowhead.common.dto;
done

2019-06-21 07:29 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/ServicesGrouppedBySystemsResponseDTO.java
> +package eu.arrowhead.common.dto;
done

2019-06-21 07:30 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	private static final String GET_SERVICE_REGISTRY_HTTP_400_MESSAGE = "Could not retrive service registry entries";
done

2019-06-21 07:31 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("Service Registry entry with id: {} succesfully retrived", id);
done

2019-06-21 07:32 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ApiOperation(value = "Return all service registry entries groupped for frontend usage", response = ServiceRegistryGrouppedResponseDTO.class)
done

2019-06-21 07:33 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@GetMapping(path = SERVICE_REGISTRY_MGMT_GROUPPED_URI)
done

2019-06-21 07:33 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseBody public ServiceRegistryGrouppedResponseDTO getServiceRegistryGrouppedData() {
done

2019-06-21 07:34 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("New get request for groupped service registry data");
done

2019-06-21 07:35 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("Groupped service registry data succesfully retrived");
done

2019-06-21 07:36 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +	public ServiceRegistryGrouppedResponseDTO getServiceReqistryEntriesForServiceRegistryGrouppedResponse() {
done

2019-06-21 07:38 UTC, borditamas commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/ServiceRegistryControllerServiceRegistryTest.java
> +	private static final String SERVICE_REGISTRY_MGMT_GROUPPED_URI = CommonConstants.SERVICE_REGISTRY_URI + CommonConstants.MGMT_URI + "/groupped";
done

2019-06-21 07:40 UTC, borditamas commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/ServiceRegistryControllerServiceRegistryTest.java
> +	public void testGetServiceRegistryGrouppedDataToCheckDTO() throws Exception {
done

2019-06-21 07:41 UTC, borditamas commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBServiceServiceRegistryTest.java
> +	//Tests of getServiceReqistryEntries
done

2019-06-21 07:41 UTC, borditamas commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBServiceServiceRegistryTest.java
> +	public void testGetServiceReqistryEntriesWithNotValidSortField() {
done

2019-06-21 07:42 UTC, borditamas commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBServiceServiceRegistryTest.java
> +	//Tests of getServiceReqistryEntriesByServiceDefintion
done

2019-06-21 07:42 UTC, borditamas commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBServiceServiceRegistryTest.java
> +	public void testGetServiceReqistryEntriesByServiceDefintionWithNotValidSortField() {
done

2019-06-21 07:42 UTC, borditamas commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBServiceServiceRegistryTest.java
> +	public void testGetServiceReqistryEntriesByServiceDefintionWithNotValidServiceDefinition() {
done

2019-06-21 08:26 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		Assert.notNull(serviceDefinition, "serviceDefinition is null");
done

2019-06-21 08:28 UTC, borditamas commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/ServiceRegistryControllerServiceRegistryTest.java
> +				.param("service_definition", "test")
done

2019-06-21 08:28 UTC, borditamas commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/ServiceRegistryControllerServiceRegistryTest.java
> +				.param("service_definition", "test")
done

2019-06-21 08:30 UTC, borditamas commented on serviceregistry/src/test/java/eu/arrowhead/core/serviceregistry/ServiceRegistryControllerServiceRegistryTest.java
> +				.param("service_definition", "test")
done

2019-06-21 08:58 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("New Service Registry get request recieved with page: {} and item_per page: {}", page, size);
checked and not throws NPE

2019-06-21 08:58 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("Service Registry entries with page: {} and item_per page: {} succesfully retrived", page, size);
checked and not throws NPE

2019-06-21 08:59 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("New Service Registry get by Service Defintition request recieved with page: {} and item_per page: {}", page, size);
checked and not throws NPE

2019-06-21 08:59 UTC, borditamas commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("Service Registry entries with page: {} and item_per page: {} succesfully retrived", page, size);
checked and not throws NPE

2019-06-21 09:22 UTC, borditamas reviewed
My parts are fixed

2019-06-25 08:22 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +		final eu.arrowhead.common.database.entity.ServiceRegistry srEntry;
done

2019-06-25 08:28 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("New Service Registry get by Service Definitition request recieved with page: {} and item_per page: {}", page, size);
new typo

2019-06-25 08:46 UTC, rbocsi reviewed
seems ok

2019-06-25 08:48 UTC, merged