Auth intra local impl
eclipse-arrowhead/core-java-spring pull request #22
Opened 2019-06-25 13:50 UTC by borditamas

2019-06-25 14:00 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/AuthorizationController.java
> +	private static final String ID_NOT_VALID_ERROR_MESSAGE = "Id must be greater then 0.";
typo thAn

2019-06-25 14:01 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/AuthorizationController.java
> +		logger.debug("IntraCloudAuthorizations  with page: {} and item_per page: {} succesfully retrived", page, size);
typo retriEved succesSfully

2019-06-25 14:03 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/AuthorizationController.java
> +			exceptionMsg = isConsumerIdInvalid ? exceptionMsg +" 'invalid consumer id'" : exceptionMsg;
need space between + and "

2019-06-25 14:05 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/AuthorizationController.java
> +			throw new BadPayloadException(exceptionMsg, HttpStatus.SC_BAD_REQUEST, CommonConstants.AUTHORIZATIOIN_URI + INTRA_CLOUD_AUTHORIZATION_MGMT_URI);
need commas between reasons (last comma should be removed)

2019-06-25 14:07 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/AuthorizationController.java
> +			throw new BadPayloadException(exceptionMsg, HttpStatus.SC_BAD_REQUEST, CommonConstants.AUTHORIZATIOIN_URI + INTRA_CLOUD_AUTHORIZATION_CHECK_URI);
commas

2019-06-25 14:08 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +		logger.debug("getIntraCloudAuthorizationEntries started..");
3 dots

2019-06-25 14:12 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +	public IntraCloudAuthorization createIntraCloudAuthorization(final long consumerId, final long providerId, final long serviceDefinitionId) {
need an other version for bulk creation

2019-06-25 14:12 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +				throw new InvalidParameterException(exceptionMessage);
commas

2019-06-25 14:13 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +				String exceptionMessage = "Following entities are not availables:";
typo available

2019-06-25 14:13 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +				throw new InvalidParameterException(exceptionMessage);
commas

2019-06-25 14:13 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +	//-------------------------------------------------------------------------------------------------
delete this

2019-06-25 14:14 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +	public IntraCloudAuthorizationListResponseDTO createBulkIntraCloudAuthorizationResponse(final long consumerId, final List<Long> providerIds, final List<Long> serviceDefinitionIds) {
use the bulk creation instead of for loop

2019-06-25 14:15 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +	public IntraCloudAuthorizationCheckResponseDTO checkIntraCloudAuthorizationRequestResponse(final long consumerId, final long serviceDefinitionId, final List<Long> providerIds) {
RequestResponse funny name

2019-06-25 14:15 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +				throw new InvalidParameterException(exceptionMsg);
commas

2019-06-25 14:17 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +			final Optional<IntraCloudAuthorization> optional = intraCloudAuthorizationRepository.findByConsumerIdAndProviderIdAndServiceDefinitionId(consumerId, providerId, serviceDefinitionId);
is this works? There are no ids in the IntraCloudAuthorization entity only other enitities

2019-06-25 14:24 UTC, rbocsi requested changes
see inline comments

let's talk about creation DTO & logic

2019-06-26 12:24 UTC, borditamas commented
Changed as discussed

2019-06-26 13:33 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +							//not throwing exception as in this bulk operation case should be only a warning
this is an error thow exception

2019-06-26 13:36 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +	public IntraCloudAuthorizationCheckResponseDTO checkIntraCloudAuthorizationRequest(final long consumerId, final long serviceDefinitionId, final List<Long> providerIds) {
use set

2019-06-26 13:37 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
>  		try {
remove try/catch

2019-06-26 13:39 UTC, rbocsi commented on authorization/src/test/java/eu/arrowhead/core/authorization/AuthorizationControllerIntraCloudTest.java
> +			.content(objectMapper.writeValueAsBytes(new IntraCloudAuthorizationRequestDTO((long) 0, createIdList(1, 1), createIdList(1, 2))))
0L

2019-06-26 13:42 UTC, rbocsi commented on authorization/src/test/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBServiceIntraCloudTest.java
> +	@Test (expected = InvalidParameterException.class)
test with null

2019-06-26 13:42 UTC, rbocsi commented on authorization/src/test/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBServiceIntraCloudTest.java
> +	public void testCreateBulkIntraCloudAuthorizationResponseWithEmptyProviderIds() {
test with empty set

2019-06-26 13:44 UTC, rbocsi requested changes
see inline comments

2019-06-27 07:23 UTC, rbocsi approved these changes
seems ok

2019-06-27 07:28 UTC, merged