Certificate Authority management interface
eclipse-arrowhead/core-java-spring pull request #227
Opened 2020-05-26 07:21 UTC by kovacskristof

2020-05-26 09:45 UTC, borditamas commented
Hello! Is this PR ready for review?

2020-05-27 19:00 UTC, kovacskristof commented
Hi! Documentation still needs some update, but apart from that I think it is mostly ready for review.

2020-05-29 11:18 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityController.java
> +			throw new InvalidParameterException("Invalid id");
throw BadPayloadException instead

2020-05-29 11:20 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityController.java
> +	@ApiOperation(value = "Add trusted public key", response = String.class, tags = { CoreCommonConstants.SWAGGER_TAG_MGMT })
response class is not String

2020-05-29 11:21 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityController.java
> +			throw new InvalidParameterException("Invalid id");
throw BadPayloadException here

2020-05-29 11:25 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityService.java
> +        return certificateDbService.getcertificateEntries(page, size, direction, sortField);
name of the called method is not camelCase.

2020-05-29 11:27 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        try {
missing null check

2020-05-29 11:29 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            final byte[] requestBytes = Base64.getDecoder().decode(encodedCert);
you should check input before trying to decode to avoid NPE

2020-05-29 11:32 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            throw new InvalidParameterException("Cannot parse certificate, because: " + ex.getMessage(), ex);
ugly way to handle NPE. The execption message will be: "Cannot parse certificate, because: null" No so helpful.

2020-05-29 11:35 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        } catch (InvalidParameterException | NullPointerException e) {
same here, catching NPE is bad practice imho.

2020-05-29 11:36 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        } catch (CertificateEncodingException | NullPointerException e) {
same here and all the other methods in this class

2020-05-29 11:37 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        final ZonedDateTime now = ZonedDateTime.now();
checking input params

2020-05-29 11:39 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        encodedCertificateChain.add(CertificateAuthorityUtils.encodeCertificate(clientCertificate));
no need to use CertificateAuthorityUtils here. This method is in the same class.

2020-05-29 11:40 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        return new String(DigestUtils.sha256(data));
null check

2020-05-29 11:41 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        X509Certificate[] clientCerts = (X509Certificate[]) httpServletRequest
null check

2020-05-29 11:41 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CACertificateDBService.java
> +    CaCertificateRepository caCertificateRepository;
should be private

2020-05-29 11:45 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CACertificateDBService.java
> +    public CaCertificate saveCertificateInfo(final String commonName, final BigInteger serial, final String requesterCN,
missing @Transactional annotations
also you should catch every exception coming from the deeper DB layers, and rethrow as an ArrowheadException after logging.

2020-05-29 11:45 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CACertificateDBService.java
> +    public IssuedCertificatesResponseDTO getcertificateEntries(final int page, final int size,
use camelCase here

2020-05-29 11:47 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CACertificateDBService.java
> +    public CertificateCheckResponseDTO isCertificateValidNow(final BigInteger serial) {
catch db exceptions here (like in the previous method)

2020-05-29 11:51 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CACertificateDBService.java
> +        logger.debug("revokeCertificate started...");
null check

2020-05-29 11:53 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +    CaTrustedKeyRepository caTrustedKeyRepository;
should be private

2020-05-29 11:54 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +    public AddTrustedKeyResponseDTO addTrustedKey(AddTrustedKeyRequestDTO request) {
missing transactional

2020-05-29 11:57 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +            throw new BadPayloadException("Invalid request for addTrustedKey: (" + ex.getMessage() + ")", ex);
you know the the message here will always be "Invalid request for addTrustedKey: (null)", right?

Please don't try to catch NPE. Instead check your input and throw an InvalidParameterException with a HELPFUL error message.

2020-05-29 11:58 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +        Optional<CaTrustedKey> trustedKeyResult = caTrustedKeyRepository.findByHash(hash);
catch and rethrow DB exception

2020-05-29 11:59 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +    public void deleteTrustedKey(long id) {
missing transactional annotation
missing db exception handling

2020-05-29 12:12 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/AddTrustedKeyRequestDTO.java
> +    private ZonedDateTime validAfter;
In the core system's DTOs we use String fields to specify and return dates. The dates in the string are in UTC (see example here ServiceRegistryController.registerService endOfValidity). We have a utility method  Utilities.parseUTCStringToLocalZonedDateTime() to create ZonesDateTime from the string (there is an other one for the opposite transformation)

2020-05-29 12:12 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/AddTrustedKeyResponseDTO.java
> +    private ZonedDateTime validAfter;
same here

2020-05-29 12:13 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/CertificateCheckResponseDTO.java
> +    private ZonedDateTime producedAt;
same here (In this case you need to convert the ZonedDateTime to String by using the appropriate utility method)

2020-05-29 12:14 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/CertificateSigningRequestDTO.java
> +    private ZonedDateTime validAfter;
use String instead of ZonedDateTime

2020-05-29 12:16 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/IssuedCertificateDTO.java
> +    private ZonedDateTime createdAt;
same issue here

2020-05-29 12:16 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/TrustedKeyCheckResponseDTO.java
> +    private ZonedDateTime createdAt;
same issue here

2020-05-29 12:17 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/TrustedKeyDTO.java
> +    private ZonedDateTime createdAt;
same issue here

2020-05-29 12:18 UTC, rbocsi requested changes
see inline comments

2020-06-02 07:02 UTC, kovacskristof commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/TrustedKeyDTO.java
> +    private ZonedDateTime createdAt;
Changed ZonedDateTime to String in 6c9e343

2020-06-02 07:02 UTC, kovacskristof commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/TrustedKeyCheckResponseDTO.java
> +    private ZonedDateTime createdAt;
Changed ZonedDateTime to String in 6c9e343

2020-06-02 07:02 UTC, kovacskristof commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/IssuedCertificateDTO.java
> +    private ZonedDateTime createdAt;
Changed ZonedDateTime to String in 6c9e343

2020-06-02 07:03 UTC, kovacskristof commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/CertificateSigningRequestDTO.java
> +    private ZonedDateTime validAfter;
Changed ZonedDateTime to String in 6c9e343

2020-06-02 07:03 UTC, kovacskristof commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/CertificateCheckResponseDTO.java
> +    private ZonedDateTime producedAt;
Changed ZonedDateTime to String in 6c9e343

2020-06-02 07:03 UTC, kovacskristof commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/AddTrustedKeyResponseDTO.java
> +    private ZonedDateTime validAfter;
Changed ZonedDateTime to String in 6c9e343

2020-06-02 07:08 UTC, kovacskristof commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/AddTrustedKeyRequestDTO.java
> +    private ZonedDateTime validAfter;
Changed ZonedDateTime to String in 6c9e343

Note however that QoS also uses ZonedDateTime in its DTOs.

2020-06-02 07:13 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CACertificateDBService.java
> +    public CaCertificate saveCertificateInfo(final String commonName, final BigInteger serial, final String requesterCN,
Fixed in b0759108

2020-06-02 07:14 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CACertificateDBService.java
> +    public CertificateCheckResponseDTO isCertificateValidNow(final BigInteger serial) {
Fixed in b075910

2020-06-02 07:14 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CACertificateDBService.java
> +        logger.debug("revokeCertificate started...");
Fixed in b075910

2020-06-02 07:14 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +    public AddTrustedKeyResponseDTO addTrustedKey(AddTrustedKeyRequestDTO request) {
Fixed in b075910

2020-06-02 07:14 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +    public void deleteTrustedKey(long id) {
Fixed in b075910

2020-06-02 07:16 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityService.java
> +        return certificateDbService.getcertificateEntries(page, size, direction, sortField);
Fixed typo

2020-06-02 07:18 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +        Optional<CaTrustedKey> trustedKeyResult = caTrustedKeyRepository.findByHash(hash);
Fixed in b075910

2020-06-02 07:18 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CACertificateDBService.java
> +    public IssuedCertificatesResponseDTO getcertificateEntries(final int page, final int size,
Fixed typo

2020-06-02 07:21 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        encodedCertificateChain.add(CertificateAuthorityUtils.encodeCertificate(clientCertificate));
Fixed; result of moving the method.

2020-06-02 07:22 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CACertificateDBService.java
> +    CaCertificateRepository caCertificateRepository;
Fixed

2020-06-02 07:23 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +    CaTrustedKeyRepository caTrustedKeyRepository;
Fixed

2020-06-02 07:31 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityController.java
> +			throw new InvalidParameterException("Invalid id");
Changed exception type

2020-06-02 07:32 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityController.java
> +	@ApiOperation(value = "Add trusted public key", response = String.class, tags = { CoreCommonConstants.SWAGGER_TAG_MGMT })
Fixed swagger response type

2020-06-02 07:32 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityController.java
> +			throw new InvalidParameterException("Invalid id");
Changed exception type

2020-06-02 08:13 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        try {
Added null check

2020-06-02 08:13 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            final byte[] requestBytes = Base64.getDecoder().decode(encodedCert);
Added null check

2020-06-02 08:14 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +            throw new InvalidParameterException("Cannot parse certificate, because: " + ex.getMessage(), ex);
Added null check

2020-06-02 08:16 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        } catch (InvalidParameterException | NullPointerException e) {
Added null check

2020-06-02 08:21 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        } catch (CertificateEncodingException | NullPointerException e) {
Added null check

2020-06-02 08:23 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        final ZonedDateTime now = ZonedDateTime.now();
Added null check

2020-06-02 08:23 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        return new String(DigestUtils.sha256(data));
Added null check

2020-06-02 08:23 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/CertificateAuthorityUtils.java
> +        X509Certificate[] clientCerts = (X509Certificate[]) httpServletRequest
Added null check

2020-06-02 08:34 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +            throw new BadPayloadException("Invalid request for addTrustedKey: (" + ex.getMessage() + ")", ex);
Added null check

2020-06-02 09:00 UTC, kovacskristof commented
Thank you for the review, I modified the code according to the suggestions.

2020-06-02 12:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/AddTrustedKeyRequestDTO.java
> +    private ZonedDateTime validAfter;
in which class? We make mistakes too, so feel free to give feedback if you find one

2020-06-02 12:32 UTC, kovacskristof commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/AddTrustedKeyRequestDTO.java
> +    private ZonedDateTime validAfter;
In [QoSIntraMeasurementResponseDTO ](https://github.com/arrowhead-f/core-java-spring/blob/development/core-common/src/main/java/eu/arrowhead/common/dto/internal/QoSIntraMeasurementResponseDTO.java) and in [QoSIntraPingMeasurementResponseDTO](https://github.com/arrowhead-f/core-java-spring/blob/development/core-common/src/main/java/eu/arrowhead/common/dto/internal/QoSIntraPingMeasurementResponseDTO.java)

2020-06-02 13:02 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/AddTrustedKeyRequestDTO.java
> +    private ZonedDateTime validAfter;
thanks.

2020-06-03 09:22 UTC, rbocsi commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +        } catch (final Exception ex) {
missing
} catch (final InvalidParameterException ex) {
            logger.debug(ex.getMessage(), ex);
            throw ex;
} 
branch. InvalidParameterException is already an ArrowheadException so no need to wrap it into a new one. Also you lose the meaningful exception message.

2020-06-03 09:39 UTC, rbocsi commented
Thanks for the feedback about ZonedDateTime usage in QoS-related DTO. We will fix them. Also, I checked your fixes: most of them are good, however I find one problem (see inline comment).

2020-06-03 09:43 UTC, kovacskristof commented on certificate-authority/src/main/java/eu/arrowhead/core/certificate_authority/database/CATrustedKeyDBService.java
> +        } catch (final Exception ex) {
Fixed in 3a955364

2020-06-03 12:06 UTC, merged