Auth inter mgmt impl
eclipse-arrowhead/core-java-spring pull request #23
Opened 2019-06-26 07:55 UTC by MaGaMeGa

2019-06-26 08:50 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/AuthorizationController.java
> +		final InterCloudAuthorizationListResponseDTO intraCloudAuthorizationEntriesResponse = authorizationDBService.getInterCloudAuthorizationEntriesResponse(validatedPage, validatedSize, validatedDirecti
rename variable to inter*

2019-06-26 08:53 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/AuthorizationController.java
> +			exceptionMsg = isServiceDefinitionNotValid ? exceptionMsg + " ServiceDefinition is null" :  exceptionMsg ;
null or blank 
use commas between errors

2019-06-26 09:02 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +	public InterCloudAuthorizationListResponseDTO createInterCloudAuthorizationResponse(Long cloudId,
cloudId is primitive long

2019-06-26 09:02 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +	public Page<InterCloudAuthorization> createInterCloudAuthorization(Long cloudId, List<Long> serviceDefinitionIds) {
cloudId is primitive long

2019-06-26 09:03 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +			throw new InvalidParameterException("Cloud id can't be null and must be greater than 0.");
remove null from error message

2019-06-26 09:03 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +		for (final Long id : serviceDefinitionIds) {
check if the serviceDefinitionsIds list is null

2019-06-26 09:05 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +	private InterCloudAuthorization createNewInterCloudAuthorization(final Long cloudId, final Long serviceDefinitionId) {
cloudId is primitive long

2019-06-26 09:05 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +
remove check

2019-06-26 09:08 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +				throw new InvalidParameterException("SerdviceDefinition id can't be null and must be greater than 0.");
typo service

2019-06-26 09:09 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +			throw ex;
remove throw ex

2019-06-26 09:15 UTC, rbocsi commented on authorization/src/test/java/eu/arrowhead/core/authorization/AuthorizationControllerInterCloudTest.java
> +			.content(objectMapper.writeValueAsBytes(new InterCloudAuthorizationRequestDTO((long) 0, createIdList(1, 2))))
use 0L

2019-06-26 09:22 UTC, rbocsi commented on authorization/src/test/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBServiceInterCloudTest.java
> +
missing test to check serviceDefIds list/set is null

2019-06-26 09:23 UTC, rbocsi commented on authorization/src/test/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBServiceInterCloudTest.java
> +	@Test (expected = InvalidParameterException.class)
remove this test

2019-06-26 09:26 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/CommonConstants.java
> +	public static final String AUTHORIZATIOIN_URI = "/authorization";
remove this

2019-06-26 09:28 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/InterCloudAuthorizationRepository.java
> +	Optional<IntraCloudAuthorization> findByCloudIdAndServiceDefinitionId(long cloudId, long serviceDefinitionId);
change this to use entities

2019-06-26 09:29 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/CloudResponseDTO.java
> +	public CloudResponseDTO(long id, String operator, String name, String address, int port,
finals

2019-06-26 09:30 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/CloudResponseDTO.java
> +	private Boolean secure;
use primitive boolean 3x

2019-06-26 09:32 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/InterCloudAuthorizationRequestDTO.java
> +	public InterCloudAuthorizationRequestDTO(long cloudId,
use Long

2019-06-26 09:32 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/InterCloudAuthorizationResponseDTO.java
> +	public InterCloudAuthorizationResponseDTO(long id, CloudResponseDTO cloud,
finals

2019-06-26 09:34 UTC, rbocsi requested changes
see inline comments

2019-06-26 09:38 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/AuthorizationController.java
> +		final InterCloudAuthorizationListResponseDTO intraCloudAuthorizationEntriesResponse = authorizationDBService.getInterCloudAuthorizationEntriesResponse(validatedPage, validatedSize, validatedDirecti
done

2019-06-26 09:43 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/AuthorizationController.java
> +			exceptionMsg = isServiceDefinitionNotValid ? exceptionMsg + " ServiceDefinition is null" :  exceptionMsg ;
done

2019-06-26 10:52 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +	public InterCloudAuthorizationListResponseDTO createInterCloudAuthorizationResponse(Long cloudId,
done

2019-06-26 10:52 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +	public Page<InterCloudAuthorization> createInterCloudAuthorization(Long cloudId, List<Long> serviceDefinitionIds) {
done

2019-06-26 10:53 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +			throw new InvalidParameterException("Cloud id can't be null and must be greater than 0.");
done

2019-06-26 10:56 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +		for (final Long id : serviceDefinitionIds) {
done

2019-06-26 10:58 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +				throw new InvalidParameterException("SerdviceDefinition id can't be null and must be greater than 0.");
done

2019-06-26 11:14 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +			throw ex;
done

2019-06-26 11:15 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +	private InterCloudAuthorization createNewInterCloudAuthorization(final Long cloudId, final Long serviceDefinitionId) {
done

2019-06-26 11:16 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +
done

2019-06-26 11:30 UTC, MaGaMeGa commented on authorization/src/test/java/eu/arrowhead/core/authorization/AuthorizationControllerInterCloudTest.java
> +			.content(objectMapper.writeValueAsBytes(new InterCloudAuthorizationRequestDTO((long) 0, createIdList(1, 2))))
done

2019-06-26 11:32 UTC, MaGaMeGa commented on authorization/src/test/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBServiceInterCloudTest.java
> +	@Test (expected = InvalidParameterException.class)
done

2019-06-26 11:39 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/CommonConstants.java
> +	public static final String AUTHORIZATIOIN_URI = "/authorization";
done

2019-06-26 11:39 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/repository/InterCloudAuthorizationRepository.java
> +	Optional<IntraCloudAuthorization> findByCloudIdAndServiceDefinitionId(long cloudId, long serviceDefinitionId);
done

2019-06-26 11:39 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/CloudResponseDTO.java
> +	private Boolean secure;
done

2019-06-26 11:40 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/CloudResponseDTO.java
> +	public CloudResponseDTO(long id, String operator, String name, String address, int port,
done

2019-06-26 11:43 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/InterCloudAuthorizationRequestDTO.java
> +	public InterCloudAuthorizationRequestDTO(long cloudId,
done

2019-06-26 11:44 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/InterCloudAuthorizationResponseDTO.java
> +	public InterCloudAuthorizationResponseDTO(long id, CloudResponseDTO cloud,
done

2019-06-26 11:56 UTC, MaGaMeGa commented on authorization/src/test/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBServiceInterCloudTest.java
> +
done

2019-06-26 13:16 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
>  		try {
remove try/catch

2019-06-26 13:18 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
>  			String exceptionMessage = "Following id parameters are invalid: ";
use one line instead of 3

2019-06-26 13:18 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +			String exceptionMessage = "Following id parameters are not present in database: ";
use one line

2019-06-26 13:19 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +				logger.info(ex.getMessage());
debug

2019-06-26 13:19 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +				final InterCloudAuthorization interCloudAuthorization = new InterCloudAuthorization(cloud, serviceDefinition);
return new ...

2019-06-26 13:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/InterCloudAuthorizationRepository.java
> +	Optional<IntraCloudAuthorization> findByCloudAndServiceDefinition(Cloud cloud, ServiceDefinition serviceDefinition);
finals

2019-06-26 13:23 UTC, rbocsi requested changes
see inline comments

2019-06-26 13:40 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
>  		try {
done

2019-06-26 13:43 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
>  			String exceptionMessage = "Following id parameters are invalid: ";
done

2019-06-26 13:43 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +			String exceptionMessage = "Following id parameters are not present in database: ";
done

2019-06-26 13:45 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +				final InterCloudAuthorization interCloudAuthorization = new InterCloudAuthorization(cloud, serviceDefinition);
done

2019-06-26 13:46 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +				logger.info(ex.getMessage());
done

2019-06-26 13:48 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/repository/InterCloudAuthorizationRepository.java
> +	Optional<IntraCloudAuthorization> findByCloudAndServiceDefinition(Cloud cloud, ServiceDefinition serviceDefinition);
done

2019-06-27 07:25 UTC, rbocsi reviewed
seems ok

2019-06-27 07:26 UTC, rbocsi approved these changes

2019-06-27 08:01 UTC, merged