rebased
eclipse-arrowhead/core-java-spring pull request #235
Opened 2020-06-18 09:40 UTC by punyal

Translator rebased

2020-06-24 10:35 UTC, rbocsi commented on translator/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_gw || true
uses the password of gateway mysql user (need new field in the templates file located in the core-common/src/deb/control folder)

2020-06-24 10:36 UTC, rbocsi commented on translator/src/deb/control/postinst
> +		db_get arrowhead-core-common/mysql_password_gw; system_passwd=$RET || true
uses the gateway mysql password

2020-06-24 10:38 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorApplicationInitListener.java
> +		return List.of(CoreSystemService.AUTH_CONTROL_SUBSCRIPTION_SERVICE);
I don't see any use of this URI in your code, so why even override this method here?

2020-06-24 10:39 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    public TranslatorHubAccess postTranslator(@RequestBody final TranslatorSetup setup, @RequestHeader("host") String host) {
Why don't you use a name that tells us what the method does? It's a create so it should return HTTP status 201 instead of 200 in case of success.

2020-06-24 10:40 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            return translatorService.createTranslationHub(setup, host.substring(0, host.indexOf(":")));
host.substring(0, host.indexOf(":")) can cause StringIndexOutOfBoundsException, because the port part is optional (if it uses the default port of the protocol) in the Host header. The error message will be very confusing for the caller.

2020-06-24 10:41 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            throw new ArrowheadException("Exception", HttpStatus.SC_BAD_REQUEST, ex.getLocalizedMessage());
ArrowheadException: you should put the error message into the msg parameter (using the word "Exception" is a tautology), the origin tells us which request cause this exception
This problem occurs in other methods as well.

2020-06-24 10:41 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        @ApiResponse(code = HttpStatus.SC_OK, message = CoreCommonConstants.SWAGGER_HTTP_200_MESSAGE),
missing API response (bad request)

2020-06-24 10:42 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    @GetMapping(PATH_TRANSLATOR_ALL)
missing produces

2020-06-24 10:44 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        return translatorService.getAllHubs(host.substring(0, host.indexOf(":")));
host.substring() problem see above
missing exception handling: web services should only throw ArrowheadException (or any of its derived classes) because there is a mechanism that convert ArrowheadExceptions to proper http error responses

2020-06-24 10:44 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        @ApiResponse(code = HttpStatus.SC_OK, message = CoreCommonConstants.SWAGGER_HTTP_200_MESSAGE),
missing API responses (bad request)

2020-06-24 10:45 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    @GetMapping(PATH_TRANSLATOR_BY_ID)
missing produces

2020-06-24 10:45 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            throw new ArrowheadException("Exception", HttpStatus.SC_BAD_REQUEST, ex.getLocalizedMessage());
ArrowheadException problem: see postTranslator

2020-06-24 10:46 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    @GetMapping(path = PATH_TRANSLATOR_PLUGIN_ENTITY_AND_SERVICE, produces = {MediaType.TEXT_PLAIN_VALUE, MediaType.APPLICATION_JSON_VALUE, "application/senml+json"})
"application/senml+json" should be a constant. Please do not use string literals in the code (except in error messages, log messages, swagger messages, etc.)

2020-06-24 10:47 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        return fiwareService.pluginEntityService(entityId, serviceName, request.getHeader(HttpHeaders.ACCEPT));
what if Accept header is missing? (then the underlying code will throw a NullPointerException)

2020-06-24 10:47 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        @ApiResponse(code = HttpStatus.SC_OK, message = CoreCommonConstants.SWAGGER_HTTP_200_MESSAGE),
missing API responses (not found, unsupported media type, maybe bad request?)

2020-06-24 10:48 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        return new FiwareUrlServices("/translator/v2/entities", "/translator/v2/types", null, null);
you should use constants instead of string literals

2020-06-24 10:49 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    public FiwareEntity[] fiwareListEntities(
what is the reason that you list all possible query params as optional, if you just use the map input parameter which contains all specified query params? I saw this in other methods too.

2020-06-24 10:50 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/security/TranslatorAccessControlFilter.java
> +    protected void checkClientAuthorized(final String clientCN, final String method, final String requestTarget, final String requestJSON, final Map<String, String[]> queryParams) {
TODO found here. If you have special logic to control access, you should implement here. If not, you should just delete checkClientAuthorized() method. There is no point to override a method and just call super().

2020-06-24 10:51 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +public class ArrowheadDriver {
ArrowheadDriver should be Spring managed component (because you create only one instance anyway)

2020-06-24 10:54 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +    public void serviceRegistryRegisterAllServices(FiwareEntity entity) {
You should consider using logger.debug() instead of logger.info() in most cases: because it much harder to find a specific problem in a large log file that contains thousands of lines about the correct behaviour of the system. Also, you don't have to use String.format: the logger have built-in functionality for that. For example: 
`  logger.debug("AuthorizationIntraClouds  with page: {} and item_per page: {} retrieved successfully", page, size);`
This issue occurs in other classes too.
						  
Every public method (not just here, but in other classes too) should check its input before use them. For example, the serviceRegistryRegisterAllServices() will throw NPE in its first line if the input param is null.
Also, the public method should check the inputs of any used private method before calling it (if necessary).

2020-06-24 10:54 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +                logger.warn("Exception: " + ex.getLocalizedMessage());
When catch an exception and logging it, it is wise to log its stacktrace too in debug level.

2020-06-24 10:57 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +                ResponseEntity response = httpService.sendRequest(registerUri, HttpMethod.POST, ServiceRegistryResponseDTO.class, request);
use ResponseEntity<?> instead of ResponseEntity (in unregister too)

2020-06-24 10:58 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +    public void serviceRegistryUnegisterAllServices(FiwareEntity entity) {
typo in the name

2020-06-24 10:59 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +        } catch (SocketException ex) {
you should use multi-catch block here instead of two simple ones. It is also wise to comment this catch block that is intentionally blank otherwise one may think that you forget to handle properly the exceptions (or you are just lazy).

2020-06-24 11:00 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +            // TODO: Enable it after security keys are fixed
unresolved TODO

2020-06-24 11:01 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +        return String.format("%s://%s:%d/translator/plugin/service/%s/%s",
should NOT return a full URL. Protocol, host and port comes from the system, the serviceUri contains the rest. So in your case, the format string should be: "/translator/plugin/service/%s/%s"

2020-06-24 11:01 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +        JsonNode json = new ObjectMapper().convertValue(entity, JsonNode.class);
why use JsonNode? You already have a FiwareEntity class which contains the serviceNames as keys in the map named other.

2020-06-24 11:02 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +    private ArrayList<String> getServicesNamesDefinitions(FiwareEntity entity) {
getServicesNamesDefinitions() is the same method as the previous one and never used, so just delete it

2020-06-24 11:02 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareDriver.java
> +import static org.springframework.http.HttpMethod.*;
please don't use wildcard imports

2020-06-24 11:03 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareDriver.java
> +public class FiwareDriver {
should be Spring managed component (because you create only one instance anyway)

2020-06-24 11:03 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareDriver.java
> +        Assert.state(fiwarePort == 0, "Port not valid");
port check is not enough (port can't be negative, or greater than 65535)

2020-06-24 11:04 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareDriver.java
> +        ResponseEntity response = httpService.sendRequest(getUriEntities(queryParams), POST, null, entity);
use ResponseEntity<?> instead of ResponseEntity (everywhere)

2020-06-24 11:04 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareDriver.java
> +    private UriComponents getUriTypes() {
never used, so it should be removed

2020-06-24 11:05 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareDriver.java
> +    private UriComponents getUriTypes(String path, Map<String, Object> queryParams) {
never used, so it should be removed

2020-06-24 11:05 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareDriver.java
> +    private UriComponents getUriRegistrations() {
never used, so it should be removed

2020-06-24 11:05 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareDriver.java
> +    private UriComponents getUriSubcriptions() {
never used, so it should be removed

2020-06-24 11:08 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareService.java
> +    private FiwareDriver fiwareDriver;
If ArrowheadDriver and FiwareDriver are both Spring managed components then you don't have to lazy initializing them, just autowire and use them

2020-06-24 11:09 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareService.java
> +            throw new ArrowheadException(String.format("No entity with id:%s", entityId), HttpStatus.NOT_FOUND.value());
you should use DataNotFoundException instead of ArrowheadException here

2020-06-24 11:09 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareService.java
> +            throw new ArrowheadException(String.format("No entity with id:%s and service:%s", entityId, serviceName), HttpStatus.NOT_FOUND.value());
you should use DataNotFoundException instead of ArrowheadException here

2020-06-24 11:09 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareService.java
> +        switch (contentType) {
if contentType is null (and it can be if the Accept header is not present), then the switch will throw NPE

2020-06-24 11:10 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareService.java
> +            case "application/senml+json":
should be a constant (which can be both used here and in the controller class)

2020-06-24 11:11 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareService.java
> +    private ArrayNode jsonOject2SenMl(String serviceName, Object o) {
Please never ever used o as a variable name in Java, because it is easy to mistake to 0 is certain fonts (the same with l and I and 1). In most cases, it is a wrong idea to use one letter long variable names (Please, note that senML is an exception from this rule, because that is a well-documented standard)

2020-06-24 11:12 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareService.java
> +        ObjectMapper mapper = new ObjectMapper();
jsonOject2SenMl() and in other methods: ObjectMapper can be reused, so you can create one as a member and use it in the method and every method where you want to parse JSONs.

2020-06-24 11:12 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareService.java
> +        ((ObjectNode) sensorValue).put("n", serviceName);
constants instead of string literals

2020-06-24 11:13 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/FiwareService.java
> +    @Scheduled(fixedRate = 1000, initialDelay = 10000)
Please note that some people have problem with scheduling private methods with Spring in the past (maybe this problem is addressed now). 

Also, you should create properties in the application.properties file for the fixedRate and initialDelay parameters instead of using hardcoded values

2020-06-24 11:14 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/common/FiwareEntity.java
> +    private String id;
I think you need setters for id and type, otherwise Jackson will put id/type value to the map instead of the dedicated fields when parsing a JSON

2020-06-24 11:15 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/common/FiwareUrlServices.java
> +    private final String entities_url;
Please don't use C-style naming in Java. Use camelCase instead (in the field names and input parameter names).

2020-06-24 11:16 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorHub.java
> +    private final EndPoint pSpoke_Consumer;
naming convention

2020-06-24 11:16 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorHub.java
> +    private final EndPoint cSpoke_Provider;
never used

2020-06-24 11:17 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorHub.java
> +    public boolean noactivity = false;
you should not use public members

2020-06-24 11:18 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorHub.java
> +        switch(pSpoke_Consumer.getProtocol()) {
input check. Any switch can throw NPE

2020-06-24 11:18 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorHub.java
> +                throw new Exception("Unknown protocol "+ pSpoke_Consumer.getProtocol());
you should use some kind of ArrowheadException instead of general Exception (everywhere)

2020-06-24 11:19 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorService.java
> +            logger.warn("Not valid ip address, we need absolut address, not relative (as 127.0.0.1 or localhost)");
typo: absolut => absolute (absolut is a vodka brand :) )

2020-06-24 11:20 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/common/TranslatorDef.java
> +        coap     (0),
naming convention: enum values should be upper case

2020-06-24 11:21 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/common/TranslatorSetup.java
> +public class TranslatorSetup {
currently, Jackson is unable to create such object from a JSON, because there is no creator is defined

2020-06-24 11:24 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/common/TranslatorSetup.java
> +    public TranslatorSetup(String producerName, String producerAddress, String consumerName, String consumerAddress) {
This constuctor signature can solve the issue:
    ```
@JsonCreator
    public TranslatorSetup(@JsonProperty("producerName") String producerName, @JsonProperty("producerAddress") String producerAddress, @JsonProperty("consumerName") String consumerName, @JsonProperty("consumerAddress") String consumerAddress)
```

2020-06-24 11:25 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/BaseContext.java
> +    public void setMethod(Method method) {
make sure that method can't be null

2020-06-24 11:26 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/CoapConsumerSpoke.java
> +        new Thread(new Worker(context), "name").start();
the name of the thread should be something specific, for example something derived from the serviceAddress. Debug the code when a bunch of thread named "name"

2020-06-24 11:27 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/CoapConsumerSpoke.java
> +    public void setNextSpoke(Object nextSpoke) {
make sure parameter is not null

2020-06-24 11:27 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/CoapConsumerSpoke.java
> +            System.out.println(lStartTime + ": CoAP sending to: " + client.getURI());
remove system.out.println-s (or replace with logger.debug messages) (everywhere, not just here)

2020-06-24 11:27 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/CoapConsumerSpoke.java
> +                //TODO: need to signal an error to the next spoke
unresolved TODO here

2020-06-24 11:28 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/CoapProducerSpoke.java
> +        // TODO Get full address of the spoke providers (scheme, url, port, path)
unresolved TODO here

2020-06-24 11:29 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpConsumerSpoke.java
> +            } catch (ProtocolException e1) {
generated catch blocks here without any exception handling

2020-06-24 11:30 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpConsumerSpoke.java
> +                    conn.setRequestProperty("content-type", "application/xml");
BaseContext contains a contentType, so why use hard-coded application/xml here?

2020-06-24 11:30 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +    private static final Charset UTF_8 = Charset.forName("UTF-8");
you should use StandardCharsets.UTF_8 instead Charset.forName()

2020-06-24 11:31 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +        params.setIntParameter(CoreConnectionPNames.SO_TIMEOUT, SOCKET_TIMEOUT).setIntParameter(CoreConnectionPNames.SOCKET_BUFFER_SIZE, SOCKET_BUFFER_SIZE).setBooleanParameter(CoreConnectionPNames.T
essentially, every type and method deprecated here and later there are other deprecated things

2020-06-24 11:32 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +                    } catch (IOException e) {
empty exception catch blocks

2020-06-24 11:33 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +            e.printStackTrace();
don't use printStacktrace() because that writes to the standard error, not to the log file

2020-06-24 11:34 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +        throw new UnsupportedOperationException("Not supported yet.");
not implemented

2020-06-24 11:34 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
not implemented

2020-06-24 11:35 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +            // TODO Auto-generated catch block
generated catch block

2020-06-24 11:36 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +            //TODO: prepare http request for next spoke
unresolved TODO

2020-06-24 11:36 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +                        // translate the payload to the utf-8 charset
commented code about charset change

2020-06-24 11:37 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +            nextSpoke.in(context);
nextSpoke is null when the instance is created, setNextSpoke throws UnsupportedOperationException, so when you call nextSpoke.in() at the end of handle() is a  guaranteed NPE

2020-06-24 11:38 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/ResponseAllowCORS.java
> +    private static final HttpDateGenerator DATE_GENERATOR = new HttpDateGenerator();
unused HttpDateGenerator

2020-06-24 11:38 UTC, rbocsi commented on translator/src/main/resources/application.properties
> +
missing domain.name property so the translator will registers itself to SR with 0.0.0.0 as server address

2020-06-24 11:40 UTC, rbocsi requested changes
See inline comments.

Also:

- no documentation, 
- essentially, no unit tests,
- no translator in CoreSystem enum

2020-07-01 11:14 UTC, punyal commented on translator/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_gw || true
/
```suggestion

```

2020-07-01 11:19 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorApplicationInitListener.java
> +		return List.of(CoreSystemService.AUTH_CONTROL_SUBSCRIPTION_SERVICE);
I remove it, it was from the previous copy.

2020-07-01 11:26 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    public TranslatorHubAccess postTranslator(@RequestBody final TranslatorSetup setup, @RequestHeader("host") String host) {
what a method does should be on the description of the method before the method, but it is a practice that no one is using on this repository. This code has been ported from an old commit, I will keep the same functionality as it had before.
Conclusion: no changes from my side.

2020-07-01 11:32 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            return translatorService.createTranslationHub(setup, host.substring(0, host.indexOf(":")));
This code has been ported from an old commit, I will keep the same functionality as it had before.
The port part is mandatory, so it has to be there.

Conclusion: no changes from my side.

2020-07-01 11:38 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            throw new ArrowheadException("Exception", HttpStatus.SC_BAD_REQUEST, ex.getLocalizedMessage());
I'm caching every single possible Exception, that's the reason I'm using "Exception", as generic (which is not a tautology). The origin of the exception is on the third parameter  ex.getLocalizedMessage(). 

public ArrowheadException(final String msg, final int errorCode, final String origin);


Conclusion: no changes from my side.

2020-07-01 11:42 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        @ApiResponse(code = HttpStatus.SC_OK, message = CoreCommonConstants.SWAGGER_HTTP_200_MESSAGE),
done

2020-07-01 11:44 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    @GetMapping(PATH_TRANSLATOR_ALL)
done

2020-07-01 11:44 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        return translatorService.getAllHubs(host.substring(0, host.indexOf(":")));
same answer as before.
Conclusion: no changes from my side.

2020-07-01 11:45 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        @ApiResponse(code = HttpStatus.SC_OK, message = CoreCommonConstants.SWAGGER_HTTP_200_MESSAGE),
done

2020-07-01 11:45 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    @GetMapping(PATH_TRANSLATOR_BY_ID)
done

2020-07-01 11:45 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            return translatorService.createTranslationHub(setup, host.substring(0, host.indexOf(":")));
I don't care where the code come from. In this repository we try to maintain a certain level of code quality (and sometimes we failed, but we try anyway). The port is optional, read the RFC. So I advise you to reconsider otherwise we just don't merge your system.

2020-07-01 11:46 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            throw new ArrowheadException("Exception", HttpStatus.SC_BAD_REQUEST, ex.getLocalizedMessage());
Same answer as before.

Conclusion: no changes from my side.

2020-07-01 11:49 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    @GetMapping(path = PATH_TRANSLATOR_PLUGIN_ENTITY_AND_SERVICE, produces = {MediaType.TEXT_PLAIN_VALUE, MediaType.APPLICATION_JSON_VALUE, "application/senml+json"})
I moved it to the top as a static, unfortunately, there is not MediaType for senml at org.springframework.http.MediaType

2020-07-01 11:51 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        return fiwareService.pluginEntityService(entityId, serviceName, request.getHeader(HttpHeaders.ACCEPT));
Yes, and it returns an internal server error (500).

2020-07-01 11:53 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        @ApiResponse(code = HttpStatus.SC_OK, message = CoreCommonConstants.SWAGGER_HTTP_200_MESSAGE),
No change needed here.

2020-07-01 11:56 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        return new FiwareUrlServices("/translator/v2/entities", "/translator/v2/types", null, null);
agree, done.

2020-07-01 11:57 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    public FiwareEntity[] fiwareListEntities(
Because some params are optional, some mandatory, and some of them are unknown.

No change needed

2020-07-01 11:58 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/security/TranslatorAccessControlFilter.java
> +    protected void checkClientAuthorized(final String clientCN, final String method, final String requestTarget, final String requestJSON, final Map<String, String[]> queryParams) {
I removed the TODO, I was copied from Gateway repo.

2020-07-01 11:58 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    public TranslatorHubAccess postTranslator(@RequestBody final TranslatorSetup setup, @RequestHeader("host") String host) {
ok

2020-07-01 11:59 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +public class ArrowheadDriver {
No, it has to be as it is.

2020-07-01 12:00 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +    public void serviceRegistryRegisterAllServices(FiwareEntity entity) {
I understand your point of view, but this server will not create huge log files.

2020-07-01 12:02 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +                logger.warn("Exception: " + ex.getLocalizedMessage());
Yes, but some of them I want to log them as a warning, not only on the debug level.

2020-07-01 12:02 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            throw new ArrowheadException("Exception", HttpStatus.SC_BAD_REQUEST, ex.getLocalizedMessage());
When you see the constructor of an exception in which the first parameter named msg (which is the abbreviation of message) one would think that you pass a message when you call it, like ex.getMessage() or ex.getLocalizedMessage(). But no, put there the meaningless "Exception" string, it is much more helpful to the caller. 

Probably,  I will review your code again, when you finish your changes and I will not approve the merge if you don't fix  things.

2020-07-01 12:07 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +                ResponseEntity response = httpService.sendRequest(registerUri, HttpMethod.POST, ServiceRegistryResponseDTO.class, request);
They are actually the same, the compiler would replace it with a generic type, if you see here in the documentation ResponseEntity it's actually class ResponseEntity<T>

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/ResponseEntity.html

Conclusion: no changes from my side

2020-07-01 12:08 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +    public void serviceRegistryUnegisterAllServices(FiwareEntity entity) {
done

2020-07-01 12:11 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        return fiwareService.pluginEntityService(entityId, serviceName, request.getHeader(HttpHeaders.ACCEPT));
Returning an internal server error is the problem. It tells the caller there is some problem with the server, but that's not true. The problem is caused by the client by passing a request without Accept header. Every client error should have 4xx instead of 5xx status code.

2020-07-01 12:21 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        @ApiResponse(code = HttpStatus.SC_OK, message = CoreCommonConstants.SWAGGER_HTTP_200_MESSAGE),
why do you think no change  needed? The service method from FiwareService throws various ArrowheadException with HTTP status codes NOT_FOUND, UNSUPPORTED_MEDIA_TYPE. The ControllerAdvice will convert these exceptions to HTTP responses using the HTTP status codes. So yeah, you need to add some @ApiResponses. You also will use BAD_REQUEST too as soon as you fix the problems with Accept header.

2020-07-01 12:21 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +    public FiwareEntity[] fiwareListEntities(
ok

2020-07-01 12:22 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +public class ArrowheadDriver {
why?

2020-07-01 12:24 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +    public void serviceRegistryRegisterAllServices(FiwareEntity entity) {
It will. It's just the matter of uptime. Also, you forget to address the input checks problem.

2020-07-01 12:28 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +                logger.warn("Exception: " + ex.getLocalizedMessage());
I think we have a misunderstanding here. I don't want to delete your line that put a warning into the log file.  I suggest you should write an other line ( logger.debug("Exception:", ex); ) that provides us more information if needed. When some weird error happens, it can help.

2020-07-01 12:35 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +                ResponseEntity response = httpService.sendRequest(registerUri, HttpMethod.POST, ServiceRegistryResponseDTO.class, request);
With this logic why you even use generic types at all, like Map<Integer, TranslatorHub>? You can use raw types (Map), the compiler will erase all the type parameters anyways.

The thing is ResponseEntity causes a warning in every decent IDE, while ResponseEntity<?> don't.

2020-07-01 12:41 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            return translatorService.createTranslationHub(setup, host.substring(0, host.indexOf(":")));
There is nothing to do with the RFC. The client can type it or not, but the RequestHeader "host" will contain it anyway. 
And this code is not reading the port, it is extracting the IP address.

2020-07-01 12:43 UTC, punyal commented on translator/src/deb/control/postinst
> +		db_get arrowhead-core-common/mysql_password_gw; system_passwd=$RET || true
removed, it was a copy error

2020-07-01 12:49 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            return translatorService.createTranslationHub(setup, host.substring(0, host.indexOf(":")));
> Host = "Host" ":" host [ ":" port ] ; Section 3.2.2
> 
>    A "host" without any trailing port information implies the default
>    port for the service requested (e.g., "80" for an HTTP URL). For
>    example, a request on the origin server for
>    <http://www.w3.org/pub/WWW/> would properly include:
> 
>        GET /pub/WWW/ HTTP/1.1
>        Host: www.w3.org
There is no : in the header value if the header value does not contain the port.

2020-07-01 14:21 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +        } catch (SocketException ex) {
moved to multi-catch

2020-07-01 14:22 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +        } catch (SocketException ex) {
moved to multi-catch

2020-07-01 14:28 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +                ResponseEntity response = httpService.sendRequest(registerUri, HttpMethod.POST, ServiceRegistryResponseDTO.class, request);
The warning is just to remember you that you are not providing it. I don't care about the content of ResponseEntity, and that's the reason why in this case it is right.

2020-07-01 14:32 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +public class ArrowheadDriver {
Because it is not needed.

2020-07-01 14:36 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +        return String.format("%s://%s:%d/translator/plugin/service/%s/%s",
It is a URI so I need to provide it.
And also because the System is not able to provide the right host if the system has more than one interface.

2020-07-01 14:39 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorHub.java
> +    private final EndPoint cSpoke_Provider;
done

2020-07-01 14:43 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorHub.java
> +    public boolean noactivity = false;
that was not used, removed

2020-07-01 14:45 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorHub.java
> +                throw new Exception("Unknown protocol "+ pSpoke_Consumer.getProtocol());
Why?

2020-07-01 14:45 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorService.java
> +            logger.warn("Not valid ip address, we need absolut address, not relative (as 127.0.0.1 or localhost)");
fixed

2020-07-01 14:48 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/common/TranslatorDef.java
> +        coap     (0),
I know, but in this case, it's needed.

2020-07-01 15:25 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/common/TranslatorSetup.java
> +public class TranslatorSetup {
done

2020-07-01 15:25 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/common/TranslatorSetup.java
> +    public TranslatorSetup(String producerName, String producerAddress, String consumerName, String consumerAddress) {
It was fixed from prev comment. Thanks

2020-07-01 15:31 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/BaseContext.java
> +    public void setMethod(Method method) {
it can't be null, there is a throw exception before.

2020-07-01 15:32 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/CoapConsumerSpoke.java
> +        new Thread(new Worker(context), "name").start();
done

2020-07-01 15:39 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/CoapConsumerSpoke.java
> +    public void setNextSpoke(Object nextSpoke) {
done

2020-07-01 15:40 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/CoapConsumerSpoke.java
> +            System.out.println(lStartTime + ": CoAP sending to: " + client.getURI());
done

2020-07-01 15:46 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/CoapConsumerSpoke.java
> +                //TODO: need to signal an error to the next spoke
done

2020-07-01 15:46 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/CoapProducerSpoke.java
> +        // TODO Get full address of the spoke providers (scheme, url, port, path)
done

2020-07-01 15:46 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpConsumerSpoke.java
> +            } catch (ProtocolException e1) {
done

2020-07-01 15:50 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpConsumerSpoke.java
> +                    conn.setRequestProperty("content-type", "application/xml");
Because the code to support multiple different content-types has not been done. It is hardcoded to JSON (XML was wrong). fixed

2020-07-01 15:53 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +    private static final Charset UTF_8 = Charset.forName("UTF-8");
I changed but apparently there is no difference nowadays.

2020-07-01 16:11 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +                    } catch (IOException e) {
fixed

2020-07-01 16:13 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +            e.printStackTrace();
done

2020-07-01 16:14 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +        throw new UnsupportedOperationException("Not supported yet.");
deleted

2020-07-01 16:14 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
deleted

2020-07-01 16:15 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +            // TODO Auto-generated catch block
done

2020-07-01 16:15 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +            //TODO: prepare http request for next spoke
done

2020-07-01 16:16 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/HttpProducerSpoke.java
> +                        // translate the payload to the utf-8 charset
changed

2020-07-01 16:22 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/ResponseAllowCORS.java
> +    private static final HttpDateGenerator DATE_GENERATOR = new HttpDateGenerator();
deleted

2020-07-01 16:24 UTC, punyal commented on translator/src/main/resources/application.properties
> +
fixed

2020-07-02 08:36 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +public class ArrowheadDriver {
Every singleton should be a Spring managed component in a Spring project. You didn't provide any reason to keep this class non-managed besides the fact you don't want to change anything. So please, convert it to Spring managed component.

2020-07-02 08:45 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +                ResponseEntity response = httpService.sendRequest(registerUri, HttpMethod.POST, ServiceRegistryResponseDTO.class, request);
Every professional project  should be warning free. The programmer's responsibility to try eliminate every warning in his code if possible. Alternatively, one can marked the appropriate code fragment with @SuppressWarnings if elimination is not possible and the code fragment can't cause any problems.

Do you realize that you fighting against adding 3 characters (per usage)?

2020-07-02 08:56 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +        return String.format("%s://%s:%d/translator/plugin/service/%s/%s",
You use this method when you register services to the Service Registry. When you register a service into the Service Registry you have to specify a provider system too (and you've done that by using the getSystemRequestDTO() method with the same ip and port), so there is no need to put the SAME ip and port into the service URI.

2020-07-02 09:11 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorHub.java
> +                throw new Exception("Unknown protocol "+ pSpoke_Consumer.getProtocol());
Because almost every Arrowhead core system is a collection of webservices. Essentially every uncatched Exception returns to the client as a HTTP error response. We have a mechanism that creates a proper HTTP error response from any ArrowheadException. In your case the client receives an HTTP status 500, but status should be 4xx, because the problem is a client error (4xx), not a server error (5xx).

More generically, Exception is meant to be a base class of exception. In every situation, you should try to use specialized exception classes.

2020-07-02 09:12 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/common/TranslatorDef.java
> +        coap     (0),
ok

2020-07-02 09:15 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/BaseContext.java
> +    public void setMethod(Method method) {
where?

2020-07-02 09:18 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            return translatorService.createTranslationHub(setup, host.substring(0, host.indexOf(":")));
This function is to get the host, no the port. Anyway, only if it is a HTTP request over 80 doesn't contain the port information, which will not happen on Arrowhead. I changed it to a non-NPE situation.

2020-07-02 09:19 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            throw new ArrowheadException("Exception", HttpStatus.SC_BAD_REQUEST, ex.getLocalizedMessage());
ok

2020-07-02 09:23 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +        return fiwareService.pluginEntityService(entityId, serviceName, request.getHeader(HttpHeaders.ACCEPT));
ok

2020-07-02 09:26 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +public class ArrowheadDriver {
I added it, but could you point me to the documentation of Spring where that is explained?

2020-07-02 09:32 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +                ResponseEntity response = httpService.sendRequest(registerUri, HttpMethod.POST, ServiceRegistryResponseDTO.class, request);
I'm not fighting against anyone. As you said, the warning that you have is from your IDE, to remember you that there is no <?>, in this case, is not needed because I'm not using the content.

Do you realize that you fighting against non adding 3 characters (per usage)?

2020-07-02 09:36 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/fiware/ArrowheadDriver.java
> +        return String.format("%s://%s:%d/translator/plugin/service/%s/%s",
A Uniform Resource Identifier (URI) is a string of characters that **unambiguously** identifies a particular resource.
I'll not provide only the path.

2020-07-02 09:37 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorHub.java
> +        switch(pSpoke_Consumer.getProtocol()) {
done

2020-07-02 09:41 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/TranslatorHub.java
> +                throw new Exception("Unknown protocol "+ pSpoke_Consumer.getProtocol());
ok, thanks. I updated them.

2020-07-02 10:35 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/BaseContext.java
> +    public void setMethod(Method method) {
that method is used in CoapProducerSpoke.java line134, and HttpProducerSpoke.java line 222. In both cases method will not be null

2020-07-02 10:59 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/services/translator/spokes/BaseContext.java
> +    public void setMethod(Method method) {
ok

2020-07-03 14:09 UTC, rbocsi commented
I make some tries with translator and a new issue occured:

- you should add translator user creation to scripts/create_empty_arrowhead_db.sql
- This is not new, but without translator in CoreSystem enum the webserver does not even start, which means to me that  you never try  your code before making a pull request.

2020-07-03 14:18 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            return translatorService.createTranslationHub(setup, host.substring(0, host.indexOf(":")));
I'll try this one with curl because of the debate. 

- In the first case, I 'forgot' to add the port to the Host header:

`curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" -H "Host: localhost" -d {} http://localhost8462/translator/`

Result:
`{"errorMessage":"Exception","errorCode":400,"exceptionType":"ARROWHEAD","origin":"begin 0, end -1, length 9"}`
Please convince me that this error message helps you to figure out what the problem is.

- In the second case, I started the translator on the port 80 (because why not?) and I don't add Host header at all. In this case curl automatically adds a Host header WITHOUT a port:

`curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d {} http://localhost8462/translator/`

Result:
`{"errorMessage":"Exception","errorCode":400,"exceptionType":"ARROWHEAD","origin":"begin 0, end -1, length 9"}`

Debug: 
![kép](https://user-images.githubusercontent.com/2082221/86477431-b6c6d380-bd48-11ea-8943-6156b488e7fb.png)

I hope you can see now what the problem is with your solution.

2020-07-03 17:33 UTC, punyal commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            return translatorService.createTranslationHub(setup, host.substring(0, host.indexOf(":")));
Which debate? Please, read again my previous comment.
As I said, this situation only happens if you have the server running on port 80 and your URL starts with "http". And as I also said in the previous comment, I changed the code to prevent this to happen.
Regarding your test with curl, you are getting the same NPE on both. There is no difference between cases 1 and 2. The header "host" is added automatically by curl with the information from the URL, in both cases, the problem is that there is no port. You can try even with http://localhost:80 in this case you will also have the same issue because curl will remove the port number.

2020-07-06 07:55 UTC, rbocsi commented on translator/src/main/java/eu/arrowhead/core/translator/TranslatorController.java
> +            return translatorService.createTranslationHub(setup, host.substring(0, host.indexOf(":")));
Oh, I read your comment just fine. You still think that the problem is with the missing port, but no: the problem is with the missing : (colon), because you try to find a colon in the Host header value, but it is not there if the port is not there. 
You should take your own advice and reread my previous comment, because in my first example the server runs on the port 8462 and I still manage to cause an error: all I had to do to 'forget' to add the port in the Host header value. An no, curl does not add automatically a Host header if you already specified one.

Another problem you still think that this causes a NullPointerException, but no: it causes a StringIndexOutOfBoundsException. 

The main problem is the you does not understand (or doesn't want to) what exception handling means in a web-service. Exception handling is not just preventing the application to crash, or logging, but if the user (the caller of the web service) make a mistake in his request, the web service responds with an error message that tells the user that the request is wrong (4xx status code) and what is the exact problem so the caller should fix it. 
In this case (when port is not present in the Host header value), the error message is this:
`{"errorMessage":"Exception","errorCode":400,"exceptionType":"ARROWHEAD","origin":"begin 0, end -1, length 9"}`
What is wrong with this one?

1.  The error message should be in the errorMessage field. The string "Exception" does not contain any information.
2.  The origin should contains something like that: /translator/
3.  Your error message which appears in the origin field is **"begin 0, end -1, length 9"**. This doesn't tell the caller how to fix the problem in his request (providing a Host header with port number). Without the source code of the translator no one has the chance to fix the request even if the caller recognizes a StringOutOfBoundsException.
4. If a NullPointerException would happen in your code, the error message would be this:
`{"errorMessage":"Exception","errorCode":400,"exceptionType":"ARROWHEAD","origin":"null"}` How helpful, isn't it?

So how to fix it?
1. First check if the host parameter is null or empty string. Just because curl adds Host header automatically if not provided, that doesn't mean every HTTP client does the same. If host parameter is null or empty you can throw a BadPayloadException with an error message that tells the caller: Host header is mandatory.
2. Next, use host.indexOf to find the colon. If you find it, then use the substring to cut the address. If you don't find a colon (return value is -1), then you should use the whole header value as address.
3. Test your code. (To do that first you have to fix the missing enum value (TRANSLATOR) in the CoreSystem enum, because otherwise the webserver fails to start).

2020-09-28 15:29 UTC, punyal reviewed
Done

2020-09-29 12:53 UTC, rbocsi requested changes
Translator does not start. Svetlin will inform you about the details.

2020-11-25 08:55 UTC, rbocsi approved these changes

2020-11-25 09:05 UTC, tsvetlin commented
Dear Pablo,
The Translator now is a release candidate. 
Keep in mind there are some TODOs left to be done, when it will become a released core system.
- Remove unused variables
- Make ArrowheadDriver and FiWare driver a Spring managed component
- Remove deprecated methods
- Write Unit tests

Thank you for your contribution!

2020-11-25 09:05 UTC, merged