Datamanager
eclipse-arrowhead/core-java-spring pull request #239
Opened 2020-06-25 08:18 UTC by jenseliasson

To merge with the development branch

2020-06-25 08:21 UTC, tsvetlin commented
Hello!

I've changed the base branch to development. We will begin the review shortly.

2020-06-26 12:21 UTC, rbocsi commented on README.md
> +The DataManager has the following use cases:
These links give me 404. These files are missing from the datamanager branch.

2020-06-26 12:23 UTC, rbocsi commented on README.md
> +Returns a list of all service enpoints that have data stored in the database.
typo enpoints

2020-06-26 12:24 UTC, rbocsi commented on README.md
> +Returns sensor data from a service endpoints from the database.
typo endpoints => endpoint

2020-06-26 12:25 UTC, rbocsi commented on README.md
> +	"vb"; false,
typo ; instead of :

2020-06-26 12:25 UTC, rbocsi commented on README.md
> +Stores sensor data in a service endpoints in the database.
typo endpoints => endpoint

2020-06-26 12:26 UTC, rbocsi commented on README.md
> +
missing proxy related descriptions

2020-06-26 12:28 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/CommonConstants.java
> +	public static final String SWAGGER_HTTP_400_MESSAGE = "Bad request";
duplication, see CoreCommonConstants

2020-06-26 12:28 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/CommonConstants.java
> +	public static final String SWAGGER_HTTP_409_MESSAGE = "Request caused a conflict";
duplication, see CoreCommonConstants

2020-06-26 12:35 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerApplicationInitListener.java
> +	private ApplicationContext applicationContext;
applicationContext member not used

2020-06-26 12:35 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerApplicationInitListener.java
> +	protected List<CoreSystemService> getRequiredCoreSystemServiceUris() {
why even override any of these methods? getRequiredCoreSystemServiceUris() has the same implementation that is in the base class, the others just logs a line and do nothing else

2020-06-26 12:36 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	@Autowired
all member's visibility should be private

2020-06-26 12:37 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	@ApiOperation(value = "Interface to get all services that s specific system has active in the Historian service", response = DataManagerServicesResponseDTO.class, tags = { CoreCommonConstants.SWAGGE
typo in description: see s in "Interface to get all services that s specific system has active in the Historian service")

2020-06-26 12:38 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	@ResponseBody public DataManagerServicesResponseDTO historianSystemPut(
what's real difference this method and the previous. Both return the result of historianService.getServicesFromSystem(systemName);. The only difference I see that the PUT version need a "list" op in its request body, but since there is no other supported op...

2020-06-26 12:38 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +		int statusCode = 0;
unused local variable: statusCode

2020-06-26 12:39 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +			String par = (String)it.next();
since it is a Iterator<String>, you don't have to cast it.next() to String

2020-06-26 12:39 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +				count = Integer.parseInt(params.getFirst(par));
in this line you forget to handle NumberFormatException, there are two Long.parseLong() usage with the same issue (and there is an other parseInt where you handle it properly)

2020-06-26 12:40 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	@ResponseBody public DataManagerSystemsResponseDTO proxyGet() {
proxyGet() and proxyPut() is the same (like historianSystemGet() and historianSystemPut())

2020-06-26 12:40 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +		@ApiResponse(code = HttpStatus.SC_OK, message = CoreCommonConstants.SWAGGER_HTTP_200_MESSAGE),
missing API response (bad request)

2020-06-26 12:41 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +			if (res == true) {
Please don't throw an exception when everything is working as intended, because that is the exact opposite of an exception. Maybe you should return an empty DataManagerServicesResponseDTO here, or changing the return value to ResponseEntity<?> and use ResponseEntity<DataManagerServicesResponseDTO> in case of list op and ResponseEntity.status(org.springframework.http.HttpStatus.OK).build() in case of delete

Also, i don't think if the delete op fails, then it is an illegal operation (it is a legal operation, just something is wrong, maybe didn't find the service). I think you should change the error message in the false case.

2020-06-26 12:42 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +		@ApiResponse(code = HttpStatus.SC_OK, message = CoreCommonConstants.SWAGGER_HTTP_200_MESSAGE),
missing API response (not found)

2020-06-26 12:42 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +				throw new BadPayloadException(NOT_FOUND_ERROR_MESSAGE, HttpStatus.SC_NOT_FOUND, "/proxy/"+systemName+"/"+serviceName);
there is a DataNotFoundException for cases like this

2020-06-26 12:43 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +		@ApiResponse(code = HttpStatus.SC_BAD_REQUEST, message = CoreCommonConstants.SWAGGER_HTTP_400_MESSAGE),
missing api response (created)

2020-06-26 12:44 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +					throw new ResponseStatusException(org.springframework.http.HttpStatus.CREATED);
exception usage when everything works fine
use instead ResponseEntity<?> return value  like this: 
`return ResponseEntity.status(org.springframework.http.HttpStatus.CREATED).build();`
 with the appropriate status codes

2020-06-26 12:45 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +                Assert.notNull(systemName, "systemName is null.");
should throw BadPayloadException instead of IllegalArgumentException

2020-06-26 12:46 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	  Iterator entry = sml.iterator();
Iterator should be Iterator<SenML> which eliminates the need of casting

2020-06-26 12:46 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	  Assert.isTrue(!(bnc != 1 || btc != 1 || buc > 1), "invalid bn/bt/bu");
should throw BadPayloadException instead of IllegalArgumentException

2020-06-26 12:47 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	  System.err.println("bt: "+ element.getBt());
remove  System.err.println("bt: "+ element.getBt()); and use logging instead

2020-06-26 12:47 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/database/service/DataManagerDBService.java
> +public class DataManagerDBService {
still no transaction handling

2020-06-26 12:47 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/database/service/DataManagerDBService.java
> +	private Connection connection = null;
unused variable: connection

2020-06-26 12:48 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/database/service/DataManagerDBService.java
> +	  } catch(SQLException se){
why catch SQLException in a different catch block when you do the same than in the general Exception catch block.
Also, please log the exceptions (everywhere). It helps finding and fixing the issues

2020-06-26 12:49 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/database/service/DataManagerDBService.java
> +		  if (m.getT() < 268435456) { //if relative ts, update it
268435456: you shouldn't use magic values in the code, use constants instead with a meaningful name

2020-06-26 12:49 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/database/service/DataManagerDBService.java
> +	    String signalsList = "";
unused local variables: signalsList, bt, bu

2020-06-26 12:50 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/security/DatamanagerAccessControlFilter.java
> +        sysNameStopPosition = requestTarget.indexOf("/", sysNameStartPosition + 0 + ("/datamanager"+CommonConstants.OP_DATAMANAGER_HISTORIAN+"/").length());
sysNameStartPosition + 0 is equals to sysNameStartPosition
"/datamanager"+CommonConstants.OP_DATAMANAGER_HISTORIAN+"/": you should create a constant from this one. You use this abomination three times

2020-06-26 12:51 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/security/DatamanagerAccessControlFilter.java
> +        sysNameStopPosition = requestTarget.indexOf("/", sysNameStartPosition + 0 + ("/datamanager"+CommonConstants.OP_DATAMANAGER_PROXY+"/").length());
same in case of proxy

2020-06-26 12:51 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/DataManagerDriver.java
> +public class DataManagerDriver {
empty class, you should delete it

2020-06-26 12:52 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/DataManagerService.java
> +public class DataManagerService {
empty class, you should delete it

2020-06-26 12:52 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +  private DataManagerDriver dataManagerDriver;
unused variable

2020-06-26 12:53 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +    if (systemName.equals("")) {
systemName.equals("") is not enough, because " " string not equals to "" but also not valid. You should use Utilities.isEmpty() for null and empty check everywhere

2020-06-26 12:53 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +    if (systemName == null || serviceName == null) {
what if systemName or serviceName is empty string?

2020-06-26 12:54 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +  public boolean addServiceForSystem(String systemName, String serviceName, String serviceType){
missing input checks

2020-06-26 12:54 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +    if (systemName == null || serviceName == null) {
missing empty string checks, I'd also check if there is any element in the msg vector

2020-06-26 12:55 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +    if (systemName == null || serviceName == null) {
missing empty string checks

2020-06-26 12:55 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +    if (systemName == null || serviceName == null) {
missing empty string checks

2020-06-26 12:55 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/ProxyElement.java
> +public class ProxyElement {
you should not use public members unless they are all finals and msg is unmodifiable list/vector

2020-06-26 12:56 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/ProxyService.java
> +public class ProxyService {
you can spare some linear searching if checks parameters whether they are empty string or not

2020-06-26 12:59 UTC, rbocsi commented on scripts/datamanager_privileges.sql
> +#GRANT ALL PRIVILEGES ON `arrowhead`.`dmhist_services` TO 'datamanager'@'%';
if the db is not on the same machine than the datamanager, you'll need these privileges too. Why are they commented out?

2020-06-26 13:02 UTC, rbocsi requested changes
See inline comments

Also:

- Please remove unused imports, variables, members (there is a lot of noise in the source files)
- You really should use constants instead of string literals (except in log messages, exception messages, etc). For example, you use the "/historian" string in multiple times in the controller class despite the fact that you have a constant too (and in some cases you use that)
- You should not use so much logger.info() use logger.debug() instead
- Still no unit tests

2020-06-26 14:30 UTC, tsvetlin commented
Please add this header to all of your source files:

`/********************************************************************************
 * Copyright (c) 2020 {YOUR_NAME or ORGANIZATION}
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0 
 *
 * Contributors: 
 *   {YOUR_NAME or ORGANIZATION} - implementation
 *   Arrowhead Consortia - conceptualization 
 ********************************************************************************/`

2020-06-26 14:33 UTC, tsvetlin requested changes
Please add this header to all of your source files:

```
/********************************************************************************
 * Copyright (c) 2020 {YOUR_NAME or ORGANIZATION}
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0 
 *
 * Contributors: 
 *   {YOUR_NAME or ORGANIZATION} - implementation
 *   Arrowhead Consortia - conceptualization 
 ********************************************************************************/
```

2020-06-29 18:20 UTC, jenseliasson commented on README.md
> +Returns a list of all service enpoints that have data stored in the database.
done

2020-06-29 18:21 UTC, jenseliasson commented on README.md
> +Returns sensor data from a service endpoints from the database.
done

2020-06-29 18:22 UTC, jenseliasson commented on README.md
> +	"vb"; false,
done

2020-06-29 18:22 UTC, jenseliasson commented on README.md
> +Stores sensor data in a service endpoints in the database.
done

2020-06-29 18:29 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/CommonConstants.java
> +	public static final String SWAGGER_HTTP_400_MESSAGE = "Bad request";
These lines are duplicated in the development branch also. Whey should they be?

2020-06-29 18:31 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerApplicationInitListener.java
> +	private ApplicationContext applicationContext;
done

2020-06-29 18:35 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerApplicationInitListener.java
> +	protected List<CoreSystemService> getRequiredCoreSystemServiceUris() {
Beause, I can need to add an item to that list any day, so I prefer to keep it this way to make future code changes as small as possible

2020-06-29 18:38 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	@Autowired
done,
I was looking at the eventhandler, and that system doesn't have all autowired members private. I guess that must be fixed as well...

2020-06-29 18:58 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +		int statusCode = 0;
done

2020-06-29 18:58 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +			String par = (String)it.next();
done

2020-06-29 19:01 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	@ResponseBody public DataManagerSystemsResponseDTO proxyGet() {
They are not the same. get always returns a list, put is prepared to handle different operations

2020-06-29 19:11 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +		@ApiResponse(code = HttpStatus.SC_OK, message = CoreCommonConstants.SWAGGER_HTTP_200_MESSAGE),
done

2020-06-29 19:12 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +		@ApiResponse(code = HttpStatus.SC_OK, message = CoreCommonConstants.SWAGGER_HTTP_200_MESSAGE),
done

2020-06-29 19:13 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +				throw new BadPayloadException(NOT_FOUND_ERROR_MESSAGE, HttpStatus.SC_NOT_FOUND, "/proxy/"+systemName+"/"+serviceName);
done

2020-06-29 19:14 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +		@ApiResponse(code = HttpStatus.SC_BAD_REQUEST, message = CoreCommonConstants.SWAGGER_HTTP_400_MESSAGE),
done

2020-06-29 19:16 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	  Iterator entry = sml.iterator();
done

2020-06-29 19:16 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	  System.err.println("bt: "+ element.getBt());
done

2020-06-29 19:31 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/database/service/DataManagerDBService.java
> +public class DataManagerDBService {
done

2020-06-29 19:32 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/database/service/DataManagerDBService.java
> +	private Connection connection = null;
done

2020-06-29 19:43 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/database/service/DataManagerDBService.java
> +	  } catch(SQLException se){
done

2020-06-29 19:53 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/database/service/DataManagerDBService.java
> +		  if (m.getT() < 268435456) { //if relative ts, update it
done

2020-06-29 20:00 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/database/service/DataManagerDBService.java
> +	    String signalsList = "";
done

2020-06-29 20:06 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/security/DatamanagerAccessControlFilter.java
> +        sysNameStopPosition = requestTarget.indexOf("/", sysNameStartPosition + 0 + ("/datamanager"+CommonConstants.OP_DATAMANAGER_HISTORIAN+"/").length());
done

2020-06-29 20:07 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/security/DatamanagerAccessControlFilter.java
> +        sysNameStopPosition = requestTarget.indexOf("/", sysNameStartPosition + 0 + ("/datamanager"+CommonConstants.OP_DATAMANAGER_PROXY+"/").length());
done

2020-06-29 20:14 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/DataManagerDriver.java
> +public class DataManagerDriver {
done

2020-06-29 20:14 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/DataManagerService.java
> +public class DataManagerService {
done

2020-06-29 20:16 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +  private DataManagerDriver dataManagerDriver;
done

2020-06-29 20:26 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +    if (systemName.equals("")) {
done

2020-06-29 20:26 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +    if (systemName == null || serviceName == null) {
done

2020-06-29 20:26 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +  public boolean addServiceForSystem(String systemName, String serviceName, String serviceType){
done

2020-06-29 20:26 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +    if (systemName == null || serviceName == null) {
done

2020-06-29 20:26 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +    if (systemName == null || serviceName == null) {
done

2020-06-29 20:32 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/HistorianService.java
> +    if (systemName == null || serviceName == null) {
done

2020-06-29 20:35 UTC, jenseliasson commented on scripts/datamanager_privileges.sql
> +#GRANT ALL PRIVILEGES ON `arrowhead`.`dmhist_services` TO 'datamanager'@'%';
done

2020-06-29 20:38 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/CommonConstants.java
> +	public static final String SWAGGER_HTTP_409_MESSAGE = "Request caused a conflict";
These lines are duplicated in the development branch also. Whey should they be?

2020-06-29 20:42 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	@ApiOperation(value = "Interface to get all services that s specific system has active in the Historian service", response = DataManagerServicesResponseDTO.class, tags = { CoreCommonConstants.SWAGGE
done

2020-06-29 20:44 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	@ResponseBody public DataManagerServicesResponseDTO historianSystemPut(
done

2020-07-01 17:51 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	  System.err.println("bt: "+ element.getBt());
done

2020-07-01 17:51 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/database/service/DataManagerDBService.java
> +public class DataManagerDBService {
done

2020-07-01 17:53 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/service/ProxyElement.java
> +public class ProxyElement {
done

2020-08-26 08:34 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	@Autowired
Sorry, but it is obviously not done. The private keyword is missing before the following members : proxyService, historianService, dataManagerDBService.

Yes, we made the same mistake in the EventHandlerController, I've fixed it. Thanks for the report.

2020-08-26 08:57 UTC, rbocsi commented on README.md
> +The DataManager has the following use cases:
No changes here, still 404. 'Alt test' is still present

2020-08-26 09:01 UTC, rbocsi commented on README.md
> +	"vb"; false,
; should be :

2020-08-26 09:01 UTC, rbocsi commented on README.md
> +
still missing

2020-08-26 10:04 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	@Autowired
Done

2020-08-26 10:04 UTC, jenseliasson commented on README.md
> +	"vb"; false,
done

2020-08-26 10:43 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +				count = Integer.parseInt(params.getFirst(par));
still not handle the NumberFormatException here. The two Long.parseLong() are eliminated because from and to are doubles now, but Double.parseDouble() has the same issue. The count, from and to come from query parameters so they could be anything even random sequence of characters. So you should really handle the possible NumberFormatExceptions just as you did in the case of signalXCount.

2020-08-26 11:09 UTC, rbocsi requested changes
See inline comments. Just a few problems remained.

2020-08-26 11:21 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +                Assert.notNull(systemName, "systemName is null.");
still not fixed

2020-08-26 11:22 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	  Assert.isTrue(!(bnc != 1 || btc != 1 || buc > 1), "invalid bn/bt/bu");
still not fixed

2020-08-26 12:39 UTC, jenseliasson commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +	  Assert.isTrue(!(bnc != 1 || btc != 1 || buc > 1), "invalid bn/bt/bu");
done

2020-08-26 12:48 UTC, rbocsi commented on datamanager/src/main/java/eu/arrowhead/core/datamanager/DataManagerController.java
> +				count = Integer.parseInt(params.getFirst(par));
One NumberFormatException handling is still missing: for the parameter count

2020-08-26 12:50 UTC, rbocsi commented on README.md
> +The DataManager has the following use cases:
fixed

2020-08-26 12:51 UTC, rbocsi commented on README.md
> +
still missing

2020-08-26 12:52 UTC, rbocsi requested changes
only 1 identified problem remained in the source
But also, the proxy endpoint's descriptions are missing from the ReadME

2020-08-27 09:08 UTC, jenseliasson commented
> only 1 identified problem remained in the source
> But also, the proxy endpoint's descriptions are missing from the ReadME

descriptions added, NumberFormat exception fixed

2020-08-27 09:28 UTC, rbocsi approved these changes
Ok, thanks. I'll tell Svetlin he can merge the datamanager to the development branch.

2020-08-27 10:05 UTC, tsvetlin approved these changes

2020-08-27 10:05 UTC, merged