Orchestrator store endpoints
eclipse-arrowhead/core-java-spring pull request #26
Opened 2019-07-15 07:50 UTC by MaGaMeGa

2019-07-15 09:11 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/entity/OrchestratorStore.java
> +	public OrchestratorStore(ServiceDefinition serviceDefinition, System consumerSystem, System providerSystem,
finals

2019-07-15 09:12 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/entity/OrchestratorStore.java
> +	//-------------------------------------------------------------------------------------------------
finals missing from setters

2019-07-15 09:14 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Cloud.java
> +	public void setorchestratorStores(Set<OrchestratorStore> orchestratorStores) { this.orchestratorStores = orchestratorStores; }
final

2019-07-15 09:15 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceDefinition.java
> +	public void setOrchestratorStores(Set<OrchestratorStore> orchestratorStores) { this.orchestratorStores = orchestratorStores; }
final

2019-07-15 09:16 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/entity/System.java
> +	public void setOrchestratorStoresAsConsumer(Set<OrchestratorStore> orchestratorStoresAsConsumer) { this.orchestratorStoresAsConsumer = orchestratorStoresAsConsumer; }
finals

2019-07-15 09:18 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/entity/OrchestratorStore.java
> +	public OrchestratorStore(ServiceDefinition serviceDefinition, System consumerSystem, System providerSystem,
fixed

2019-07-15 09:18 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Cloud.java
> +	public void setorchestratorStores(Set<OrchestratorStore> orchestratorStores) { this.orchestratorStores = orchestratorStores; }
fixed

2019-07-15 09:19 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/entity/OrchestratorStore.java
> +	//-------------------------------------------------------------------------------------------------
fixed

2019-07-15 10:13 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SystemRepository.java
> +	Optional<System> findWithOrchestrationStoresAsConsumerById(long id);
final

2019-07-15 10:48 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreListResponseDTO.java
> +		super();
no need for super();

2019-07-15 10:49 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreModifyPriorityRequestDTO.java
> +		super();
no need for super()

2019-07-15 10:51 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreRequestDTO.java
> +		super();
no need for super()

2019-07-15 10:52 UTC, borditamas commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreResponseDTO.java
> +		super();
no need for super()

2019-07-15 11:16 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreListResponseDTO.java
> +		super();
fixed

2019-07-15 11:16 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreModifyPriorityRequestDTO.java
> +		super();
fixed

2019-07-15 11:16 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreRequestDTO.java
> +		super();
fixed

2019-07-15 11:17 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreResponseDTO.java
> +		super();
fixed

2019-07-15 11:19 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +	public OrchestratorStoreListResponseDTO getOrchestratorStoreEntriesResponse(final int page, final int size,
Previously used pattern was having a DB service with pageable return value, and another service wich call it but convert the pageable to dto.

2019-07-15 11:26 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/Defaults.java
> +	public static final String DEFAULT_IS_GATEKEEPER_PRESENT = "false";
should be boolean

2019-07-15 11:30 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/OrchestratorStore.java
> +	private Integer priority;
use primitive int

2019-07-15 11:34 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +			throw new BadPayloadException(""+ NULL_PARAMETERS_ERROR_MESSAGE, HttpStatus.SC_BAD_REQUEST, origin);
empty string!

2019-07-15 11:35 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/OrchestratorStoreRepository.java
> +	public Page<OrchestratorStore> findAllByPriority(final int priority, PageRequest regRequest);
maybe don't need to custom query
try findByPriority second param is Pageable

2019-07-15 11:37 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +		checkOrchestratorStoreRequestDTOForByConsumerIdAndServiceDefinitionId(request, CommonConstants.ORCHESTRATOR_STORE_MGMT_URI );
delete "By" from method name

2019-07-15 11:39 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/OrchestratorStoreRepository.java
> +	@Query("SELECT entry FROM OrchestratorStore entry WHERE  consumerSystem.id = ?1 AND serviceDefinition.id = ?2 ")
try findByConsumerSystemAndServiceDefinition with entity parameters and Pageable

2019-07-15 11:40 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SystemRepository.java
>  	Optional<System> findBySystemNameAndAddressAndPort(final String systemName, final String address, final int port);
public

2019-07-15 11:42 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		Assert.notNull(entity.getId(), "OrchestratorStore.id is null");
primitive, can't be null

2019-07-15 11:42 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		Assert.notNull(entity.getPriority(), "OrchestratorStore.Priority is null");
will be primitive, can't be null

2019-07-15 11:47 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +			return DTOConverter.convertOrchestratorStoreEntryListToOrchestratorStoreListResponseDTO(savedOrchestratorStoreEntries);
new entries should be saved in bulk instead of saving one-by-one

2019-07-15 11:50 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +					savedOrchestratorStoreEntries.add(createOrchestratorStoreEntityById(orchestratorStoreRequestByIdDTO));
new entries should be saved in bulk instead of saving one-by-one

2019-07-15 11:51 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreRequestByIdDTO.java
> +	private String attribute;
use Map<String,String> instead of String

2019-07-15 11:51 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreRequestDTO.java
> +	private String attribute;
Map<String,String>

2019-07-15 11:52 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreResponseDTO.java
> +	private String attribute;
Map<String,String>

2019-07-15 11:53 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreResponseDTO.java
> +	private ZonedDateTime createdAt;
use String

2019-07-15 11:55 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +	private static final String ORCHESTRATOR_STORE_MGMT_ALL_TOP_PRIORITY = CommonConstants.ORCHESTRATOR_STORE_MGMT_URI + "/all_topPriority";
use _ instead of camel case

2019-07-15 11:55 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		final Map<Long, Integer> priorityMap = new HashMap(orchestratorStoreList.size());
missing diamond: new HashMap<>(...);

2019-07-15 11:56 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		final Map<Long, Integer> modifyedPriorityMap = new HashMap(priorityMap.size() - 1);
missing diamond: new HashMap<>(...);

2019-07-15 11:56 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +	private static final String ORCHESTRATOR_STORE_MGMT_MODIFY = CommonConstants.ORCHESTRATOR_STORE_MGMT_URI + "/modify";
rename modify_priorities

2019-07-15 11:58 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +			final List<OrchestratorStore> savedOrchestratorStoreEntries = new ArrayList();
missing diamond: new ArrayList<>(...);

2019-07-15 12:01 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +			final Optional<OrchestratorStore> orchestratorStoreOption = orchestratorStoreRepository.findById(id);
consider to use ...Repository.existsById(id);

2019-07-15 12:05 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +	@ApiOperation(value = "Modify prioities of OrchestratorStore entries.")
typo prioRities

2019-07-15 12:06 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +			throw new BadPayloadException(""+ NULL_PARAMETERS_ERROR_MESSAGE, HttpStatus.SC_BAD_REQUEST, origin);
it's a Long

2019-07-15 12:08 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +	}
remove elses

2019-07-15 12:11 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		Collections.sort(updatedOrchestratorStoreList, getOrchestratorStorePriorityComparator());
Does sorting really necessary?

2019-07-15 12:11 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +			}
check all ids in the DTO (+ chekc priority is greater than 0)

2019-07-15 12:12 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +		if ( request.getPriorityMap().isEmpty()) {
checks if map is null

2019-07-15 12:14 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +		for (final Long consumerSystemId : priorityMap.keySet()) {
use entry set

2019-07-15 12:14 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +			orchestratorStoreRepository.saveAndFlush(orchestratorStore);
consider to use ...Repository.saveAll(Iterable<>);
also consider the validity of this method

2019-07-15 12:15 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +			if (consumerSystemId == null) {
check consumerSystemId is greater than 0 instead of null check

2019-07-15 12:16 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +			}
check priority is greater than 0 too

2019-07-15 12:17 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +	private static final String LESS_THEN_ONE_ERROR_MESAGE= " must be greater then zero.";
then => than

2019-07-15 12:17 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +	private static final String NOT_AVAILABLE_SHORTABLE_FIELD_ERROR_MESAGE = "The following shortable field  is not available : ";
Shortable => sortable

2019-07-15 12:18 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		final List<OrchestratorStore> orchestratorStoreList = new ArrayList(modifyedPriorityMap.size());
missing diamond new Arraylist<>(...)

2019-07-15 12:18 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +	private static final String ORCHESTRATORSTORE_REQUESTBYIDDTO_VALIDATION_EXCEPTION_MESSAGE = "Exception in OrchestratorStoreRequestByIdDTO validation, entry not going to be added to save list." ;
use _ between words

2019-07-15 12:19 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +	private static final String MODIFY_PRIORITY_MAP_EXCEPTION_MESSAGE = "OrchestratorStore entry List size != PriorityMap size ";
don't use != instead use not equals

2019-07-15 12:21 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		final List<OrchestratorStore> updatedOrchestratorStore = new ArrayList(orchestratorStoreList.size());
missing diamond new Arraylist<>(...)

2019-07-15 12:31 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		} catch (final InvalidParameterException ex) {
remove this catch block

2019-07-15 12:34 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +	private void refreshOrchestratorStoreListByModifyedPriorityMap(final List<OrchestratorStore> orchestratorStoreList, final Map<Long, Integer> priorityMap ) {
I think this method change the priorities first to *-1, then back to the original.

2019-07-15 12:35 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +			final Optional<List<OrchestratorStore>> orchestratorStoreListOption = orchestratorStoreRepository.findAllByConsumerIdAndServiceDefinitionId(
consider using List instead of Option<List<...>>

2019-07-15 12:36 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +			final Map<Long, Integer> modifyedPriorityMap = decreaseInvolvedPrioritiesInPriorityMap(priority, originalPriorityMap);
typo modified

2019-07-15 12:36 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		for (final OrchestratorStore orchestratorStore : orchestratorStoreList) {
this for is really necessary?

2019-07-15 12:39 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +
repo method should return list in order (by priority)
replace 3 method with one for loop where you decrease priorites if neccessary

2019-07-15 12:40 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		orchestratorStoreRepository.saveAll(updatedOrchestratorStore);
should not save at this time. Would be better to sort this list and change the priorities in order afterward

2019-07-15 13:03 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		final List<OrchestratorStore> updatedOrchestratorStore = new ArrayList(orchestratorStoreList.size());
missing <>

2019-07-15 13:18 UTC, rbocsi requested changes
see inline comments

2019-07-15 13:19 UTC, borditamas requested changes
see comments

2019-07-15 13:24 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/Defaults.java
> +	public static final String DEFAULT_IS_GATEKEEPER_PRESENT = "false";
fixed

2019-07-15 13:27 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/entity/OrchestratorStore.java
> +	private Integer priority;
fixed

2019-07-15 13:46 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +	private static final String ORCHESTRATOR_STORE_MGMT_ALL_TOP_PRIORITY = CommonConstants.ORCHESTRATOR_STORE_MGMT_URI + "/all_topPriority";
fixed

2019-07-15 13:47 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +	private static final String ORCHESTRATOR_STORE_MGMT_MODIFY = CommonConstants.ORCHESTRATOR_STORE_MGMT_URI + "/modify";
fixed

2019-07-15 13:48 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +		checkOrchestratorStoreRequestDTOForByConsumerIdAndServiceDefinitionId(request, CommonConstants.ORCHESTRATOR_STORE_MGMT_URI );
fixed

2019-07-15 13:49 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +	@ApiOperation(value = "Modify prioities of OrchestratorStore entries.")
fixed

2019-07-15 13:51 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +	}
fixed

2019-07-15 13:59 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +			}
fixed

2019-07-15 14:02 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +		if ( request.getPriorityMap().isEmpty()) {
fixed

2019-07-15 14:06 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +		for (final Long consumerSystemId : priorityMap.keySet()) {
fixed

2019-07-15 14:07 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +			if (consumerSystemId == null) {
fixed

2019-07-15 14:07 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorStoreController.java
> +			}
fixed

2019-07-15 14:09 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +	private static final String LESS_THEN_ONE_ERROR_MESAGE= " must be greater then zero.";
fixed

2019-07-15 14:10 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +	private static final String NOT_AVAILABLE_SHORTABLE_FIELD_ERROR_MESAGE = "The following shortable field  is not available : ";
fixed

2019-07-15 14:13 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +	private static final String MODIFY_PRIORITY_MAP_EXCEPTION_MESSAGE = "OrchestratorStore entry List size != PriorityMap size ";
fixed

2019-07-15 14:18 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +	private static final String ORCHESTRATORSTORE_REQUESTBYIDDTO_VALIDATION_EXCEPTION_MESSAGE = "Exception in OrchestratorStoreRequestByIdDTO validation, entry not going to be added to save list." ;
fixed

2019-07-15 14:20 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		} catch (final InvalidParameterException ex) {
fixed

2019-07-15 14:25 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +			final Optional<List<OrchestratorStore>> orchestratorStoreListOption = orchestratorStoreRepository.findAllByConsumerIdAndServiceDefinitionId(
fixed

2019-07-15 14:28 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +			final Map<Long, Integer> modifyedPriorityMap = decreaseInvolvedPrioritiesInPriorityMap(priority, originalPriorityMap);
fixed

2019-07-15 14:30 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		final Map<Long, Integer> priorityMap = new HashMap(orchestratorStoreList.size());
fixed

2019-07-15 14:31 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		final List<OrchestratorStore> updatedOrchestratorStore = new ArrayList(orchestratorStoreList.size());
fixed

2019-07-15 14:31 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		final List<OrchestratorStore> updatedOrchestratorStore = new ArrayList(orchestratorStoreList.size());
fixed

2019-07-15 14:35 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		orchestratorStoreRepository.saveAll(updatedOrchestratorStore);
shuld save here, otherwise could run into priority duplication problems

2019-07-16 07:24 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +
fixed

2019-07-16 07:43 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreResponseDTO.java
> +	private ZonedDateTime createdAt;
fixed

2019-07-16 08:12 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreRequestDTO.java
> +	private String attribute;
fixed

2019-07-16 08:12 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreResponseDTO.java
> +	private String attribute;
fixed

2019-07-16 08:35 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +	public OrchestratorStoreListResponseDTO getOrchestratorStoreEntriesResponse(final int page, final int size,
fixed

2019-07-16 08:36 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/OrchestratorStoreRequestByIdDTO.java
> +	private String attribute;
fixed

2019-07-16 08:39 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		Assert.notNull(entity.getId(), "OrchestratorStore.id is null");
fixed

2019-07-16 08:39 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		Assert.notNull(entity.getPriority(), "OrchestratorStore.Priority is null");
fixed

2019-07-16 08:40 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +			final List<OrchestratorStore> savedOrchestratorStoreEntries = new ArrayList();
fixed

2019-07-16 09:17 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		Collections.sort(updatedOrchestratorStoreList, getOrchestratorStorePriorityComparator());
refractored

2019-07-16 09:17 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +			orchestratorStoreRepository.saveAndFlush(orchestratorStore);
refactored

2019-07-16 09:18 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		final List<OrchestratorStore> orchestratorStoreList = new ArrayList(modifyedPriorityMap.size());
fixed

2019-07-16 09:18 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SystemRepository.java
> +	Optional<System> findWithOrchestrationStoresAsConsumerById(long id);
refactored

2019-07-16 10:09 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/repository/OrchestratorStoreRepository.java
> +	public Page<OrchestratorStore> findAllByPriority(final int priority, PageRequest regRequest);
fixed

2019-07-16 10:52 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/repository/OrchestratorStoreRepository.java
> +	@Query("SELECT entry FROM OrchestratorStore entry WHERE  consumerSystem.id = ?1 AND serviceDefinition.id = ?2 ")
fixed

2019-07-16 10:53 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SystemRepository.java
>  	Optional<System> findBySystemNameAndAddressAndPort(final String systemName, final String address, final int port);
fixed

2019-07-16 10:56 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceDefinition.java
> +	public void setOrchestratorStores(Set<OrchestratorStore> orchestratorStores) { this.orchestratorStores = orchestratorStores; }
refactored

2019-07-16 10:56 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/entity/System.java
> +	public void setOrchestratorStoresAsConsumer(Set<OrchestratorStore> orchestratorStoresAsConsumer) { this.orchestratorStoresAsConsumer = orchestratorStoresAsConsumer; }
refactored

2019-07-22 08:24 UTC, rbocsi commented
this code is merged into the foreign system branch.

2019-07-22 08:24 UTC, closed without merging