Configuration system
eclipse-arrowhead/core-java-spring pull request #297
Opened 2021-03-29 21:13 UTC by jenseliasson

This is the Configuration support core system.

2021-03-31 09:39 UTC, rbocsi commented on configuration/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_configuration || true
To make this work, you have to extend the arrowhead-core-common/src/deb/control/templates file with something like this:

```
Template: arrowhead-core-common/mysql_password_configuration
Type: password
Default:
Description: MySQL password for Configuration system (leave empty for random).
```

2021-03-31 10:01 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/ConfigurationController.java
> +	@ResponseBody public ConfigurationListResponseDTO confListGet(
It is good for a first version. 

But for a larger cloud, where hundreds or thousands of configuration can exist, I think we need a web service that supports paging. There are a lot of examples for that in the other core systems (for example SR).

2021-03-31 10:03 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/ConfigurationController.java
> +			@ApiResponse(code = HttpStatus.SC_NOT_FOUND, message = CoreCommonConstants.SWAGGER_HTTP_404_MESSAGE),
In the worst case, this one returns an empty list. I don't think NOT_FOUND is needed here.

2021-03-31 10:39 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/ConfigurationController.java
> +			throw new BadPayloadException("Bad payload");
At least, pass the e.getMessage() to the new exception. so the user don't have to guess what was the problem.

2021-03-31 10:40 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/ConfigurationController.java
> +			Assert.notNull(systemName, "systemName is null.");
empty string is fine? (for every check here)

2021-03-31 10:42 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/database/service/ConfigurationDBService.java
> +	public ConfigurationResponseDTO getConfigForSystem(final String systemName) {
check input

2021-03-31 10:44 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/database/service/ConfigurationDBService.java
> +	public ConfigurationResponseDTO setConfigForSystem(final String systemName, final ConfigurationRequestDTO conf) {
input check

2021-03-31 10:50 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/database/service/ConfigurationDBService.java
> +			if (rs.next()) {
this one returns one or zero records, because no loop here

2021-03-31 10:51 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/database/service/ConfigurationDBService.java
> +		logger.debug("deleteConfigForSystem:");
input check & transformation

2021-03-31 10:52 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/security/ConfigurationAccessControlFilter.java
> +                final String configurationRawConfURI = CommonConstants.CONFIGURATION_URI + CommonConstants.OP_CONFIGURATION_RAWCONF;
these could be local constants, and then you can use here and the previous method as well.

2021-03-31 10:55 UTC, rbocsi commented on configuration/src/main/resources/log4j2.xml
> +		<RollingFile name="FileAppender" fileName="${LOG_DIR}/datamanager.log" filePattern="${LOG_DIR}/datamanager-%d{yyyy-MM-dd}-%i.log">
rename the files in fileName and filePattern

2021-03-31 11:01 UTC, rbocsi commented on configuration/src/main/resources/application.properties
> +domain.port=8463
this and the server.port should be the default port in the repository (according to the Defaults class, it's 8459)

2021-03-31 11:18 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/ConfigurationController.java
> +	@ResponseBody public ConfigurationResponseDTO storeConfigurationForSystem(@PathVariable(value = PATH_VARIABLE_NAME) final String systemName, @RequestBody final ConfigurationRequestDTO config) {
systemName has to be in the path and in the body (DTO) as well. Why? What happens if the two are not match?

2021-03-31 11:21 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/database/service/ConfigurationDBService.java
> +				ret.setUpdatedAt(rs.getString(5));
DB stores the dates in local time. But in the response we expect them in UTC. So you have to make a conversion here.

2021-03-31 11:22 UTC, rbocsi commented on configuration/src/main/java/eu/arrowhead/core/configuration/database/service/ConfigurationDBService.java
> +				entry.setUpdatedAt(rs.getString(6));
DB stores the dates in local time. But in the response we expect them in UTC. So you have to make a conversion here.

2021-03-31 11:25 UTC, rbocsi requested changes
see inline comments

Also, please copy the src/main/resources/certificates/configuration.p12 to the certificates/testcloud2 folder as well.

2021-04-01 06:38 UTC, jenseliasson commented on configuration/src/main/java/eu/arrowhead/core/configuration/ConfigurationController.java
> +	@ResponseBody public ConfigurationListResponseDTO confListGet(
Agree, I'll do it for for 5.0 then

2021-04-01 06:41 UTC, jenseliasson commented on configuration/src/main/java/eu/arrowhead/core/configuration/ConfigurationController.java
> +			@ApiResponse(code = HttpStatus.SC_NOT_FOUND, message = CoreCommonConstants.SWAGGER_HTTP_404_MESSAGE),
Good point. Done!

2021-04-01 06:43 UTC, jenseliasson commented on configuration/src/main/java/eu/arrowhead/core/configuration/ConfigurationController.java
> +			throw new BadPayloadException("Bad payload");
Fixed!

2021-04-01 06:49 UTC, jenseliasson commented on configuration/src/main/java/eu/arrowhead/core/configuration/ConfigurationController.java
> +			Assert.notNull(systemName, "systemName is null.");
Fixed

2021-04-01 07:09 UTC, jenseliasson commented on configuration/src/main/java/eu/arrowhead/core/configuration/database/service/ConfigurationDBService.java
> +	public ConfigurationResponseDTO getConfigForSystem(final String systemName) {
Fixed

2021-04-01 07:12 UTC, jenseliasson commented on configuration/src/main/java/eu/arrowhead/core/configuration/database/service/ConfigurationDBService.java
> +	public ConfigurationResponseDTO setConfigForSystem(final String systemName, final ConfigurationRequestDTO conf) {
Fixed

2021-04-01 07:41 UTC, jenseliasson commented on configuration/src/main/java/eu/arrowhead/core/configuration/database/service/ConfigurationDBService.java
> +			if (rs.next()) {
That was a real bug, thanks.
Fixed!

2021-04-01 07:43 UTC, jenseliasson commented on configuration/src/main/java/eu/arrowhead/core/configuration/database/service/ConfigurationDBService.java
> +		logger.debug("deleteConfigForSystem:");
Fixed

2021-04-01 07:48 UTC, jenseliasson commented on configuration/src/main/java/eu/arrowhead/core/configuration/security/ConfigurationAccessControlFilter.java
> +                final String configurationRawConfURI = CommonConstants.CONFIGURATION_URI + CommonConstants.OP_CONFIGURATION_RAWCONF;
correct, and fixed!

2021-04-01 07:49 UTC, jenseliasson commented on configuration/src/main/resources/log4j2.xml
> +		<RollingFile name="FileAppender" fileName="${LOG_DIR}/datamanager.log" filePattern="${LOG_DIR}/datamanager-%d{yyyy-MM-dd}-%i.log">
Fixed

2021-04-02 07:05 UTC, jenseliasson commented on configuration/src/main/resources/application.properties
> +domain.port=8463
Updated!

2021-04-02 07:11 UTC, jenseliasson commented on configuration/src/main/java/eu/arrowhead/core/configuration/ConfigurationController.java
> +	@ResponseBody public ConfigurationResponseDTO storeConfigurationForSystem(@PathVariable(value = PATH_VARIABLE_NAME) final String systemName, @RequestBody final ConfigurationRequestDTO config) {
The reason is to have same some style for all interfaces, and to prevent a configuration message for system X to be stored for system Y. Code has been updated to double check the names

2021-04-02 07:20 UTC, jenseliasson commented on configuration/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_configuration || true
Fixed!

2021-04-03 07:43 UTC, jenseliasson commented on configuration/src/main/java/eu/arrowhead/core/configuration/database/service/ConfigurationDBService.java
> +				entry.setUpdatedAt(rs.getString(6));
Fixed!

2021-04-08 10:01 UTC, rbocsi approved these changes

2021-06-30 13:11 UTC, merged