MSCV merge into development
eclipse-arrowhead/core-java-spring pull request #315
Opened 2021-05-31 12:59 UTC by mzsilak

2021-06-02 11:03 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/security/AuthAccessControlFilter.java
> +	private static final CoreSystem[] allowedCoreSystemsForRuleMgmt = { CoreSystem.ONBOARDING_CONTROLLER, CoreSystem.MSCV };
According to the pom.xml MSCV is stands for Monitoring and Standard Compliance Verification. Why do you need unlimited access to the intracloud authorization for monitoring and verification? Please explain.

2021-06-02 11:17 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Mip.java
> +public class Mip {
I think using Mip as entry name is decrease readability. I realize this is stands for  Measurable Indicator Points because I found this text in the Constants class. But it is not common knowledge for Arrowhead developers and the Internet is not a good help in this case (Macrophage Inflammatory Protein (immunology), Mortgage Insurance Premium, Minor In Possession, Mixed Integer Programming is the first four hit). 
So maybe you can use the MeasurableIndicatorPoint as entry name (and mscv_measurable_indicator_point as table name). At the very least, please add a comment here WTF Mip is.

<!--EndFragment-->

)

2021-06-02 11:17 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Mip.java
> +    private Long id;
not null so it should be primitive long

2021-06-02 11:18 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Mip.java
> +    private Integer extId;
if the column is not null then the member should be int

2021-06-02 11:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Mip.java
> +    public Mip(final String name,
Integer => int

2021-06-02 11:27 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Mip.java
> +        if(Objects.nonNull(category)) return category.getAbbreviation() + "-" + extId;
Please do not use if, else, for, while etc. without braces. I know Java allows it, but it is not a good practice.

2021-06-02 11:28 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Mip.java
> +    }
Long => long

2021-06-02 11:28 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Mip.java
> +    }
Integer => int

2021-06-02 11:30 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/MipCategory.java
> +    private Long id;
should be primitive long (in getter/setter too)

2021-06-02 11:31 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/MipDomain.java
> +    private Long id;
should be primitive long (in getter/setter too)

2021-06-02 11:31 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Script.java
> +    private Long id;
should be primitive long (in getter/setter too)

2021-06-02 11:32 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Script.java
> +    public Script(final Long id, final Mip mip, final Layer layer, final OS os, final String physicalPath) {
Long => long

2021-06-02 11:34 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/SshTarget.java
> +    private Integer port;
should be primitive int (in getter/setter too)

2021-06-02 11:36 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/SshTarget.java
> +    private String authInfo;
authInfo in other systems usually stores the public key. Are you storing here a public key? If not, maybe you should rename this column/field to avoid confusion.

2021-06-02 11:36 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/SshTarget.java
> +    public SshTarget(final String name, final OS os, final String address, final Integer port) {
Integer => int

2021-06-02 11:36 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/SshTarget.java
> +    public SshTarget(final Long id, final String name, final OS os, final String address, final Integer port, final String username, final String authInfo) {
Long => long, Integer => int

2021-06-02 11:37 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Standard.java
> +    private Long id;
should be primitive long (in getter/setter too)

2021-06-02 11:37 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Standard.java
> +    public Standard(final Long id, final String identification, final String name, final String referenceUri) {
Long => long

2021-06-02 11:38 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Target.java
> +    private Long id;
should be primitive long (in getter/setter too)

2021-06-02 11:41 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Target.java
> +    public Target(final Long id, final String name, final OS os) {
Long => long

2021-06-02 11:42 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationEntry.java
> +    private Long id;
should be primitive long (in getter/setter too)

2021-06-02 11:51 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationEntry.java
> +    private Short weight;
should be primitive short (in getter/setter too)

2021-06-02 11:51 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationEntry.java
> +    public VerificationEntry(final Mip mip, final Short weight, final VerificationEntryList entryList) {
Short => short

2021-06-02 11:51 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationEntry.java
> +    public VerificationEntry(final Long id, final Mip mip, final Short weight, final VerificationEntryList entryList) {
Long => long, Short => short

2021-06-02 11:52 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationEntryList.java
> +    private Long id;
should be primitive long (in getter/setter too)

2021-06-02 11:52 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationEntryList.java
> +    private Long verificationInterval;
should be primitive long (in getter/setter too)

2021-06-02 11:53 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationEntryList.java
> +                                 final Long verificationInterval,
Long => long

2021-06-02 11:53 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationEntryList.java
> +    public VerificationEntryList(final Long id, final String name, final String description,
Long => long (x2)

2021-06-02 11:54 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationEntryList.java
> +        Assert.notNull(entry,"Verification entry must not be mull");
typo: mull => null

2021-06-02 11:55 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationEntryList.java
> +        Assert.notNull(entry,"Verification entry must not be mull");
same typo again

2021-06-02 11:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationResult.java
> +    private Long id;
should be primitive long (in getter/setter too)

2021-06-02 11:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationResult.java
> +    public VerificationResult(final Long id,
Long => long

2021-06-02 11:58 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationResultDetail.java
> +    private Long id;
should be primitive long (in getter/setter too)

2021-06-02 11:59 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationResultDetail.java
> +    public VerificationResultDetail(final Long id, final VerificationResult execution,
Long => long

2021-06-02 12:00 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/VerificationResultDetail.java
> +        this.details = details;
constructor should do the same thing with details than the setter.

2021-06-02 12:02 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/MipRepository.java
> +    MipView findViewById(final Long id);
Long => long

2021-06-02 12:04 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/MipRepository.java
> +    Optional<Mip> findByCategoryAbbreviationAndExtId(final String categoryAbbreviation, final Integer extId);
Integer => int (x2)

Also, why change the order in the second one? I find it confusing.

2021-06-02 12:15 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/SshTargetRepository.java
> +    List<SshTarget> findViewByName(final String name);
The return list does not contain view objects, but actual entities

2021-06-02 12:16 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/SshTargetRepository.java
> +    <S extends SshTarget> Optional<S> findByAddressAndPort(final String address, final Integer port);
Integer => int

2021-06-02 12:17 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/StandardRepository.java
> +    Optional<Standard> findByIdentification(final String name);
parameter name should be identification to avoiding confusion

2021-06-02 12:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/VerificationEntryListRepository.java
> +    Optional<VerificationListView> findViewById(final Long id);
Long => long

2021-06-02 12:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/VerificationEntryRepository.java
> +    Optional<VerificationEntryView> findViewById(final Long id);
Long => long

2021-06-02 12:21 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/MipRepository.java
> +    MipView findViewByName(final String name);
maybe Optional<MipView> for return type

2021-06-02 12:24 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/VerificationExecutionDetailRepository.java
> +    @Deprecated
MSCV does not even be released. If something is deprecated, just delete it (or replace it).

2021-06-02 12:27 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/VerificationExecutionRepository.java
> +    VerificationResult findViewById(final Long id);
VerificationResult is not a view, but an entity. Also, maybe return type should be Optional<VerificationResult>. Also Long => long

2021-06-02 12:30 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/VerificationExecutionRepository.java
> +    VerificationResult findTopViewByTargetAndVerificationListOrderByExecutionDateDesc(final Target target, final VerificationEntryList entryList);
VerificationResult is not a view, but an entity. Also, maybe return type should be `Optional<VerificationResult>`.

2021-06-02 12:30 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/mscv/VerificationExecutionRepository.java
> +    VerificationResult findTopViewByTargetAndVerificationListLayerOrderByExecutionDateDesc(final Target target, final Layer layer);
VerificationResult is not a view, but an entity. Also, maybe return type should be `Optional<VerificationResult>`.

2021-06-02 14:17 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/MipViewImpl.java
> +public class MipViewImpl implements MipView {
I am not sure about it because I don't know Spring JPA Data projections in details, but after reading the reference it seems to me that you don't have to implement the MipView interface after annotating with `@Value` expressions, because the Spring will generate an implementation for you. So maybe this class is unnecessary, but as I said I am not an expert in projections.

ps: Thanks you for using this mechanism. I learned something new today.

2021-06-02 14:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationEntryView.java
> +    Long getId();
Long => long

2021-06-02 14:20 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationEntryView.java
> +    Short getWeight();
Short => short, also expression in annotation is not right.

2021-06-02 14:21 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationEntryView.java
> +    @Value("#{target.id}")
expression in annotation is not right.

2021-06-02 14:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationEntryViewImpl.java
> +    public Long getId() {
Long => long

2021-06-02 14:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationEntryViewImpl.java
> +    public Short getWeight() {
Short => short

2021-06-02 14:23 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationExecutionDetailView.java
> +    Integer getResultWeight();
Integer => short

2021-06-02 14:24 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationExecutionDetailView.java
> +    String getVerificationSet();
It's the name of the verificationList and the name of the method is getVerificationSet?

2021-06-02 14:24 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationExecutionView.java
> +    Long getId();
Long => long

2021-06-02 14:25 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationExecutionViewImpl.java
> +    public Long getId() {
Long => long

2021-06-02 14:26 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationListView.java
> +    Long getId();
Long => long

2021-06-02 14:26 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationListView.java
> +    Long getVerificationInterval();
Long => long

2021-06-02 14:26 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationListViewImpl.java
> +    public Long getId() {
Long => long

2021-06-02 14:26 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationListViewImpl.java
> +    public Long getVerificationInterval() {
Long => long

2021-06-02 14:27 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/VerificationListViewImpl.java
> +        final var set = new HashSet<VerificationEntryView>();
Please do not use var in java code. It decreases readability.

2021-06-03 12:47 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/CategoryDto.java
> +public class CategoryDto implements Serializable {
if you use Serializable, please generate a serialVersionUuid as well.

2021-06-03 12:48 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/ClientExecutionRequest.java
> +public class ClientExecutionRequest implements Serializable {
if you use Serializable, please generate a serialVersionUuid as well.

2021-06-03 12:52 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/ClientExecutionRequest.java
> +    private Layer layer;
In a request dto it is better to use String fields instead of enums. This way, you can validate the string that is represent a Layer element, and return a good error message to the user. If you expect an enum value and the user gives you a wrong one, the Jackson failed to parse the JSON to the DTO and returns a much generic error response.

2021-06-03 12:53 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/DomainDto.java
> +public class DomainDto implements Serializable {
if you use Serializable, please generate a serialVersionUuid as well.

2021-06-03 12:56 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/MipDto.java
> +public class MipDto implements Serializable {
if you use Serializable, please generate a serialVersionUuid as well.

This class should be a more understandable name (see details in Mip entity class).

2021-06-03 12:57 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/MipIdentifierDto.java
> +public class MipIdentifierDto implements Serializable {
if you use Serializable, please generate a serialVersionUuid as well.

2021-06-03 13:01 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/ScriptRequestDto.java
> +public class ScriptRequestDto implements Serializable {
if you use Serializable, please generate a serialVersionUuid as well.

2021-06-03 13:01 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/ScriptRequestDto.java
> +    private OS os;
see comments before about using enum values in request objects

2021-06-03 13:04 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/StandardDto.java
> +public class StandardDto implements Serializable {
if you use Serializable, please generate a serialVersionUuid as well.

2021-06-03 13:05 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/TargetDto.java
> +public class TargetDto implements Serializable {
if you use Serializable, please generate a serialVersionUuid as well.

2021-06-03 13:06 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/TargetDto.java
> +    private OS os;
If this DTO is used in a request, then it is not a good idea to use enum values in it, see previous comments about enums and request DTOs.

2021-06-03 13:06 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/TargetLoginRequest.java
> +public class TargetLoginRequest implements Serializable {
if you use Serializable, please generate a serialVersionUuid as well.

2021-06-03 13:18 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +        return deleteJob(context.getScheduler(), context.getJobDetail());
assert that context is not null

2021-06-03 13:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +        return unscheduleJob(context.getScheduler(), context.getTrigger());
assert that context is not null

2021-06-03 13:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +        return rescheduleJob(context.getScheduler(), context.getTrigger(), newTrigger);
assert that context is not null

2021-06-03 13:20 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +        pauseJob(context.getScheduler(), context.getJobDetail());
assert that context is not null

2021-06-03 13:20 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +    public static void pauseTrigger(final JobExecutionContext context, final Trigger trigger) throws SchedulerException {
assert that context is not null,

also trigger parameter is not used

2021-06-03 13:21 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +    public static void resumeJob(final JobExecutionContext context) throws SchedulerException {
assert that context is not null

2021-06-03 13:21 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +    public static void resumeTrigger(final JobExecutionContext context, final Trigger trigger) throws SchedulerException {
assert that context is not null

also, trigger parameter is not used

2021-06-03 13:21 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +    public static boolean silentlyDeleteJob(final JobExecutionContext context) {
assert that context is not null

2021-06-03 13:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +    public static boolean silentlyUnscheduleJob(final JobExecutionContext context) {
assert that context is not null

2021-06-03 13:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +    public static ZonedDateTime silentlyRescheduleJob(final JobExecutionContext context, final Trigger newTrigger) {
assert that context is not null

2021-06-03 13:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +    public static void silentlyPauseJob(final JobExecutionContext context) {
assert that context is not null

2021-06-03 13:23 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +    public static void silentlyPauseTrigger(final JobExecutionContext context, final Trigger trigger) {
assert that context is not null

also, trigger parameter is not used

2021-06-03 13:23 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +    public static void silentlyResumeJob(final JobExecutionContext context) {
assert that context is not null

2021-06-03 13:23 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +    public static void silentlyResumeTrigger(final JobExecutionContext context, final Trigger trigger) {
assert that context is not null

also, trigger parameter is not used.

2021-06-03 13:29 UTC, rbocsi commented on mscv/src/deb/arrowhead-mscv.service
> +[Unit]
Please delete the previous file from the repository:  mscv/public7275390519080648892.pem.tmp

2021-06-03 13:32 UTC, rbocsi commented on mscv/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_onboarding || true
don't use the the onboarding controller's password, use a new one. To do this, you have to extend the templates file located in the core-common/src/deb/control folder

2021-06-03 13:34 UTC, rbocsi commented on mscv/src/deb/control/control
> +Package: arrowhead-onboarding
invalid

2021-06-03 13:35 UTC, rbocsi commented on mscv/src/deb/control/postinst
> +SYSTEM_NAME="msvc"
typo msvc => mscv

2021-06-03 13:35 UTC, rbocsi commented on mscv/src/deb/control/postinst
> +PKG_NAME="arrowhead-msvc"
typo msvc => mscv

2021-06-03 13:36 UTC, rbocsi commented on mscv/src/deb/control/postinst
> +		db_get arrowhead-core-common/mysql_password_msvc; system_passwd=$RET || true
typo msvc => mscv

2021-06-03 13:36 UTC, rbocsi commented on mscv/src/deb/control/postinst
> +		db_unregister arrowhead-core-common/mysql_password_msvc
typo msvc => mscv

2021-06-03 13:38 UTC, rbocsi commented on mscv/src/deb/control/postrm
> +SYSTEM_NAME="msvc"
typo msvc => mscv

2021-06-03 13:39 UTC, rbocsi commented on mscv/src/deb/control/preinst
> +# preinst script for arrowhead-msvc
typo msvc => mscv

2021-06-03 13:39 UTC, rbocsi commented on mscv/src/deb/control/postinst
> +# postinst script for arrowhead-msvc
typo msvc => mscv

2021-06-03 13:40 UTC, rbocsi commented on mscv/src/deb/control/postrm
> +# postrm script for arrowhead-onboarding
incorrect

2021-06-03 13:40 UTC, rbocsi commented on mscv/src/deb/control/prerm
> +# prerm script for arrowhead-msvc
typo msvc => mscv

2021-06-03 13:40 UTC, rbocsi commented on mscv/src/deb/control/prerm
> +PKG_NAME="arrowhead-msvc"
typo msvc => mscv

2021-06-03 13:42 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvApplicationInitListener.java
> +    public MscvApplicationInitListener(final DriverUtilities driver) {this.driver = driver;}
missing `@Autowired`

2021-06-03 13:49 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvApplicationInitListener.java
> +        for (CoreSystemService coreSystemService : getRequiredCoreSystemServiceUris()) {
No. We won't give right the MSCV to create auth rules as it see fit. Instead, go over the required core system's ACCESS CONTROL filters and enable there the access for the MSCV.

2021-06-03 13:56 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvDtoConverter.java
> +        if (Objects.isNull(entry)) { return null; } else { return new VerificationEntryViewImpl(entry); }
use ternary operator or split into multiple lines for better readability.

2021-06-03 13:56 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvDtoConverter.java
> +        if (Objects.isNull(mip)) { return null; } else { return new MipViewImpl(mip); }
use ternary operator or split into multiple lines for better readability.

2021-06-03 13:57 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvDtoConverter.java
> +        if (Objects.isNull(mipCategory)) { return null; } else { return new CategoryDto(mipCategory.getName(), mipCategory.getAbbreviation()); }
use ternary operator or split into multiple lines for better readability.

2021-06-03 13:58 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvDtoConverter.java
> +        if (Objects.isNull(dto)) { return null; } else { return new MipCategory(dto.getName(), dto.getAbbreviation()); }
use ternary operator or split into multiple lines for better readability.

2021-06-03 13:58 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvDtoConverter.java
> +        if (Objects.isNull(domain)) { return null; } else { return new MipDomain(domain.getName()); }
use ternary operator or split into multiple lines for better readability.

2021-06-03 13:58 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvDtoConverter.java
> +        if (Objects.isNull(domain)) { return null; } else { return new DomainDto(domain.getName()); }
use ternary operator or split into multiple lines for better readability.

2021-06-03 13:59 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvDtoConverter.java
> +        final Mip mip = new Mip();
check dto is null or not

2021-06-07 10:38 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/Validation.java
> +        logger.debug("verify({},{}) started...", dto, origin);
Maybe you want to something like this in the previous four methods as well

2021-06-07 10:41 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/Validation.java
> +        if (Objects.isNull(standard)) {
missing debug line

2021-06-07 10:41 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/Validation.java
> +        if (Objects.isNull(mipId)) {
missing debug line

2021-06-07 10:42 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/Validation.java
> +        if (Objects.isNull(mipId)) {
missing debug line

2021-06-07 10:42 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/Validation.java
> +        if (Objects.isNull(layer)) {
missing debug line

2021-06-07 10:42 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/Validation.java
> +        if (Objects.isNull(os)) {
missing debug line

2021-06-07 10:53 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/CategoryMgmtController.java
> +    @PostMapping(CREATE_CATEGORY_URI)
Maybe you should use the consumes and produces attributes (in every controller method)

2021-06-07 10:58 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/CategoryMgmtController.java
> +        validation.verifyName(name, origin);
If there is no particular reason for this order, maybe you should do this in the opposite order: first check the first paramter, then the second.

2021-06-07 10:59 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/DomainMgmtController.java
> +    @PostMapping(CREATE_DOMAIN_URI)
Maybe you should use the consumes and produces attributes (in every controller method)

2021-06-07 11:00 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/DomainMgmtController.java
> +        final MipDomain domain;
this can't be final

2021-06-07 11:17 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/CategoryMgmtController.java
> +        }
This is not in a transaction. If two create controller method with the same category runs in parallel threads, it is possible that the exists method return false to both, then one of the create db service method returns error because of unique constraint validation.

2021-06-07 11:19 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/DomainMgmtController.java
> +        }
this is not in a transaction

2021-06-07 11:20 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/DomainMgmtController.java
> +        validation.verifyName(name, origin);
opposite order

2021-06-07 11:23 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/EchoController.java
> +    @ApiOperation(value = "Return an echo message with the purpose of testing the core device availability", response = String.class,
core device => core service

2021-06-07 11:23 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/EchoController.java
> +    public String echoOnboarding() {
rename the method

2021-06-07 11:25 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ExecutionController.java
> +    @ApiOperation(value = "Return the Base64 encoded public key of the server as well as the SSH identity line", response = String.class,
response is NOT a String

2021-06-07 11:25 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ExecutionController.java
> +    @GetMapping(OP_MSCV_PUBLIC_KEY_URI)
Maybe you should use the consumes and produces attributes (in every controller method)

2021-06-07 11:32 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ExecutionController.java
> +    public void login(@RequestBody final TargetLoginRequest request) throws MscvException {
You should catch any exception here and throw ArrowheadException (or any derived class) instead. Alternatively, MscvException can be a child class of ArrowheadException, or you could create a ControllerAdvice to handle MscvException properly.

2021-06-07 11:36 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/DomainMgmtController.java
> +    public void delete(@PathVariable(PARAMETER_NAME) final String name) {
In CategoryMgmtController, the delete method returns with NO_CONTENT status code. This one returns with OK. Please choose one and use it everywhere.

2021-06-07 11:37 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ExecutionController.java
> +    @ApiOperation(value = "Request verification of client", response = ClientExecutionResponse.class,
The method does NOT returns with ClientExecutionResponse.

2021-06-07 11:38 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ExecutionController.java
> +            @ApiResponse(code = HttpStatus.SC_CREATED, message = EXECUTION_HTTP_201_MESSAGE, response = ClientExecutionResponse.class),
same here. Also the method returns with OK status code when there is no error, not CREATED.

2021-06-07 11:39 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ExecutionController.java
> +    //-------------------------------------------------------------------------------------------------
The method does NOT returns with ExecutionResponse.

2021-06-07 11:39 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ExecutionController.java
> +            @ApiResponse(code = HttpStatus.SC_CREATED, message = EXECUTION_HTTP_201_MESSAGE, response = ExecutionResponse.class),
same here. Also the method returns with OK status code when there is no error, not CREATED.

2021-06-07 11:42 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ExecutionController.java
> +    private String createMgmtOrigin(final String path) {
not used

2021-06-07 11:43 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/MipMgmtController.java
> +    protected static final String MIP_IDENTIFIER_DESCRIPTION = "Identifier in the form: &lt;category abbreviation&gt;-&lt;external id&gt;";
why protected?

2021-06-07 11:45 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/MipMgmtController.java
> +    private static final String READ_MIP_DESCRIPTION = "Get MSCV mip by through external id category abbreviation";
by or through?

2021-06-07 11:45 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/MipMgmtController.java
> +    private static final String UPDATE_MIP_DESCRIPTION = "Update MSCV mip through external id category abbreviation";
missing and?

2021-06-07 11:46 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/MipMgmtController.java
> +    private static final String DELETE_MIP_DESCRIPTION = "Delete MSCV mip through external id category abbreviation";
missing and?

2021-06-07 11:46 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/MipMgmtController.java
> +    @PostMapping(CREATE_MIP_URI)
Maybe you should use the consumes and produces attributes (in every controller method)

2021-06-07 11:46 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/MipMgmtController.java
> +        }
this is not one transaction.

2021-06-07 11:50 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/MipMgmtController.java
> +        validation.verifyName(categoryAbbreviation, origin);
use verifyAbbreviation instead.

2021-06-07 11:55 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/MipMgmtController.java
> +        if (Objects.nonNull(standard) || Objects.nonNull(identification)) {
the value of standard parameter is never used later

2021-06-07 11:56 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/MipMgmtController.java
> +        if (Objects.nonNull(category) || Objects.nonNull(abbreviation)) {
the value of category parameter is never used later

2021-06-07 11:57 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/MipMgmtController.java
> +    @ApiOperation(value = READ_ALL_MIP_DESCRIPTION, response = MipDto.class)
response and return value are mismatched

2021-06-07 11:58 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/MipMgmtController.java
> +        validation.verifyAbbreviation(categoryAbbreviation, origin);
verify in input parameter order

2021-06-07 12:00 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ScriptMgmtController.java
> +@RequestMapping(CommonConstants.MSCV_URI)
If this controller is for management endpoints, you should add MGMT_URI to the RequestMapping

2021-06-07 12:02 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ScriptMgmtController.java
> +                                final CoreSystemRegistrationProperties properties,
the last two parameters are never used

2021-06-07 12:03 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ScriptMgmtController.java
> +    @PostMapping(value = UPLOAD_SCRIPT_URI)
Maybe you should use the consumes and produces attributes (in every controller method)

2021-06-07 12:07 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ScriptMgmtController.java
> +    @ApiOperation(value = READ_SCRIPT_CONTENT_DESCRIPTION, response = byte[].class, tags = {CoreCommonConstants.SWAGGER_TAG_ALL, CoreCommonConstants.SWAGGER_TAG_CLIENT})
response and return value are not matched

2021-06-07 12:08 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ScriptMgmtController.java
> +    @ApiOperation(value = READ_SCRIPT_CONTENT_DESCRIPTION, response = byte[].class)
response and return value are not matched

2021-06-07 12:12 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ScriptMgmtController.java
> +            header.add("Expires", "0");
header names should be constants from HttpHeaders

2021-06-07 12:12 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ScriptMgmtController.java
> +    @ApiOperation(value = READ_ALL_SCRIPT_DESCRIPTION, response = ScriptResponseDto.class)
response and return value are not matched

2021-06-07 12:24 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/ScriptMgmtController.java
> +        outputStream = new ByteArrayOutputStream();
you should merge these into one line

2021-06-07 12:27 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/StandardMgmtController.java
> +    @PostMapping(CREATE_STANDARD_URI)
Maybe you should use the consumes and produces attributes (in every controller method)

2021-06-07 12:28 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/StandardMgmtController.java
> +        validation.verifyIdentification(identification, origin);
opposite order

2021-06-07 12:29 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/StandardMgmtController.java
> +    @ResponseStatus(org.springframework.http.HttpStatus.NO_CONTENT)
NO_CONTENT usage again.

2021-06-07 12:31 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/TargetMgmtController.java
> +    private static final String VERIFY_LOGIN_TARGET_DESCRIPTION = "Instruct MSCV to remote login to a target with a username and password";
Maybe copy-paste error? The description is the same as in the previous one

2021-06-07 12:31 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/TargetMgmtController.java
> +    @PostMapping(CREATE_TARGET_URI)
Maybe you should use the consumes and produces attributes (in every controller method)

2021-06-07 12:34 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/TargetMgmtController.java
> +    public void login(@RequestBody final TargetLoginRequest request) throws MscvException, ArrowheadException {
Somehow you have to handle MscvException (see alternatives in a previous comment)

2021-06-07 12:36 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/VerificationMgmtController.java
> +    @GetMapping(READ_VERIFICATION_URI)
Maybe you should use the consumes and produces attributes (in every controller method)

2021-06-07 12:41 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/VerificationMgmtController.java
> +            @ApiParam(value = "Filter for start date. Format: yyyy-MM-dd HH:mm:ss")
Please note that in Arrowhead 4.4.0 the date format will be changed to ISO8601. See #193 issue.

2021-06-07 12:46 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/handlers/ExecutionHandlerFactory.java
> +    private final Map<Class<?>, ExecutionHandler<?>> registrar;
maybe typo in variable name?

2021-06-07 12:50 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/handlers/ShellBasedSshExecutionHandler.java
> +    @Override
maybe add a TODO here

2021-06-07 12:51 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/handlers/ShellBasedSshExecutionHandler.java
> +
this one is not implemented yet or the implementation is empty? If the latter, maybe add some comment here (e.g. // do nothing or // intentionally blank.

2021-06-07 13:01 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/quartz/QuartzJobConfiguration.java
> +//@Configuration
delete this

2021-06-07 13:02 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/quartz/QuartzJobConfiguration.java
> +    public QuartzJobConfiguration(@Value(CoreCommonConstants.$URI_CRAWLER_INTERVAL_WD) final int schedulerInterval) {
use an independent property here

2021-06-07 13:03 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/quartz/QuartzJobConfiguration.java
> +}
rename these methods, this is not for the URI Crawler. Also, do not use the UriCrawlerTask.

2021-06-07 13:07 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/quartz/UriCrawlerTask.java
> +public class UriCrawlerTask implements Job {
delete these

2021-06-07 13:22 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/security/KeyPairFileUtilities.java
> +        } else if (publicKey.getAlgorithm().equals("DSA")) {
RSA, DSA, and BC should be constants

2021-06-07 13:23 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/security/KeyPairFileUtilities.java
> +            }
maybe close dis in a finally block if necessary

2021-06-07 13:37 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/CategoryService.java
> +    @Transactional
All DB service methods should catch any exception comes from the  DB and rethrow them as ArrowheadException (or any child), because the ControllerAdvice only handles ArrowheadExceptions. 

Please note that transaction sare rollbacked automatically only in case of unchecked exceptions (and the exception class you specify explicitly in rollbackFor attribute). So, for example, in case of a SQLException, the transaction will not rollback.

Because ArrowheadException is an unchecked exception, catching every type of exceptions and rethrowing them as ArrowheadException will solve the rollback problem. In the other core services we've explicitly specified ArrowheadException in the rollbackFor attribute, but just because it improves readability.

2021-06-07 13:46 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/CategoryService.java
> +        return repository.saveAndFlush(category);
It would be a good idea to at least trim the category name and abbreviation, before storing. Please note that changes implicate further changes in other db-related methods

2021-06-07 13:46 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/CategoryService.java
> +
Assert about not empty string

2021-06-07 13:47 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/CategoryService.java
> +
Assert about not empty string

2021-06-07 13:47 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/DomainService.java
> +    @Transactional
All DB service methods should catch any exception comes from the DB and rethrow them as ArrowheadException (or any child), because the ControllerAdvice only handles ArrowheadExceptions.

Please note that transaction sare rollbacked automatically only in case of unchecked exceptions (and the exception class you specify explicitly in rollbackFor attribute). So, for example, in case of a SQLException, the transaction will not rollback.

2021-06-07 13:48 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/DomainService.java
> +        return repository.saveAndFlush(domain);
Maybe a trim on name before storing?

2021-06-07 13:49 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/DomainService.java
> +        return repository.findByName(name);
assert about not empty string

2021-06-07 13:49 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/DomainService.java
> +
assert about not empty string

2021-06-07 13:53 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/EventHandlerListener.java
> +@RequestMapping(CommonConstants.MSCV_URI + CoreCommonConstants.MGMT_URI)
The event handler notification web service is definitely not an endpoint for manangement tool. So why do you add /mgmt to its path?

2021-06-07 13:56 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/EventHandlerListener.java
> +@RequestMapping(CommonConstants.MSCV_URI + CoreCommonConstants.MGMT_URI)
Handling events that comes from the Event Handler is not a management endpoint.

2021-06-07 13:57 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/EventHandlerListener.java
> +    public void publish(@RequestBody final EventDTO event) throws IOException, SchedulerException {
What a confusing name! You RECEIVED events via the Event Handler that is published by someone else.

2021-06-07 14:11 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvApplicationInitListener.java
> +        for (CoreSystemService coreSystemService : getRequiredCoreSystemServiceUris()) {
I just realize that you need this to subscribe events of other core systems. Still not like it. It would be better if events from core systems would be public automatically, and don't need the authorization for accessing them. 

This is a change in the Event Handler, and I have to discuss this with my collegues first. What is your opinion about this?

2021-06-07 14:12 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/EventHandlerListener.java
> +    @EventListener
It could be @PostConstruct after removing the authorization rule manipulation from ApplicationInitListener (and adding the necessary changes to the Event Handler subscribing).

2021-06-07 14:18 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/EventHandlerListener.java
> +        dto.setNotifyUri(CommonConstants.MSCV_URI + CoreCommonConstants.MGMT_URI + OP_MSCV_EVENT_CALLBACK_URI);
this shouldn't be a management endpoint

2021-06-08 07:51 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/MipService.java
> +    @Transactional
All DB service methods should catch any exception comes from the DB and rethrow them as ArrowheadException (or any child), because the ControllerAdvice only handles ArrowheadExceptions.

Please note that transaction sare rollbacked automatically only in case of unchecked exceptions (and the exception class you specify explicitly in rollbackFor attribute). So, for example, in case of a SQLException, the transaction will not rollback.

2021-06-08 07:52 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/MipService.java
> +        Assert.notNull(category, CATEGORY_NULL_ERROR_MESSAGE);
what about empty string?

2021-06-08 07:52 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/MipService.java
> +        Assert.notNull(categoryAbbreviation, CATEGORY_NULL_ERROR_MESSAGE);
what about empty string?

2021-06-08 07:52 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/MipService.java
> +        Assert.notNull(categoryAbbreviation, ABBR_EMPTY_ERROR_MESSAGE);
what about empty string?

2021-06-08 10:33 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvApplicationInitListener.java
> +        for (CoreSystemService coreSystemService : getRequiredCoreSystemServiceUris()) {
I've discussed this problem with my colleagues. The Event Handler changes are possible, but not easy, so - at least for now - we postponed them to version 5.0.

But this does not mean that your solution is good. The current solution should be that the MSCV does not care about the authorization rules. It's the system operator's responsibility to make the necessary authorization rules when the MSCV is deployed. You just make sure that the documentation contains the needed information.

2021-06-08 13:17 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/ScriptService.java
> +    @Transactional
All DB service methods should catch any exception comes from the DB and rethrow them as ArrowheadException (or any child), because the ControllerAdvice only handles ArrowheadExceptions.

Please note that transaction will rollbacked automatically only in case of unchecked exceptions (and the exception class you specify explicitly in rollbackFor attribute). So, for example, in case of a SQLException, the transaction will not rollback.

2021-06-08 13:17 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/ScriptService.java
> +        Assert.notNull(identifier, MIP_IDENTIFIER_NULL_ERROR_MESSAGE);
not empty check

2021-06-08 13:20 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/MipService.java
> +        return repository.saveAndFlush(mip);
Maybe a trim on name before storing?

2021-06-08 13:25 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/MipService.java
> +        return repository.findByExtIdAndCategoryName(extId, category);
Maybe a trim on category before querying?

2021-06-08 13:25 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/MipService.java
> +        return repository.findByCategoryAbbreviationAndExtId(categoryAbbreviation, extId);
Maybe a trim on categoryAbbreviation before querying?

2021-06-08 13:26 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/MipService.java
> +        final Optional<Mip> optionalMip = findByExternalIdAndCategoryAbbreviation(extId, categoryAbbreviation);
maybe a trim on categoryAbbreviation before querying

2021-06-08 13:27 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/ScriptService.java
> +        final Matcher matcher = Validation.MIP_IDENTIFIER_PATTERN.matcher(identifier);
maybe a trim on identifier before matching?

2021-06-08 13:29 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/ScriptService.java
> +        Assert.notNull(catAbbr, CATEGORY_NULL_ERROR_MESSAGE);
maybe check not empty? Also a trim before storing.

2021-06-08 13:32 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/ScriptService.java
> +        Assert.notNull(name, NAME_NULL_ERROR_MESSAGE);
check name not empty, and trim before querying

2021-06-08 13:34 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/ScriptService.java
> +                              .resolve(mipView.getIdentifier() + ".sh")
Is extension always sh, even on Windows?

2021-06-08 13:40 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/StandardService.java
> +    public Standard create(final Standard category) {
the parameter name shouldn't be category

All DB service methods should catch any exception comes from the DB and rethrow them as ArrowheadException (or any child), because the ControllerAdvice only handles ArrowheadExceptions.

Please note that transaction will rollbacked automatically only in case of unchecked exceptions (and the exception class you specify explicitly in rollbackFor attribute). So, for example, in case of a SQLException, the transaction will not rollback.

2021-06-08 13:40 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/StandardService.java
> +        Assert.notNull(category, CATEGORY_NULL_ERROR_MESSAGE);
incorrect erro message

2021-06-08 13:41 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/StandardService.java
> +        return repository.saveAndFlush(category);
maybe trim standard's identification and name fields before storing?

2021-06-08 13:41 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/StandardService.java
> +        Assert.notNull(identification, STANDARD_NULL_ERROR_MESSAGE);
check not empty

2021-06-08 13:42 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/StandardService.java
> +        Assert.notNull(identification, STANDARD_NULL_ERROR_MESSAGE);
check for not empty and maybe a trim before querying

2021-06-08 13:44 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/TargetService.java
> +    @Transactional
All DB service methods should catch any exception comes from the DB and rethrow them as ArrowheadException (or any child), because the ControllerAdvice only handles ArrowheadExceptions.

Please note that transaction will rollbacked automatically only in case of unchecked exceptions (and the exception class you specify explicitly in rollbackFor attribute). So, for example, in case of a SQLException, the transaction will not rollback.

2021-06-08 13:46 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/TargetService.java
> +        return targetRepo.saveAndFlush(sshTarget);
maybe trim name before storing

2021-06-08 13:51 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/VerificationExecutionService.java
> +    @Transactional
All DB service methods should catch any exception comes from the DB and rethrow them as ArrowheadException (or any child), because the ControllerAdvice only handles ArrowheadExceptions.

Please note that transaction will rollbacked automatically only in case of unchecked exceptions (and the exception class you specify explicitly in rollbackFor attribute). So, for example, in case of a SQLException, the transaction will not rollback.

2021-06-08 13:54 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/VerificationExecutionService.java
> +                                                                    DetailSuccessIndicator.NOT_APPLICABLE, null);
both branch create an entry with NOT_APPLICABLE. Maybe in the first branch you want to use something else? Maybe IN_PROGRESS?

2021-06-08 13:56 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/VerificationService.java
> +        Assert.notNull(name, NAME_NULL_ERROR_MESSAGE);
not empty check and maybe a trim

2021-06-08 14:11 UTC, rbocsi commented on scripts/create_arrowhead_tables.sql
> +use arrowhead;
unnecessary line

2021-06-08 14:12 UTC, rbocsi commented on scripts/mscv_privileges.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`authorization_intra_cloud` TO 'mscv'@'localhost';
seems unlikely that MSCV uses these tables

2021-06-08 14:13 UTC, rbocsi commented on scripts/mscv_privileges.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`authorization_intra_cloud` TO 'mscv'@'%';
seems unlikely that MSCV uses these tables

2021-06-08 14:17 UTC, rbocsi requested changes
I wrote a lot of comments inline. Please take them into consideration.

2021-08-11 09:19 UTC, mzsilak commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/ScriptService.java
> +                              .resolve(mipView.getIdentifier() + ".sh")
currently only Linux like systems are supported

2021-08-11 12:03 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Mip.java
> +public class Mip {
I agree that the name MIP will not be understandable for anyone not familiar with the MSCV framework. However, I am not sure if the full name helps on this matter. I see the risk that it only makes the classnames more cluttered for MipCategory and MipDomain. 
I will add a comment at the top of the class with the following:

> Measurable Indicator Points are extracted from existing standards and guidelines to address 
 requirements. The MIPs are executed through target operating system specific Scripts. The results of all executions determine the compliance of a device/system/service to a specific standard.

> See also: "Security Safety and Organizational Standard Compliance in Cyber Physical Systems" from Ani Bicaku et. al.

2021-08-11 12:27 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Mip.java
> +    private Long id;
The id is null before the entity is persisted the first time to the database. With a primitive type the id would have the value '0' and I would need to rely on the functionality of @GeneratedValue to assign the correct value. If that functionality fails for whatever reason, the issue wouldn't be detected immediately with a primitive type as the value '0' is valid from database point of view.

2021-08-11 12:30 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/SshTarget.java
> +    private String authInfo;
Yes, it is the public key of the SSH server.

2021-08-11 12:49 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/database/view/mscv/MipViewImpl.java
> +public class MipViewImpl implements MipView {
You are right that it is not _needed_, however I was unhappy with one of the behaviors of the Spring generated implementation and decided to provide an implementation myself.

2021-08-11 12:59 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/ClientExecutionRequest.java
> +    private Layer layer;
While that is true, the enum value allows Swagger to show only possible/valid values in the GUI without additional input.

2021-08-11 13:40 UTC, mzsilak commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvApplicationInitListener.java
> +        for (CoreSystemService coreSystemService : getRequiredCoreSystemServiceUris()) {
Currently the authorization rules are mandatory if MSCV is to be used. I don't like to have an operator have to add this rules manually as there is no way around this. Why add manual tasks if it can be (and already is) automated? Once the event handler changes, we can remove the authorization rule management.

2021-08-12 09:26 UTC, mzsilak commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/CategoryMgmtController.java
> +        }
I am not sure if a simple db transaction prevents this issue, unless maybe if we fine tune it for serialized isolation of a transaction.

2021-08-12 14:27 UTC, mzsilak commented on mscv/src/main/java/eu/arrowhead/core/mscv/handlers/ExecutionHandlerFactory.java
> +    private final Map<Class<?>, ExecutionHandler<?>> registrar;
Should be the correct word but it could be changed.

2021-08-17 08:24 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Mip.java
> +    private Long id;
We talked about this issue in slack. Please ignore all 'use primitive whenever you can' comments.

2021-08-17 08:25 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/mscv/Mip.java
> +public class Mip {
I think a comment would help a lot.

2021-08-17 08:26 UTC, mzsilak commented
Hello @rbocsi,

I don't agree with your comments regarding using primitives for non-nullable database entities.

I use objects so I can be sure that any set value is intended. If I would use primitives it would not be possible to check for null, but I would need to check for the default values instead.
Checking needs to be done anyway, but if there is a path where its missing now, the database would complain and that is good. With primitives, if there is a path where the check is missing, it would accept the faulty value.  

I could also add a validation annotation on the entity so that the JPA provider performs additional checks, but at that point I don't see the advantages of primitives over the current implementation.

What are your thoughts about this?

2021-08-17 08:30 UTC, rbocsi commented
I am convinced. Please feel free to ignore all 'use primitives' comments.

2021-11-09 12:34 UTC, tsvetlin commented
Hello @mzsilak!

What is the status of the PR? Are all the issue fixed? Do you need a new review?

2021-11-09 14:31 UTC, mzsilak commented
All issues should be fixed. Another review can be done for QA.

2021-11-09 16:09 UTC, tsvetlin commented
Could you please resolve the merge conflicts here too @mzsilak. We will do the review after. Thank you

2021-11-17 12:52 UTC, tsvetlin commented
Bump!

Could you please resolve the merge conflicts here too @mzsilak. We will do the review after. Thank you

2021-12-21 20:20 UTC, mzsilak commented
@tsvetlin This PR can be merged as well

2022-01-03 15:05 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvApplicationInitListener.java
> +    protected List<CoreSystemService> getRequiredCoreSystemServiceUris() {
after the merge, there are errors here.

2022-01-03 15:06 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/security/MscvAccessControlFilter.java
> +                    checkIfClientIsAnAllowedCoreSystem(clientCN, cloudCN, new CoreSystem[]{CoreSystem.EVENT_HANDLER}, requestTarget);
after the merge, there is an error here

2022-01-04 09:16 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/CategoryDto.java
> +public class CategoryDto implements Serializable {
still not resolved, 1L is not a useful serialVersionUID

2022-01-04 09:17 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/CategoryListResponseDto.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:17 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/ClientExecutionRequest.java
> +public class ClientExecutionRequest implements Serializable {
still not resolved, 1L is not a useful serialVersionUID

2022-01-04 09:18 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/ClientExecutionRequest.java
> +    private Layer layer;
ok

2022-01-04 09:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/DomainDto.java
> +public class DomainDto implements Serializable {
still not resolved, 1L is not a useful serialVersionUID

2022-01-04 09:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/DomainListResponseDto.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:20 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/ExecutionRequest.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:21 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/MipDto.java
> +public class MipDto implements Serializable {
still not resolved, 1L is not a useful serialVersionUID

You should add the comment here too that describes what a MIP is

2022-01-04 09:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/MipIdentifierDto.java
> +public class MipIdentifierDto implements Serializable {
still not resolved, 1L is not a useful serialVersionUID

2022-01-04 09:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/MipListResponseDto.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/MipVerificationResultDto.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:23 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/PaginationResponse.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:24 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/PublicKeyResponse.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:24 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/ScriptListResponseDto.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:31 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/ScriptRequestDto.java
> +public class ScriptRequestDto implements Serializable {
still not resolved, 1L is not a useful serialVersionUID

2022-01-04 09:31 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/ScriptResponseDto.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:32 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/SshTargetDto.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:32 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/StandardDto.java
> +public class StandardDto implements Serializable {
still not resolved, 1L is not a useful serialVersionUID

2022-01-04 09:32 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/StandardListResponseDto.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:33 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/TargetDto.java
> +public class TargetDto implements Serializable {
still not resolved, 1L is not a useful serialVersionUID

2022-01-04 09:34 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/TargetListResponseDto.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:35 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/TargetLoginRequest.java
> +public class TargetLoginRequest implements Serializable {
still not resolved, 1L is not a useful serialVersionUID

2022-01-04 09:35 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/VerificationResultDto.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:35 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/VerificationResultListResponseDto.java
> +    private static final long serialVersionUID = 1L;
1L is not a useful serialVersionUID

2022-01-04 09:36 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/quartz/QuartzUtilities.java
> +        return deleteJob(context.getScheduler(), context.getJobDetail());
still not resolved

2022-01-04 09:44 UTC, rbocsi commented on mscv/src/deb/arrowhead-mscv.service
> +ExecStart=/usr/bin/java -Dlog4j.configurationFile=file:/etc/arrowhead/systems/mscv/log4j2.xml -jar /usr/share/arrowhead/mscv/mscv.jar
wrong jar name, it should be arrowhead-mscv.jar

2022-01-04 09:46 UTC, rbocsi commented on mscv/src/deb/control/postrm
> +		    rmdir ${AH_SYSTEMS_DIR}/sysop 2>/dev/null || true
don't delete sysop directory here

2022-01-04 10:44 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/CategoryMgmtController.java
> +    @PostMapping(CREATE_CATEGORY_URI)
still unresolved

2022-01-04 10:46 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/DomainMgmtController.java
> +    @PostMapping(CREATE_DOMAIN_URI)
still unresolved

2022-01-04 10:52 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/controller/EchoController.java
> +        consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
This is just plain wrong here: echo consumes nothing and produces a plain string (plain/text). This cause broken test in
MsvcControllerTest

2022-01-04 13:25 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/handlers/SshExecutionHandler.java
> +    @Override
Transaction?

2022-01-04 13:41 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/ScriptService.java
> +            // TODO oldScript.setPhysicalPath(newScript.getPhysicalPath());
implement or remove

2022-01-04 13:44 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/ScriptService.java
> +    @Transactional(readOnly = true)
I think Transaction annotation does not work on protected (or private) method. Make this method public or annotate the caller public method.

2022-01-04 13:44 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/ScriptService.java
> +    @Transactional(readOnly = true)
I think Transaction annotation does not work on protected (or private) method. Make this method public or annotate the caller public method.

2022-01-04 13:46 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/service/TargetService.java
> +    @Transactional(readOnly = true)
I think Transaction annotation does not work on protected (or private) method. Make this method public or annotate the caller public method.

2022-01-04 13:49 UTC, rbocsi commented on mscv/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +      "type": "java.lang.String",
java.lang.Integer

2022-01-04 13:50 UTC, rbocsi commented on mscv/src/main/resources/application.properties
> +server.address=127.0.0.1
0.0.0.0

2022-01-04 13:52 UTC, rbocsi commented on mscv/src/test/java/eu/arrowhead/core/mscv/MsvcControllerTest.java
> +    public void echoMsvc() throws Exception {
This test is broken. (Echo does not return JSON)

2022-01-04 13:56 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/database/service/SystemRegistryDBService.java
> +                                                              system.getAuthenticationInfo());
After the merge, this is an error. Try this:

```
            final var systemRequestDTO = new SystemRequestDTO(system.getSystemName(),
                                                              system.getAddress(),
                                                              system.getPort(),
                                                              system.getAuthenticationInfo(),
                                                              Utilities.text2Map(system.getMetadata()));
```

2022-01-04 13:59 UTC, rbocsi commented on systemregistry/src/main/java/eu/arrowhead/core/systemregistry/database/service/SystemRegistryDBService.java
> +                                   final CertificateAuthorityDriver caDriver,
after the merge, there is a syntax error here (the constructor signature ends twice, there is a duplicate input parameter, etc).

2022-01-04 14:01 UTC, rbocsi requested changes
I found some issues (new ones and some old ones that remained unresolved). There are syntax errors in the code after the merge and a broken unit test.

2022-03-06 22:25 UTC, mzsilak commented on mscv/src/main/java/eu/arrowhead/core/mscv/handlers/SshExecutionHandler.java
> +    @Override
The method itself doesn't do database operations, but submits a runnable.

2022-03-06 22:31 UTC, mzsilak commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/mscv/VerificationResultListResponseDto.java
> +    private static final long serialVersionUID = 1L;
I would argue it is as useful as any other (including randomly generated) serialVersionUID.

2022-03-07 09:40 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/MscvApplicationInitListener.java
> +        httpService.sendRequest(authMgmtUri, HttpMethod.POST, AuthorizationIntraCloudListResponseDTO.class, authRequest);
Only works if Auth is up and running. If they are initializing in the same time (for example when a computer automatically starts them at boot). What was the problem with the previous version (multiple tries)?

2022-03-07 09:51 UTC, rbocsi commented on mscv/src/main/java/eu/arrowhead/core/mscv/handlers/SshExecutionHandler.java
> +    @Override
```
           } finally {
                executionDetailRepo.saveAll(detailList);
                executionDetailRepo.flush();
                executionRepo.saveAndFlush(execution);
                logger.info("Finished verification of {} with result: {}", execution.getTarget(), execution.getResult());
            }
```
This seems database operation to me. I get that this method is doing anything DB-related, but the runnable does on multiple repositories. So a transaction is necessary inside the runnable.

2022-03-07 10:19 UTC, rbocsi requested changes
There are still `@Transactional` annotations on protected method, for example in VerificationService.

You still need to handle transaction somehow in SshExecutionHandler.

2022-06-23 08:22 UTC, merged