Integrate configuration manager
eclipse-arrowhead/core-java-spring pull request #318
Opened 2021-06-07 14:19 UTC by LuLeRoemer

This commit integrates a wrapper to integrate the Arrowhead Framework with Eclipse hawkBit.

Signed-off-by: Lukas Römer <lukas.roemer@bosch.io>

2021-06-07 14:34 UTC, jerkerdelsing commented
Very glad to see this commit. @tsvetlin  will you and your team check run the Ci/CD process here.

2021-06-09 09:42 UTC, rbocsi commented on README.md
> +# Configuration Manager
The name of this project should contain the HawkBit word (maybe configuration-hawkbit or configuration-manager-hawkbit), because we already have a configuration (see pull requests) system, and we should avoid confusion as much as possible.

2021-06-09 09:43 UTC, rbocsi commented on configuration-manager/Dockerfile
> +ARG JAR_FILE=target/arrowhead-configuration-manager-4.3.0.jar
The jar name comes from the project name so this should change too.

2021-06-09 09:47 UTC, rbocsi commented on configuration-manager/README.md
> +- `CLIENT_ID` - this is the ID/name of the core system (should comply with the Arrowhead CN naming conventions, e.g.: `configuration`)
The example here is problematic as we have a configuration system with the same CN. Please change the example, maybe to hawkbitconfiguration.

2021-06-09 09:54 UTC, rbocsi commented on configuration-manager/README.md
> +The configuration manager uses a client certificate to connect to the Arrowhead Authorization system in order to retrieve the public key that is used to sign JWTs.
Every core system should comes with working certificates for testing/trial purposes. So, we need

- a certificate in testcloud2.aitia.arrowhead.eu cloud (hawkbitconfiguration.testcloud2.aitia.arrowhead.eu) in src/main/resources/certificates folder
- a truststore that contains the testcloud2.aitia.arrowhead.eu entry in the same folder
- the property files should uses these files by default
- a copy of the above-mentioned system certificate should appear in the core-java-spring/certificates/testcloud2 folder
- a certificate in testcloud1.aitia.arrowhead.eu cloud (hawkbitconfiguration.testcloud1.aitia.arrowhead.eu) in core-java-spring/certificates/testcloud1 folder
- the password for every file is 123456

These are necessary for making a trial as easy as possible.

2021-06-09 09:56 UTC, rbocsi commented on configuration-manager/certificates/generate-certificates.sh
> +CLIENT_ID="configuration"
change this to maybe hawkbitconfiguration

2021-06-09 09:58 UTC, rbocsi commented on configuration-manager/pom.xml
> +	<artifactId>arrowhead-configuration-manager</artifactId>
change the artifact id to something less confusing, maybe arrowhead-configuration-manager-hawkbit

2021-06-09 10:01 UTC, rbocsi commented on configuration-manager/pom.xml
> +			</plugin>
You need to create a debian installer as well. You can use the jdeb maven plugin to do that. There is a plenty of example in other core systems.

2021-06-09 11:27 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/arrowhead/ArrowheadAuthorizationSystemClient.java
> +    public String getPublicKey() throws WebClientResponseException {
This is correct for Arrowhead 4.3.0.

But, from Arrowhead 4.4.0 will be wrong, because in that version the webservice returns a valid JSON (see issue  #276), so the return value will be something like this: "public-key-characters". The quotes are part of the return value.

2021-06-09 11:32 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/Initialization.java
> +            this.arrowheadServiceRegistryClient.registerService(requestDTO);
This system should unregister its service at graceful shutdown.

2021-06-09 11:33 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/Initialization.java
> +                log.warn("Own system is already registered in Arrowhead");
This system should unregister its service here (because it couldn't unregister at shutdown), then try registering again.

2021-06-09 11:33 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/arrowhead/ArrowheadServiceRegistryClient.java
> +
should provide support for unregister too

2021-06-09 11:36 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/arrowhead/model/response/ServiceDefinitionResponseDTO.java
> +    private Long id;
can be primitive long

2021-06-09 11:36 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/arrowhead/model/response/ServiceInterfaceResponseDTO.java
> +    private Long id;
can be primitive long

2021-06-09 11:37 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/arrowhead/model/response/ServiceRegistryResponseDTO.java
> +    private Long id;
can be primitive long

2021-06-09 11:37 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/arrowhead/model/response/ServiceRegistryResponseDTO.java
> +    private Integer version;
can be int

2021-06-09 11:38 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/arrowhead/model/response/SystemResponseDTO.java
> +    private Long id;
can be primitive long

2021-06-09 11:38 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/arrowhead/model/response/SystemResponseDTO.java
> +    private Integer port;
can be int

2021-06-09 11:41 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/config/ArrowheadConfig.java
> +    private Integer authorizationSystemPort;
these 3 value shouldn't be come from a hard-coded property. Instead, you should query the Service Registry for auth-public-key service, and you should read these information from the response.

2021-06-09 12:13 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/hawkbit/HawkbitDmfConsumer.java
> +            log.info("Received message");
maybe log.debug(). The static "Received message" log message does not contain too much information in production code.

2021-06-09 12:24 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/hawkbit/HawkbitDmfOutboundClient.java
> +                .contentType("application/json")
application/json should be a constant, not a string literal.

2021-06-09 12:31 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/hawkbit/model/outbound/ThingCreatedOutboundMessage.java
> +            if (this.type != null) headers.put(MessageHeader.TYPE.toString(), this.type);
it is not a good practice to omit braces even if Java allows it.

2021-06-09 12:35 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/properties/SystemProperties.java
> +    private String address;
You use this when register this system's service into Arrowhead. In Service Registry, the address never contains the protocol, only the IP or DNS name.

2021-06-09 12:36 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/properties/SystemProperties.java
> +     * This is the port of the configuration system itself, e.g. 8445.
8445 is the default port of Authorization system, so maybe not the best example. You should use this system default port which is 8447 I think.

2021-06-09 12:41 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/security/JwtAuthenticationFilter.java
> +            PublicKey authorizationSystemPublicKey = loadPublicKeyFromString(authorizationSystemPublicKeyString);
maybe you should do this once

2021-06-10 08:45 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/service/HawkbitService.java
> +        UpdateActionStatusOutboundMessage message = UpdateActionStatusOutboundMessage.builder()
maybe null check on input param

2021-06-10 08:47 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/service/HawkbitService.java
> +                        .tenant("DEFAULT").build())
I'm not familiar with Hawkbit, but you have a hawkbitTenant variable. Don't you want to use that instead of the hard coded DEFAULT?

2021-06-10 08:56 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/websocket/WebsocketSender.java
> +public class WebsocketSender {
camelCase error in class name: WebsocketSender => WebSocketSender

2021-06-10 08:57 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/websocket/WebsocketSender.java
> +        TextMessage wsMessage = new TextMessage(body);
maybe you can move these lines inside the if branch.

2021-06-10 09:00 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +# Listens on port 8443 and loads its certificate from the truststore
Comment and value contains different ports. Also, 8443 is the default port of Service Registry.

2021-06-10 09:01 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +        key-store-password: password
should contains valid values for testing and trial

2021-06-10 09:02 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +    # This is the address of the configuration system itself, e.g. "https://192.168.1.1" or "https://subdomain.domain.tld"
address should not contain the protocol, just the IP or domain name

2021-06-10 09:03 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +    # This is the port of the configuration system itself, e.g. 8445
8445 is the default port the Authorization core system, so maybe you should find a different example (e. g. 8447)

2021-06-10 09:04 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +    # This is the name of the configuration system itself, e.g. "conf-system". In the context of Arrowhead the system
As there is an other configuration system in Arrowhead, you should choose a different name (and a different example), maybe hawkbitconfiguration

2021-06-10 09:05 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +    providedServiceDefinition:
should contain a default for trial

2021-06-10 09:05 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +    password: password
should contain valid values for testing and trial

2021-06-10 09:06 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +    password: password
should contain valid values for testing and trial

2021-06-10 09:08 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +    alias: "configuration.example.corp.arrowhead.eu"
please change the alias because we already have a configuration system. In this section you should use the hawkbitconfiguration.p12 file that contains the hawkbitconfiguration.testcloud2.aitia.arrowhead.eu certificate with password 123456. Alias should be hawkbitconfiguration.testcloud2.aitia.arrowhead.eu (or just hawkbitconfiguration).

2021-06-10 09:09 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +    port:
This is not the correct way to use Authorization system.

2021-06-10 09:09 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +    port:
should contain 127.0.0.1 and 8443 for default

2021-06-10 09:10 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +    password:
should contain some default values

2021-06-10 09:12 UTC, rbocsi commented on configuration-manager/src/main/resources/log4j2.xml
> +    <Appenders>
should contain FileAppender too

2021-06-10 10:45 UTC, rbocsi commented on configuration-manager/src/test/java/eu/arrowhead/core/confmgr/arrowhead/ArrowheadAuthorizationSystemClientTest.java
> +                .setBody("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvmaFymz4cSB+LP3pixhhgrczq8G2rWTMyyajMQNSXOuvGDBhB7S32rl/+B8VUvTrYBx7ab8AM/TxrDwWAzsQ3p3oo0+5NNibHpZ8QucWIXqbpQqFobiNWx+ogoBLV4UfJ
Please note that after 4.4.0 this one will be wrong. After that content type should be application/json, and the body should contains double quotes.

2021-06-10 10:47 UTC, rbocsi commented on configuration-manager/src/test/java/eu/arrowhead/core/confmgr/arrowhead/ArrowheadServiceRegistryClientTest.java
> +    public void givenServiceIsNotRegistered_whenRegisterService_thenServiceIsRegistered() throws Exception {
Please note that in 4.4.0 this will be wrong. Because of issue #193 we change the input/output date format (e. g. 2020-03-18T22:13:32.143Z) in JSONs.

2021-06-10 11:48 UTC, rbocsi commented on configuration-manager/src/test/java/eu/arrowhead/core/confmgr/arrowhead/ArrowheadServiceRegistryClientTest.java
> +    public void givenSystemRequestDTOIsInvalid_whenRegisterService_thenConstraintViolationExceptionIsThrown() throws Exception {
This test is failed in my environment (among some others).

```
Expecting throwable message:
  <"interfaces: nem lehet üres, serviceUri: nem lehet null, providerSystem: nem lehet null, serviceDefinition: nem lehet null">
to contain:
  <"providerSystem: must not be null">
but did not.

"nem lehet null" is "must not be null" in Hungarian. The validator you use generates localized error messages (who thinked that this is a good idea).
```

2021-06-10 12:18 UTC, rbocsi commented on configuration-manager/src/test/java/eu/arrowhead/core/confmgr/arrowhead/ArrowheadServiceRegistryClientTest.java
> +    public void givenSystemRequestDTOIsInvalid_whenRegisterService_thenConstraintViolationExceptionIsThrown() throws Exception {
Adding this snippet to the test fixes for me:
```
    private static Locale defaultLocale;
	
	@BeforeAll
	public static void setUp()  {
		defaultLocale = Locale.getDefault();
		Locale.setDefault(Locale.UK);
	}
	
	@AfterAll
	public static void tearDown() {
		Locale.setDefault(defaultLocale);
	}
```

But maybe there is a more elegant solution

2021-06-10 12:43 UTC, rbocsi commented on configuration-manager/src/test/resources/application-test.yml
> +    port: 8443
port should change to 8447

2021-06-10 12:44 UTC, rbocsi commented on configuration-manager/src/test/resources/application-test.yml
> +    # This is the address of the configuration system itself, e.g. "https://192.168.1.1" or "https://subdomain.domain.tld"
this comment is incorrect. There is no protocol in address.

2021-06-10 12:49 UTC, rbocsi requested changes
I've looked into your code and made some comments (see inline). Please take them into consideration.

2021-08-31 15:22 UTC, LuLeRoemer commented on configuration-manager/src/test/java/eu/arrowhead/core/confmgr/arrowhead/ArrowheadServiceRegistryClientTest.java
> +    public void givenSystemRequestDTOIsInvalid_whenRegisterService_thenConstraintViolationExceptionIsThrown() throws Exception {
I will adjust the Test class as proposed.

2021-08-31 15:39 UTC, LuLeRoemer commented on configuration-manager/src/test/java/eu/arrowhead/core/confmgr/arrowhead/ArrowheadAuthorizationSystemClientTest.java
> +                .setBody("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvmaFymz4cSB+LP3pixhhgrczq8G2rWTMyyajMQNSXOuvGDBhB7S32rl/+B8VUvTrYBx7ab8AM/TxrDwWAzsQ3p3oo0+5NNibHpZ8QucWIXqbpQqFobiNWx+ogoBLV4UfJ
Can you please tell how the payload looks exactly? Like this?
```
{
    "publicKey": "key"
}
```

2021-08-31 15:43 UTC, LuLeRoemer commented on configuration-manager/src/main/resources/application.yml
> +    port:
What exactly do you mean?

2021-09-01 12:16 UTC, LuLeRoemer commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/security/JwtAuthenticationFilter.java
> +            PublicKey authorizationSystemPublicKey = loadPublicKeyFromString(authorizationSystemPublicKeyString);
Yes, you are right. We also want to cache the request to the authorization system to acquire the public key. However, we plan to do that as part of the next version.

2021-09-01 15:19 UTC, LuLeRoemer commented on configuration-manager/pom.xml
> +			</plugin>
Could you please explain why this is necessary? As the configuration manager only works together with HawkBit I don't see an advantage in providing a debian installer, unless we package a self-contained installer including HawkBit. However, that doesn't really make sense as we want to be able keep the possibility of deploying both applications separately.

2021-09-01 15:37 UTC, LuLeRoemer commented on README.md
> +# Configuration Manager
Ok, I renamed it in HawkBit Configuration Manager (hawkbit-configuration-manager)

2021-09-03 08:46 UTC, rbocsi commented on configuration-manager/pom.xml
> +			</plugin>
In the Arrowhead Framework project we provide 3 way to install a framework (as you can see in the Readme),

1. One can use docker images,
2. one can use Debian installer,
3. or compile from the source

So, you have to provide a debian installer. Please note that none of the installers installs the "weak" dependencies (like Java JRE, MySQL or activeMQ server, etc) they want to use, so you don't have to install the HawkBit during the deployment of the Arrowhead System. Such dependencies should be mentioned in the documentation as requirements.

But this doesn't mean that the Debian installer does nothing. For example, the installer of Authorization system does a lot of things:

- asks the location of the database and make possible to specify a password
- in Authorized installation mode (add system to an existing cloud), it asks path of the cloud certificate
- in Detached installation mode (creating a stand-alone, isolated cloud), it asks the name and operator of the cloud
- make possible to specify Subject Alternative Names (SANs) for the certificate
- connects to the database and creates a MySQL user for the system, and adds the necessary privileges to it
- generates certificates (in Authorized mode: a system certificate and a trust store, in Detached mode: a master, a cloud and a system certificate and a trust store)
- modifies the configuration file with the previously mentioned information (DB location and password, SR location, certificates location)
- copy the necessary files into their standard locations: JAR file into the usr/share/arrowhead/authorization directory, config files and certificates into the /ect/arrowhead/systems/authorization directory, service file into the /etc/systemd/system directory, etc.
- creates symbolic links
- starts the system and make sure that the system is automatically started whenever the computer reboots

Your system does not use the MySQL database if I remember right, so you can skip that. But all the others are needed. Furthermore, your installer should ask the location and access information of the HawkBit and use that data to modify the configuration file accordingly. The goal is that after the installer is finished your system is able to start and work properly IF its dependencies (the HawkBit in your case) are running WITHOUT the need to manually modifying the configuration file.

2021-09-03 08:49 UTC, rbocsi commented on configuration-manager/src/main/java/eu/arrowhead/core/confmgr/security/JwtAuthenticationFilter.java
> +            PublicKey authorizationSystemPublicKey = loadPublicKeyFromString(authorizationSystemPublicKeyString);
ok. Then I suggest to add a TODO comment here about the future plans

2021-09-03 08:54 UTC, rbocsi commented on configuration-manager/src/main/resources/application.yml
> +    port:
The access information to the authorization system shouldn't come from the configuration file. You should ask the Service Registry instead. The access information of the Service Registry is already in the configuration file (currently there is no other way to discover the Service Registry), so you can use that information to query the Service Registry about the authorization's specified services (like the public-key service).

2021-09-03 09:01 UTC, rbocsi commented on configuration-manager/src/test/java/eu/arrowhead/core/confmgr/arrowhead/ArrowheadAuthorizationSystemClientTest.java
> +                .setBody("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvmaFymz4cSB+LP3pixhhgrczq8G2rWTMyyajMQNSXOuvGDBhB7S32rl/+B8VUvTrYBx7ab8AM/TxrDwWAzsQ3p3oo0+5NNibHpZ8QucWIXqbpQqFobiNWx+ogoBLV4UfJ
No. The result will be this
`"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvmaFymz4cSB+LP3pixhhgrczq8G2rWTMyyajMQNSXOuvGDBhB7S32rl/+B8VUvTrYBx7ab8AM/TxrDwWAzsQ3p3oo0+5NNibHpZ8QucWIXqbpQqFobiNWx+ogoBLV4UfJekxXYH54QrTdwkvlOFXxjkL11uwBKEsZ0TzKgGaRs+iR80sjDeicnpPlMm0RbpXjx10OzmjqfC1Wrusyl2gjsW9ySfwJ1461n6cPndn8csvC37IHdHpkKTRlcDDPG6/GN3+vfUeznA7zGFWv2IOTzsuruehXaOuDNgekvREK3Xh4BpvGTZ6oEFVmr5853U3PS6ExKlvwR8NwFiPXI9LAQIDAQAB"`
instead of 
`MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvmaFymz4cSB+LP3pixhhgrczq8G2rWTMyyajMQNSXOuvGDBhB7S32rl/+B8VUvTrYBx7ab8AM/TxrDwWAzsQ3p3oo0+5NNibHpZ8QucWIXqbpQqFobiNWx+ogoBLV4UfJekxXYH54QrTdwkvlOFXxjkL11uwBKEsZ0TzKgGaRs+iR80sjDeicnpPlMm0RbpXjx10OzmjqfC1Wrusyl2gjsW9ySfwJ1461n6cPndn8csvC37IHdHpkKTRlcDDPG6/GN3+vfUeznA7zGFWv2IOTzsuruehXaOuDNgekvREK3Xh4BpvGTZ6oEFVmr5853U3PS6ExKlvwR8NwFiPXI9LAQIDAQAB`

The only difference that the answer contains double quotes too (because in a JSON every string is qouted). And, of course, the content type is application/json.

So, you code should be something like this:
```
mockWebServer.enqueue(new MockResponse()
.setResponseCode(200)
.addHeader("Content-Type", "application/json")
.setBody("\"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvmaFymz4cSB+LP3pixhhgrczq8G2rWTMyyajMQNSXOuvGDBhB7S32rl/+B8VUvTrYBx7ab8AM/TxrDwWAzsQ3p3oo0+5NNibHpZ8QucWIXqbpQqFobiNWx+ogoBLV4UfJekxXYH54QrTdwkvlOFXxjkL11uwBKEsZ0TzKgGaRs+iR80sjDeicnpPlMm0RbpXjx10OzmjqfC1Wrusyl2gjsW9ySfwJ1461n6cPndn8csvC37IHdHpkKTRlcDDPG6/GN3+vfUeznA7zGFWv2IOTzsuruehXaOuDNgekvREK3Xh4BpvGTZ6oEFVmr5853U3PS6ExKlvwR8NwFiPXI9LAQIDAQAB\""));
```

2021-12-08 09:41 UTC, closed without merging