Timemanager
eclipse-arrowhead/core-java-spring pull request #327
Opened 2021-07-16 09:59 UTC by jenseliasson

Added the TimeManager support core system

2021-07-19 07:03 UTC, jerkerdelsing commented
@jenseliasson Please fix the ECA point, see above.
@jenseliasson Can you provide the latest documentation enabling me to make a SysML model of the TimeManager.

2021-07-20 11:34 UTC, jenseliasson commented
Documentation updated and added. The ECA is fixed during the merge.

2021-07-23 11:41 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +    public static SSLSocketFactory getSslSocketFactory(final String caCrtFile, final String crtFile, final String keyFile, final String password)
Why static if this is a Spring component? Or, why is this a component if only have one public static method?

2021-07-23 11:44 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              JcaPEMKeyConverter converter = new JcaPEMKeyConverter().setProvider("BC");
use constants instead of string literals

2021-07-23 11:44 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +                     converter = new JcaPEMKeyConverter().setProvider("BC");
use constants instead of string literals

2021-07-23 11:44 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              certConverter.setProvider("BC");
use constants instead of string literals

2021-07-23 11:44 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              caKs.setCertificateEntry("ca-certificate", certConverter.getCertificate(caCert));
use constants instead of string literals

2021-07-23 11:44 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              ks.setCertificateEntry("certificate", certConverter.getCertificate(cert));
use constants instead of string literals

2021-07-23 11:44 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              ks.setKeyEntry("private-key", key.getPrivate(), password.toCharArray(), new java.security.cert.Certificate[]{certConverter.getCertificate(cert)});
use constants instead of string literals

2021-07-23 11:44 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              SSLContext context = SSLContext.getInstance("TLSv1.3");
use constants instead of string literals

2021-07-23 11:45 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              return context.getSocketFactory();
you should close resources in case of exceptions too (parser, for example)

2021-07-23 11:46 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/TimeManagerTimeResponseDTO.java
> +        private long epoch_ms;
use camelCase

2021-07-23 11:52 UTC, rbocsi commented on scripts/start_coresystems.bat
> +START "" /B "cmd /c javaw -jar arrowhead-timemanager-4.1.3.jar > sout_timemanager.log 2>&1"
should use the %version% instead of hard-coded 4.1.3

2021-07-23 11:55 UTC, rbocsi commented on timemanager/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_timemanager || true
To make this work, you should add a mysql_password_timemanager field into the templates file located in /core-common/src/deb/control folder.

2021-07-23 11:58 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerController.java
> +package eu.arrowhead.core.timeamanager;
typo in package name. I think this should be eu.arrowhead.core.timemanager

2021-07-23 12:00 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
> +    TimeWSHandler timeWSHandler;
should be private

2021-07-23 12:00 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
> +    TimeManagerDriver timeManagerDriver;
should be private

2021-07-23 12:01 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
> +                        attributes.put("CN", CN);
should use constants instead of string literals

2021-07-23 12:02 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
> +                attributes.put("serviceId", serviceId);
should use constants instead of string literals

2021-07-23 12:02 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeWSHandler.java
> +    TimeManagerDriver timeManagerDriver;
should be private

2021-07-23 12:03 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeWSHandler.java
> +                TextMessage msg = new TextMessage(Utilities.toJson(response).getBytes("UTF-8"));
should use constants instead of string literals

2021-07-23 12:04 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/database/service/TimeManagerDBService.java
> +public class TimeManagerDBService {
why is this here? Time manager core service does not even use DB except for logging.

2021-07-23 12:06 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/security/TimemanagerAccessControlFilter.java
> +        //checkIfRequesterSystemNameisEqualsWithClientNameFromCN(requestTargetSystemName, clientCN);
unnecessary code

2021-07-23 12:06 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/security/TimemanagerAccessControlFilter.java
> +        }
unnecessary code

2021-07-23 12:08 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> +			  final long offset = offsetMillis.longValue();
if offsetMillis is null, this will cause a NullPointerException

2021-07-23 12:08 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> +			  }
you should move this snippet up before the calculation of offset.

2021-07-23 12:09 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> +				  logger.debug("Time offset to large, something is wrong!");
typo: to => too

2021-07-23 12:09 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> +			  ioe.printStackTrace();
change this to proper logging

2021-07-23 12:09 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> +		  e.printStackTrace();
change this to proper logging

2021-07-23 12:10 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeService.java
> +public class TimeService {
what is the purpose of this class?

2021-07-23 12:11 UTC, rbocsi commented on timemanager/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +]}
all your custom properties should be here

2021-07-23 12:13 UTC, rbocsi commented on timemanager/src/main/resources/swagger/swagger-ui.html
> +  <title>Timemanager</title>
should be Time Manager

2021-07-23 12:14 UTC, rbocsi requested changes
see inline comments

2021-07-23 12:54 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/dto/shared/TimeManagerTimeResponseDTO.java
> +        private long epoch_ms;
Fixed

2021-07-23 12:55 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerController.java
> +package eu.arrowhead.core.timeamanager;
yes, fixed

2021-07-23 12:55 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
> +    TimeWSHandler timeWSHandler;
Yes, fixed

2021-07-23 12:55 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
> +    TimeManagerDriver timeManagerDriver;
Yes, fixed

2021-07-23 13:00 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
> +                        attributes.put("CN", CN);
Fixed

2021-07-23 13:01 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeWSHandler.java
> +    TimeManagerDriver timeManagerDriver;
Yes, fixed

2021-07-23 13:01 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/database/service/TimeManagerDBService.java
> +public class TimeManagerDBService {
Work is in progress to add more features...

2021-07-23 13:06 UTC, jenseliasson commented on timemanager/src/main/resources/swagger/swagger-ui.html
> +  <title>Timemanager</title>
No, TimeManager

2021-07-23 13:24 UTC, jenseliasson commented on scripts/start_coresystems.bat
> +START "" /B "cmd /c javaw -jar arrowhead-timemanager-4.1.3.jar > sout_timemanager.log 2>&1"
Fixed

2021-07-23 13:26 UTC, jenseliasson commented on timemanager/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_timemanager || true
fixed

2021-07-23 13:33 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              JcaPEMKeyConverter converter = new JcaPEMKeyConverter().setProvider("BC");
Fixed

2021-07-23 13:33 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +                     converter = new JcaPEMKeyConverter().setProvider("BC");
Fixed

2021-07-23 13:34 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              caKs.setCertificateEntry("ca-certificate", certConverter.getCertificate(caCert));
Fixed

2021-07-23 13:34 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              ks.setCertificateEntry("certificate", certConverter.getCertificate(cert));
Fixed

2021-07-23 13:34 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              SSLContext context = SSLContext.getInstance("TLSv1.3");
Fixed

2021-07-23 13:34 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              ks.setKeyEntry("private-key", key.getPrivate(), password.toCharArray(), new java.security.cert.Certificate[]{certConverter.getCertificate(cert)});
Fixed

2021-07-23 13:34 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              certConverter.setProvider("BC");
Fixed

2021-07-23 13:44 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +              return context.getSocketFactory();
Fixed

2021-07-23 13:44 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
> +                attributes.put("serviceId", serviceId);
Fixed

2021-07-23 14:04 UTC, jenseliasson commented on timemanager/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +]}
Fixed

2021-07-23 14:14 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> +			  }
fixed

2021-07-23 14:14 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> +			  final long offset = offsetMillis.longValue();
fixed

2021-07-23 14:14 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> +			  ioe.printStackTrace();
fixed

2021-07-23 14:14 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> +		  e.printStackTrace();
fixed

2021-07-23 14:26 UTC, jenseliasson commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +    public static SSLSocketFactory getSslSocketFactory(final String caCrtFile, final String crtFile, final String keyFile, final String password)
Fixed

2021-07-23 14:51 UTC, jenseliasson commented
All review comments are fixed.

2021-07-26 08:27 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/SslUtil.java
> +                     throw e;
this is equals to doing nothing, just much slower :)
I suggest to logging the exception (log.debug) at least.

2021-07-26 08:30 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
>      @Value("${server.ssl.enabled}")
we have a constant for this. CommonConstants.SERVER_SSL_ENABLED

2021-07-26 08:31 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
>      private boolean websocketsEnabled;
the content of `@Value` should be constant too

2021-07-26 08:32 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerController.java
> +	@Value("${time.timezone}")
should be constant

2021-07-26 08:35 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/security/TimemanagerAccessControlFilter.java
>  	protected void checkClientAuthorized(final String clientCN, final String method, final String requestTarget, final String requestJSON, final Map<String,String[]> queryParams) {
Typo in class name, should be TimeManagerAccessControlFilter.

2021-07-26 08:38 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> -		logger.info("Checking external time!");
The content of `@Value` annotations should be constant.

Unfortunately, Git does not allow me to put a comment on a line which is not changed since last review :(

2021-07-26 08:40 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> -			  logger.debug(" Roundtrip delay(ms)=" + delayMillis + ", clock offset(ms)=" + delayMillis); // offset in ms
in this message you use delayMillis twice. I think the second one should be offsetMillis.

2021-07-26 08:40 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/service/TimeManagerDriver.java
> +			logger.debug("Roundtrip delay(ms)=" + delayMillis + ", clock offset(ms)=" + delayMillis); // offset in ms
in this message you use delayMillis twice. I think the second one should be offsetMillis.

2021-07-26 08:41 UTC, rbocsi requested changes
The fixes are good, but I found new issues (see inline comments)

2021-07-26 13:50 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
>      @Value("${server.ssl.enabled}")
fixed

2021-07-26 13:53 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerWSConfig.java
>      private boolean websocketsEnabled;
fixed

2021-07-26 13:55 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/TimeManagerController.java
> +	@Value("${time.timezone}")
fixed

2021-07-27 08:29 UTC, rbocsi approved these changes

2021-08-02 20:48 UTC, jenseliasson reviewed
Fixes done, documentation updated

2021-08-03 08:00 UTC, jenseliasson commented
@rbocsi  
Please review the changes I just pushed.

2021-08-03 08:11 UTC, rbocsi commented on README.md
> +Returns time stamps (UNIX in seconds and millseconds), time zone ("Europe/Budapest"), Daylist savings active (true/false) and if the time is trusted (true/false).
typo: Daylist => Daylight

2021-08-03 08:16 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/security/TimemanagerSecurityConfig.java
> +public class TimemanagerSecurityConfig extends DefaultSecurityConfig {
rename this class: TimemanagerSecurityConfig => TimeManagerSecurityConfig

2021-08-03 08:33 UTC, rbocsi commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/swagger/TimemanagerSwaggerConfig.java
> +public class TimemanagerSwaggerConfig extends DefaultSwaggerConfig {
rename this class: TimemanagerSwaggerConfig => TimeManagerSwaggerConfig

2021-08-03 08:34 UTC, rbocsi requested changes
find some minor issues (only typos)

2021-08-03 09:46 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/swagger/TimemanagerSwaggerConfig.java
> +public class TimemanagerSwaggerConfig extends DefaultSwaggerConfig {
Done

2021-08-03 09:49 UTC, jenseliasson commented on README.md
> +Returns time stamps (UNIX in seconds and millseconds), time zone ("Europe/Budapest"), Daylist savings active (true/false) and if the time is trusted (true/false).
Fixed

2021-08-03 09:50 UTC, jenseliasson commented on timemanager/src/main/java/eu/arrowhead/core/timemanager/security/TimemanagerSecurityConfig.java
> +public class TimemanagerSecurityConfig extends DefaultSecurityConfig {
Done

2021-08-03 10:04 UTC, jenseliasson commented
Fixed!

2021-08-21 11:59 UTC, merged