Gams merge
eclipse-arrowhead/core-java-spring pull request #332
Opened 2021-07-29 10:47 UTC by mzsilak

2021-08-03 13:12 UTC, rbocsi commented on certificate-authority/src/main/resources/application.properties
> +cloud.ssl.key-alias=certificate_authority
doesn't seem right. These entries are related to the cloud's certificate, not to the certificate authority. The alias should be something like this: testcloud2.aitia.arrowhead.eu.

2021-08-03 13:25 UTC, rbocsi commented on gams/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_onboarding || true
If GAMS uses the db (even for logging), it needs a unique user (and password), should not use the onboarding's credentials.

To use the mysql_password_gams entry, you need to add a few lines to the core-common/src/deb/control/templates file.

2021-08-03 13:26 UTC, rbocsi commented on gams/src/deb/control/postinst
> +		db_unregister arrowhead-core-common/mysql_password_onboarding
use mysql_password_gams here

2021-08-03 13:28 UTC, rbocsi commented on gams/src/deb/control/postrm
> +		    rmdir ${AH_SYSTEMS_DIR}/sysop 2>/dev/null || true
don't remove sysop's dir

2021-08-03 13:29 UTC, rbocsi commented on gams/src/deb/control/prerm
> +PKG_NAME="arrowhead-onboarding"
PKG_NAME is wrong, should be arrowhead-gams

2021-08-03 13:29 UTC, rbocsi commented on gams/src/deb/gams.service
> +ExecStart=/usr/bin/java -Dlog4j.configurationFile=file:/etc/arrowhead/systems/gams/log4j2.xml -jar /usr/share/arrowhead/gams/arrowhead-onboarding.jar
jar name is wrong, should be arrowhead-gams.jar

2021-08-03 13:32 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/entity/AbstractEntity.java
> +        if(Objects.isNull(createdAt)) this.createdAt = ZonedDateTime.now().withNano(0);
please don't use if, for, while, etc. without braces.

2021-08-03 13:42 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/entity/CountingEvaluation.java
> +    private Integer count;
if count can't be null, why not use int instead of integer?

2021-08-03 13:42 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/entity/CountingEvaluation.java
> +    private Long timeValue = 24L;
if timeValue can't be null, why not use long?

2021-08-03 13:43 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/entity/DoubleSensorData.java
> +    private Double data;
why not use primitive double?

2021-08-03 13:46 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/entity/GamsInstance.java
> +    private Long delay = 0L;
why not primitive long?

2021-08-03 13:49 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/entity/LongSensorData.java
> +    private Long data;
primitive long?

2021-08-03 13:50 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/entity/MatchPolicy.java
> +    private Long number;
primitive long?

2021-08-03 13:52 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/entity/Sensor.java
> +    private Long retentionTime = 24L;
primitive long?

2021-08-03 13:52 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/entity/Sensor.java
> +        if(Objects.nonNull(timeUnit)) this.timeUnit = timeUnit;
braces

2021-08-03 13:53 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/entity/SetPointEvaluation.java
> +    private Boolean inverse;
why not primitive boolean?

2021-08-03 13:54 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/entity/TimeoutGuard.java
> +    private Long timeValue = 24L;
why not primitive long?

2021-08-03 13:56 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/repository/AbstractSensorDataRepository.java
> +    Long countBySensorAndStateAndCreatedAtAfter(final Sensor sensor, final ProcessingState state, final ZonedDateTime from);
primitive long?

2021-08-03 13:59 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/repository/ActionPlanRepository.java
> +public interface ActionPlanRepository extends RefreshableRepository<ActionPlan, Long> {
maybe missing `@Repository` annotation

2021-08-03 13:59 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/repository/AggregationRepository.java
> +public interface AggregationRepository extends RefreshableRepository<Aggregation, Long> {
maybe missing @Repository annotation

2021-08-03 14:00 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/repository/EventRepository.java
> +    Long countValid();
primitive long?

2021-08-03 14:03 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/common/database/repository/TimeoutRepository.java
> +public interface TimeoutRepository extends RefreshableRepository<TimeoutGuard, Long> {
should be named TimeoutGuardRepository

2021-08-04 08:03 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/GamsProperties.java
> +        private Long value;
primitive long?

2021-08-04 08:32 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/rest/controller/GamsManagementController.java
> +    public GamsInstanceListDto getInstances() {
should support paging

2021-08-04 08:33 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/rest/controller/GamsManagementController.java
> +    public SensorListDto getSensors(@PathVariable(Constants.PARAMETER_UID) final String instanceUid) {
should support paging

2021-08-04 08:35 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/rest/controller/SensorDataController.java
> +    private static final String PUBLISH_SENSOR_BAD_REQUEST = "Unable to publish sensor";
maybe "Unable to publish sensor data"

2021-08-04 08:39 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/rest/dto/CreateInstanceRequest.java
> +    @ApiModelProperty(required = false, value = "Contact information (e-mail) of the mainainer", dataType = "string")
typo: mainainer => maintainer

2021-08-04 08:46 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/security/GamsAccessControlFilter.java
> +    protected void checkClientAuthorized(final String clientCN, final String method, final String requestTarget, final String requestJSON, final Map<String, String[]> queryParams) {
you don't use this method.

2021-08-04 08:47 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/ActionAssemblyService.java
> +    public ActionAssemblyService(final HttpService httpService, final EventService eventService,
missing `@Autowired`

2021-08-04 08:58 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventConsumer.java
> +    private final static Long ADD_WORKERS_START_DELAY = 30L;
primitive long?

2021-08-04 08:58 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventConsumer.java
> +    private final static Long ADD_WORKERS_INTERVAL_DELAY = 300L;
primitive long?

2021-08-04 08:58 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventConsumer.java
> +    private final static Long REMOVE_WORKERS_START_DELAY = 60L;
primitive long?

2021-08-04 08:58 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventConsumer.java
> +    private final static Long REMOVE_WORKERS_INTERVAL_DELAY = 60L;
primitive long?

2021-08-04 09:05 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    public void createFailureEvent(final Event source, final String message) {
Transaction?

2021-08-04 09:06 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    public void createTimeoutEvent(final TimeoutGuard analysis) {
Transaction?

2021-08-04 09:07 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    public void createMonitorEventWithDelay(final Sensor sensor, final AbstractSensorData<?> data) {
Transaction?

2021-08-04 09:07 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    public void createMonitorEvent(final Sensor sensor, final AbstractSensorData<?> data) {
Transaction?

2021-08-04 09:07 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    public void createAnalyseEvent(final Sensor sensor, final AbstractSensorData<?> data) {
Transaction?

2021-08-04 09:08 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    public void createPlanEvent(final Sensor sensor, final AbstractSensorData<?> data) {
Transaction?

2021-08-04 09:09 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    protected void persisted(final Event event) {
whenever you use this method, it should be in a transaction

2021-08-04 09:09 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    protected void processing(final Event event) {
whenever you use this method, it should be in a transaction

2021-08-04 09:09 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    protected void processed(final Event event) {
whenever you use this method, it should be in a transaction

2021-08-04 09:09 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    protected void expireEvents() {
whenever you use this method, it should be in a transaction

2021-08-04 09:13 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/InstanceService.java
> +public class InstanceService {
Every database-related method (not just in this class, everywhere) should catch Exception comes from the DB layer, log it and throw an ArrowheadException instead.

2021-08-04 09:14 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/InstanceService.java
> +    public void delete(final GamsInstance gamsInstance) {
Transaction?

2021-08-04 09:15 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/KnowledgeService.java
> +    public void put(final GamsInstance instance, final String key, final String value) {
Transaction?

2021-08-04 09:16 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/MapeKService.java
> +    public void publish(final Sensor sensor, final ZonedDateTime timestamp, final Object data, final String address) {
Transaction?

2021-08-04 09:16 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/MapeKService.java
> +    public void analyze(final Event source) {
Transaction?

2021-08-04 09:18 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/MapeKService.java
> +                    final MatchPolicy matchPolicy = ((MatchPolicy) policy);
outer parantheses are unnecessary

2021-08-04 09:25 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    public Sensor create(final GamsInstance instance, final CreateSensorRequest request) {
Transaction?

2021-08-04 09:25 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    public AbstractSensorData<?> store(final Sensor sensor, final ZonedDateTime timestamp, final Object data, final String address) {
Transaction?

2021-08-04 09:25 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    public void store(final AbstractSensorData datum) {
Transaction?

2021-08-04 09:28 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    public void deleteAllSensor(final GamsInstance instance) {
Transaction?

2021-08-04 09:30 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    protected Sensor createEventSensor(final GamsInstance instance, final String name, final SensorType type) {
The public method that eventually call this should be in a transaction

2021-08-04 09:30 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    public Sensor createEventSensor(final GamsInstance instance, final ConfigurationEntity entity, final SensorType type) {
I think this is the one. So... transaction

2021-08-04 09:31 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    protected void persisted(final AbstractSensorData data) {
The public method that eventually call this should be in a transaction

2021-08-04 09:31 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    protected void processing(final AbstractSensorData data) {
The public method that eventually call this should be in a transaction

2021-08-04 09:31 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    protected void processed(final AbstractSensorData data) {
The public method that eventually call this should be in a transaction

2021-08-04 09:33 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/TimeoutService.java
> +    public void createTimeoutGuard(final Sensor sensor, final Long timeValue, final ChronoUnit timeUnit) {
Transaction?

2021-08-04 09:33 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/TimeoutService.java
> +    public void deleteTimeoutAnalysis(final TimeoutGuard guard) {
Transaction?

2021-08-04 09:40 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/utility/MathHelper.java
> +            long l = (long) ((((Double) number)) * PRECISION);
never ever use l as a variable, it's confusing (looks like a 1 is some fonts).

Also, it seems to me you use too much paranthesis.
`long longValue = (long) (((Double) number) * PRECISION);`
is enough.

2021-08-04 09:41 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/utility/MathHelper.java
> +            long l = (long) ((((Float) number)) * PRECISION);
same as the previous comment

2021-08-04 09:43 UTC, rbocsi commented on gams/src/main/resources/application.properties
> +server.address=127.0.0.1
it should be 0.0.0.0

2021-08-04 09:44 UTC, rbocsi commented on gams/src/main/resources/log4j2.xml
> +		<Property name="ARROWHEAD_CONSOLE_FILE_LEVEL">DEBUG</Property>
should be INFO in the repository

2021-08-04 09:45 UTC, rbocsi commented on gams/src/main/resources/sql/table_creation.sql
> +/*
remove these

2021-08-04 09:51 UTC, rbocsi commented on gams/src/test/resources/application.properties
> +server.address=127.0.0.1
should be 0.0.0.0

2021-08-04 09:54 UTC, rbocsi commented on gams/src/main/resources/sql/table_creation.sql
> +CREATE TABLE IF NOT EXISTS `gams_instance`
these table creation should be in the scripts/create_arrowhead_tables.sql file as well.

2021-08-04 09:56 UTC, rbocsi commented on scripts/gams_privileges.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`logs` TO 'gams_knowledge'@'localhost';
there is no such user

2021-08-04 09:56 UTC, rbocsi commented on scripts/gams_privileges.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`logs` TO 'gams_knowledge'@'%';
there is no such user

2021-08-04 09:58 UTC, rbocsi commented on scripts/gams_privileges.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`gams_setpoint_analysis` TO 'gams@localhost';
missing qoute sign after gams

2021-08-04 09:59 UTC, rbocsi requested changes
see my inline comments

2021-08-04 10:28 UTC, rbocsi commented on pom.xml
> +	    <module>qos-monitor</module>
The current version does not contain qos-monitor (the upcoming 4.4.0 will), so this line cause error when you run maven.

2021-08-04 10:56 UTC, rbocsi commented
Some tests are failed for me:

MapeKTimeoutTest.createTimeout:
```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sensorDataController' defined in file [B:\munka\tmp\core-java-spring\gams\target\classes\eu\arrowhead\core\gams\rest\controller\SensorDataController.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mapeKService' defined in file [B:\munka\tmp\core-java-spring\gams\target\classes\eu\arrowhead\core\gams\service\MapeKService.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'timeoutService': Invocation of init method failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select timeoutgua0_.id as id1_45_, timeoutgua0_.created_at as created_2_45_, timeoutgua0_.uid as uid3_45_, timeoutgua0_.updated_at as updated_4_45_, timeoutgua0_.sensor_id as sensor_i7_45_, timeoutgua0_.time_unit as time_uni5_45_, timeoutgua0_.time_value as time_val6_45_ from gams_timeout_guard timeoutgua0_]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:843)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:275)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:243)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 25 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mapeKService' defined in file [B:\munka\tmp\core-java-spring\gams\target\classes\eu\arrowhead\core\gams\service\MapeKService.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'timeoutService': Invocation of init method failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select timeoutgua0_.id as id1_45_, timeoutgua0_.created_at as created_2_45_, timeoutgua0_.uid as uid3_45_, timeoutgua0_.updated_at as updated_4_45_, timeoutgua0_.sensor_id as sensor_i7_45_, timeoutgua0_.time_unit as time_uni5_45_, timeoutgua0_.time_value as time_val6_45_ from gams_timeout_guard timeoutgua0_]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support. [...]

2021-08-04 10:58 UTC, rbocsi commented
SensorControllerTest (all three):
```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sensorDataController' defined in file [B:\munka\tmp\core-java-spring\gams\target\classes\eu\arrowhead\core\gams\rest\controller\SensorDataController.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mapeKService' defined in file [B:\munka\tmp\core-java-spring\gams\target\classes\eu\arrowhead\core\gams\service\MapeKService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'knowledgeService' defined in file [B:\munka\tmp\core-java-spring\gams\target\classes\eu\arrowhead\core\gams\service\KnowledgeService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'eu.arrowhead.common.database.repository.AggregationRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:843)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 25 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mapeKService' defined in file [B:\munka\tmp\core-java-spring\gams\target\classes\eu\arrowhead\core\gams\service\MapeKService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'knowledgeService' defined in file [B:\munka\tmp\core-java-spring\gams\target\classes\eu\arrowhead\core\gams\service\KnowledgeService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'eu.arrowhead.common.database.repository.AggregationRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.bea [...]

2021-08-04 10:58 UTC, rbocsi commented
Jammer:

```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sensorDataController' defined in file [B:\munka\tmp\core-java-spring\gams\target\classes\eu\arrowhead\core\gams\rest\controller\SensorDataController.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mapeKService' defined in file [B:\munka\tmp\core-java-spring\gams\target\classes\eu\arrowhead\core\gams\service\MapeKService.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'timeoutService': Invocation of init method failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select timeoutgua0_.id as id1_45_, timeoutgua0_.created_at as created_2_45_, timeoutgua0_.uid as uid3_45_, timeoutgua0_.updated_at as updated_4_45_, timeoutgua0_.sensor_id as sensor_i7_45_, timeoutgua0_.time_unit as time_uni5_45_, timeoutgua0_.time_value as time_val6_45_ from gams_timeout_guard timeoutgua0_]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:843)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:275)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:243)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 25 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mapeKService' defined in file [B:\munka\tmp\core-java-spring\gams\target\classes\eu\arrowhead\core\gams\service\MapeKService.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'timeoutService': Invocation of init method failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select timeoutgua0_.id as id1_45_, timeoutgua0_.created_at as created_2_45_, timeoutgua0_.uid as uid3_45_, timeoutgua0_.updated_at as updated_4_45_, timeoutgua0_.sensor_id as sensor_i7_45_, timeoutgua0_.time_unit as time_uni5_45_, timeoutgua0_.time_value as time_val6_45_ from gams_timeout_guard timeoutgua0_]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance( [...]

2021-08-30 15:52 UTC, mzsilak commented on gams/src/main/java/eu/arrowhead/core/gams/service/InstanceService.java
> +public class InstanceService {
The GAMS system is event based and most of its interaction is not triggered from outside. I've added the Exceptions where the calls might come from outside

2021-11-09 12:32 UTC, tsvetlin commented
@mzsilak What is the status of this PR?
Have you fixed all issues, do you need a new review?

2021-11-09 14:30 UTC, mzsilak commented
All issues should be fixed. Another review can be done for QA.

2021-11-09 16:07 UTC, tsvetlin commented
As I can see there are conflicts @mzsilak. Could you please resolve them, and we can continue with the review.

2021-11-17 12:53 UTC, tsvetlin commented
Bump!

Could you please resolve the merge conflicts here too @mzsilak. We will do the review after. Thank you

2021-12-21 19:59 UTC, mzsilak commented
@tsvetlin It is merged now

2022-01-03 11:48 UTC, rbocsi commented on gams/src/deb/gams.service
> +[Unit]
This file name should be arrowhead-gams.service. Because this is how files like postinst and prerm referenced the service file.

2022-01-03 11:48 UTC, rbocsi commented on gams/pom.xml
> +	                				<src>${project.basedir}/src/deb/gams.service</src>
gams.service should be renamed to arrowhead-gams.service

2022-01-03 13:06 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventConsumer.java
> +    @Transactional
I think @Transactional does not work on protected (or private) methods. So instead using here, you should marked the method with the annotation that calling this method.

2022-01-03 13:09 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    @Transactional
I think @transactional does not work on protected (or private) methods. So instead using here, you should marked the method with the annotation that calling this method.

2022-01-03 13:09 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    @Transactional
I think @transactional does not work on protected (or private) methods. So instead using here, you should marked the method with the annotation that calling this method.

2022-01-03 13:09 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    @Transactional
I think @transactional does not work on protected (or private) methods. So instead using here, you should marked the method with the annotation that calling this method.

2022-01-03 13:10 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    @Transactional
I think @transactional does not work on protected (or private) methods. So instead using here, you should marked the method with the annotation that calling this method.

2022-01-03 13:12 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventConsumer.java
> +    @Transactional
or maybe this method should be public (because the method caller is not a Spring bean).

2022-01-03 13:13 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    protected void persisted(final Event event) {
or make this method public

2022-01-03 13:22 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    @Transactional
I think @transactional does not work on protected (or private) methods. So instead using here, you should marked the method with the annotation that calling this method.

2022-01-03 13:22 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    @Transactional
I think @transactional does not work on protected (or private) methods. So instead using here, you should marked the method with the annotation that calling this method.

2022-01-03 13:22 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    @Transactional
I think @transactional does not work on protected (or private) methods. So instead using here, you should marked the method with the annotation that calling this method.

2022-01-03 13:22 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/SensorService.java
> +    @Transactional
I think @transactional does not work on protected (or private) methods. So instead using here, you should marked the method with the annotation that calling this method.

2022-01-03 13:30 UTC, rbocsi commented on scripts/gams_privileges.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`logs` TO 'gams_knowledge'@'localhost';
gams_knowledge user does still not exist. Please delete this line.

2022-01-03 13:30 UTC, rbocsi commented on scripts/gams_privileges.sql
> +GRANT ALL PRIVILEGES ON `arrowhead`.`logs` TO 'gams_knowledge'@'%';
gams_knowledge user does still not exist. Please delete this line.

2022-01-03 13:33 UTC, rbocsi requested changes
Thanks for the fixes. I still found some issues (see new inline comments).

Unit tests are working now.

2022-03-07 10:29 UTC, rbocsi commented on gams/src/main/java/eu/arrowhead/core/gams/service/EventService.java
> +    protected void processing(final Event event) {
The caller still don't have a transaction.

2022-03-07 10:32 UTC, rbocsi requested changes
Only 1 problem found. See inline comment (EventService).

2022-06-23 09:17 UTC, rbocsi approved these changes

2022-06-23 09:19 UTC, merged