Ditto integration
eclipse-arrowhead/core-java-spring pull request #375
Opened 2022-02-21 09:33 UTC by nicnys-8

We would like this pull request to be merged into a new branch named ditto-integration.

2022-02-21 13:00 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/InventoryIdDTO.java
> +	public InventoryIdDTO(@JsonProperty("inventoryId") final String inventoryId) {
maybe a  `@JsonCreator` annotation on the constructor is missing here?

2022-02-21 13:03 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/SystemDataDTO.java
> +	public SystemDataDTO(@JsonProperty("systemData") final String data) {
maybe a @JsonCreator annotation on the constructor is missing here?

2022-02-21 13:05 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/internal/SystemDataDTO.java
> +	public String getSystemData() {
getSystemData and setSystemData() or getData() and setData().

2022-02-21 13:10 UTC, rbocsi commented on ditto/src/deb/control/config
> +db_input high arrowhead-core-common/mysql_password_chor || true
This field is the db password of the Choreographer. If you want to use the database, creates a new entry in the core-common/src/deb/control/templates file and use that

2022-02-21 13:12 UTC, rbocsi commented on ditto/src/deb/control/postinst
> +    db_get arrowhead-core-common/mysql_password_ditto; system_passwd=$RET || true
in here, you use the right field (but this field is not defined in the templates file)

2022-02-21 13:15 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoController.java
> +			response = String.class, tags = {CoreCommonConstants.SWAGGER_TAG_CLIENT})
Is response a String or and Object?

2022-02-21 13:17 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoMonitorController.java
> +		return new SystemDataDTO("");
does not seem to me very useful.

2022-02-21 13:18 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoMonitorController.java
> +	@ApiOperation(value = "Return system data describing this core system", response = String.class, tags = { CoreCommonConstants.SWAGGER_TAG_CLIENT })
response is not String

2022-02-21 13:18 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoMonitorController.java
> +	@ApiOperation(value = "Return an inventory ID for this core system", response = String.class, tags = { CoreCommonConstants.SWAGGER_TAG_CLIENT })
response is not String

2022-02-21 13:18 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoMonitorController.java
> +		return new InventoryIdDTO("");
does not seem to me very useful.

2022-02-21 13:20 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/security/DittoSecurityConfig.java
> +		registrationBean.addUrlPatterns("/things/*"); // TODO: Move constant somewhere else.
can be a constant in this class if you don't use anywhere else

2022-02-21 13:23 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/security/DittoSecurityConfig.java
> +		KeyStore keystore;
your private key can be accessed through the arrowheadContext too with the key CommonConstants.SERVER_PRIVATE_KEY.

See ApplicationInitListener.obtainKeys() method

2022-02-21 13:40 UTC, rbocsi commented on ditto/src/main/resources/application.properties
> +ditto_ws_address=ws://localhost:8080
two protocols on the same port?

2022-02-21 13:42 UTC, rbocsi commented on ditto/src/test/resources/application.properties
> +ditto_ws_address=ws://localhost:8080
same here

2022-02-21 13:44 UTC, rbocsi commented on scripts/ditto_privileges.sql
> +USE `arrowhead`;
you should add some lines into the create_empty_arrowhead_db.sql file to create those users that referenced here and include this file.

2022-02-21 13:46 UTC, rbocsi requested changes
See inline comments. After fixing those, somebody probably Svetlin can create a branch for you, and redirect this PR to the new branch.

2022-02-22 17:10 UTC, tsvetlin commented
@nicnys-8 Base branch changed

2022-02-23 16:33 UTC, merged