Orchestrator orchestration from store
eclipse-arrowhead/core-java-spring pull request #38
Opened 2019-08-07 09:55 UTC by MaGaMeGa

2019-08-07 11:51 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
>  			throw new InvalidParameterException("Consumer with name: " + name + ", address: " + address + " and port: " + port + " is not exist in the database.");
There is a file named .swp. What is this? Please delete if it isn't important

2019-08-07 11:53 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/OrchestratorStoreRepository.java
> +	public List<OrchestratorStore> findAllByPriorityAndSystemId(int topPriority, long consumerSystemId);
finals

2019-08-07 11:59 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +	public static List<Long> convertServiceInterfaceResponseDTOListToServiceInterfaceIdList(
There is private method in OrchestratorDriver named convertServiceInterfaceListToServiceInterfaceIdList which does the same. Use that if you can (it's shorter). If you can't access it, move THAT method to here (make public and static) and use that everywhere.

2019-08-07 12:01 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		Assert.notNull(orchestratorStoreResponseDTO.getProviderCloud(), "orchestratorStoreResponseDTO.ProviderCloud is null");
is this true? Is ProviderCloud always set, even in case of local rule?

2019-08-07 12:03 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		preferredProviderDataDTO.setProviderCloud(cloudRequestDTO);
PreferredProviderDataDTO expects that the providerCloud is only set to a non-null value, if the provider is in an other cloud. If the provider is local, the cloud member must be set to null. See isLocal() method.

2019-08-07 12:09 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/ICNResponseDTO.java
> +public class ICNResponseDTO extends OrchestrationResponseDTO {
This may changed because this part of the gatekeeper service is not implemented yet (but we already have a ICNProposalResponseDTO class which is basicly empty. I don't know these two types are the same or not. We'll see when we get there.)

2019-08-07 12:12 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorApplicationInitListener.java
> +		final String registerUriStr = CommonConstants.SERVICE_REGISTRY_URI + CommonConstants.OP_SERVICE_REGISTRY_QUERY_BY_SYSTEM_ID_URI;
typo registryUriStr (does not register anything)

2019-08-07 12:12 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorApplicationInitListener.java
> +		final String registerUriStr = CommonConstants.SERVICE_REGISTRY_URI + CommonConstants.OP_SERVICE_REGISTRY_QUERY_BY_SYSTEM_DTO_URI;
the same as before

2019-08-07 12:15 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorController.java
> +	@ApiOperation(value = "Get Orchestration process by the consumer SystemId.", response = OrchestrationResponseDTO.class)
need a better description for example
"Start ochestration process from the ochestrator store based on consumer system id."

2019-08-07 12:18 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		if ( Utilities.isEmpty(serviceDefinitionName)) {
move this before the db operation. If servicedefinition is null or blank than the method can throw exception without any db operation (it will be quicker).

2019-08-07 12:19 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		if ( Utilities.isEmpty(serviceDefinitionName)) {
move this before any db operation

2019-08-07 12:19 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		if ( Utilities.isEmpty(serviceInterfaceName)) {
move this before any db operation

2019-08-07 12:20 UTC, MaGaMeGa commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
>  			throw new InvalidParameterException("Consumer with name: " + name + ", address: " + address + " and port: " + port + " is not exist in the database.");
done

2019-08-07 12:20 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/database/service/OrchestratorStoreDBService.java
> +		final Optional<ForeignSystem> foreignSystemOptional = foreignSystemRepository.findById(orchestratorStore.getProviderSystemId());
check if input parameter is null or not

2019-08-07 12:23 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/database/repository/OrchestratorStoreRepository.java
> +	public List<OrchestratorStore> findAllByPriorityAndSystemId(int topPriority, long consumerSystemId);
done

2019-08-07 12:29 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudProviderMatchmakingParameters.java
> +		Assert.notNull(preferredGlobalProviders, "preferredLocalProviders set is null.");
it's not a set it's a list. The same error appears in the IntraCloud...Parameters constructor as well, please fix that too.

2019-08-07 12:30 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorDriver.java
> +				Collections.singletonMap(CommonConstants.COMMON_FIELD_NAME_ID, consumerSystemId + ""));
you can use Map.of() instead it's shorter

2019-08-07 12:32 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	private static final String SERVICE_REGISTRY_QUERY_BY_SYSTEM_ID_DESCRIPTION = "Return Consumer system by requested id";
delete consumer from the sentence (the webservice can return any system I think)

2019-08-07 12:33 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	private static final String SERVICE_REGISTRY_QUERY_BY_SYSTEM_ID_400_MESSAGE = "Could not query Service Registry by Consumer system id";
modify accordingly the status messages too

2019-08-07 12:33 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	private static final String SERVICE_REGISTRY_QUERY_BY_SYSTEM_DTO_400_MESSAGE = "Could not query Service Registry by Consumer system requestDTO";
the same as the previous comments

2019-08-07 12:34 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +	@ResponseBody public SystemResponseDTO queryRegistryBySystemId(@PathVariable(value = PATH_VARIABLE_ID) final long consumerSystemId) {
rename input parameter to systemId

2019-08-07 12:35 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("Return consumer system by id: {}", consumerSystemId);
don't forget to fix the debug messages too

2019-08-07 12:37 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/ServiceRegistryController.java
> +		logger.debug("Return consumer system by name: {}, address: {}, port: {}", systemName, address, port);
remove consumer from the sentence

2019-08-07 12:37 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +	public SystemResponseDTO getSystemByNameAndAddressAndPort(String systemName, String address, int port) {
finals

2019-08-07 12:46 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +	public static List<Long> convertServiceInterfaceResponseDTOListToServiceInterfaceIdList(
fixed: method was not in use, removed

2019-08-07 12:48 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    orchestrationFormRequestDTO.validateCrossParameterConstraints();
this line is unnecessary since the next method calling will validate the form.

2019-08-07 12:49 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +
check if the dto is null or not

2019-08-07 12:50 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +		final SystemResponseDTO systemResponseDTO = orchestratorDriver.queryServiceRegistryBySystemId(systemId);
return the result immediately (sonarqube is not happy to see this)

2019-08-07 12:55 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +			if (requestedService.getInterfaceRequirements() == null || Utilities.isEmpty(requestedService.getInterfaceRequirements().get(0) )) {
the second part of the condition is wrong. If you want that interface requirements contains only one element then you have to use requestedService.getInterfaceRequirements().size() == 1.
The current one checks if the first element of the interface list is null or empty string (and an NullPointerException is thrown if the list is empty).

2019-08-07 12:56 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    	return new ArrayList<>(0);
use List.of() instead

2019-08-07 12:57 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    for (java.util.Map.Entry<Long, String> entry : serviceDefinitionsIdsMap.entrySet()) {
use import

2019-08-07 12:58 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    final Map<Long, List<String>> serviceDefinitionIdInterfaceIdsMap = mapIntrefacesToServiceDefinitions( onlyLocalEntryList);
typo intERfaces

2019-08-07 12:59 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    final Map<Long, List<String>> providerIdInterfaceIdsMap = mapIntrefacesToProviders( onlyLocalEntryList);
same typo again

2019-08-07 13:00 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private List<OrchestratorStore> filterEntryListByForeign(List<OrchestratorStore> entryList) {
change this to a lambda expression

2019-08-07 13:01 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    	return new ArrayList<>(0);
use List.of()

2019-08-07 13:03 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		Assert.notNull(orchestratorStoreResponseDTO.getProviderCloud(), "orchestratorStoreResponseDTO.ProviderCloud is null");
This method should be called only when the provider is foreign -
renamed to convertForeignOrchestratorStoreResponseDTOToPreferredProviderDataDTO

2019-08-07 13:04 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private Map<Long, List<String>> mapIntrefacesToServiceDefinitions(List<OrchestratorStore> entryList) {
typo in name

2019-08-07 13:04 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		preferredProviderDataDTO.setProviderCloud(cloudRequestDTO);
renamed to convertForeignOrchestratorStoreResponseDTOToPreferredProviderDataDTO

2019-08-07 13:05 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +				final List<String> serviceInterfaceIdList = new ArrayList<>();
is it possible that the interface name list contains the same name more than once?

2019-08-07 13:05 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private Map<Long, List<String>> mapIntrefacesToProviders(List<OrchestratorStore> entryList) {
typo

2019-08-07 13:07 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +			filteredInterfaceList.clear();
unnecessary line the list is empty at this point

2019-08-07 13:10 UTC, rbocsi requested changes
see inline comments

To be honest, I don't exactly understand the whole process, it's too difficult (the cognitive complexity is too much :) ). After you finish the changes and test, I think I will debug the process someday.

2019-08-07 13:13 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		Assert.notNull(orchestratorStoreResponseDTO.getProviderCloud(), "orchestratorStoreResponseDTO.ProviderCloud is null");
in that case you have to check the input (it is a foreing rule or not). This is a public method, you can't assume anything about the caller.

2019-08-07 14:39 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private Map<Long, List<String>> mapIntrefacesToServiceDefinitions(List<OrchestratorStore> entryList) {
fixed

2019-08-07 14:39 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    	return new ArrayList<>(0);
done

2019-08-07 14:40 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private List<OrchestratorStore> filterEntryListByForeign(List<OrchestratorStore> entryList) {
done

2019-08-07 14:40 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    for (java.util.Map.Entry<Long, String> entry : serviceDefinitionsIdsMap.entrySet()) {
fixed

2019-08-07 14:40 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    final Map<Long, List<String>> providerIdInterfaceIdsMap = mapIntrefacesToProviders( onlyLocalEntryList);
fixed

2019-08-07 14:40 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    final Map<Long, List<String>> serviceDefinitionIdInterfaceIdsMap = mapIntrefacesToServiceDefinitions( onlyLocalEntryList);
fixed

2019-08-07 14:40 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    	return new ArrayList<>(0);
done

2019-08-07 14:41 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +			if (requestedService.getInterfaceRequirements() == null || Utilities.isEmpty(requestedService.getInterfaceRequirements().get(0) )) {
done

2019-08-07 14:41 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +		final SystemResponseDTO systemResponseDTO = orchestratorDriver.queryServiceRegistryBySystemId(systemId);
done

2019-08-07 14:41 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    orchestrationFormRequestDTO.validateCrossParameterConstraints();
removed

2019-08-07 14:41 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +
done

2019-08-07 14:43 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/ICNResponseDTO.java
> +public class ICNResponseDTO extends OrchestrationResponseDTO {
ok

2019-08-07 14:52 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		Assert.notNull(orchestratorStoreResponseDTO.getProviderCloud(), "orchestratorStoreResponseDTO.ProviderCloud is null");
done

2019-08-07 15:24 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudProviderMatchmakingParameters.java
> +		Assert.notNull(preferredGlobalProviders, "preferredLocalProviders set is null.");
done

2019-08-07 15:30 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorDriver.java
> +				Collections.singletonMap(CommonConstants.COMMON_FIELD_NAME_ID, consumerSystemId + ""));
done

2019-08-07 15:47 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +				final List<String> serviceInterfaceIdList = new ArrayList<>();
surrounded the addition with contains conditional and corrected interfaceIdList to interfaceNameList

2019-08-07 16:24 UTC, MaGaMeGa commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/database/service/ServiceRegistryDBService.java
> +	public SystemResponseDTO getSystemByNameAndAddressAndPort(String systemName, String address, int port) {
done

2019-08-16 09:20 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	public OrchestrationResponseDTO orchestrationFromStoreWithSystemIdParameter(
It's a bit missleading that the method name is "......WithSystemIdParameter", but systemId can be null and you still get result with.

2019-08-16 09:26 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +			final SystemRequestDTO consumerSystemRequestDTO = DTOConverter.convertSystemResponseDTOToSystemRequestDTO(orchestratorDriver.queryServiceRegistryBySystemId(systemId));
I think here you already have a valid SystemRequestDTO in the OrchestrationFormRequestDTO. No need for querying via http request.

2019-08-16 10:19 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +		}else {
The method sould be split here to two part, cause the two branch of the 'if -else' block do different things
1st block returns all the top priorized provider-service entries (more different service)
2nd block returns available providers for one exact service.
The purpose is quiet different

2019-08-16 10:59 UTC, borditamas requested changes
see comments

2019-08-20 14:15 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	public OrchestrationResponseDTO orchestrationFromStoreWithSystemIdParameter(
fixed in refactored code

2019-08-20 14:15 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +			final SystemRequestDTO consumerSystemRequestDTO = DTOConverter.convertSystemResponseDTOToSystemRequestDTO(orchestratorDriver.queryServiceRegistryBySystemId(systemId));
fixed in refactored code

2019-08-20 14:16 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +		}else {
fixed in refactored code

2019-08-21 08:57 UTC, borditamas commented
As the branch "Orchestrator orchestration trigger inter cloud" contains these commits as well, therefore the review & merge going to happen by the pull request of that branch.

2019-08-21 08:57 UTC, closed without merging