Ditto integration
eclipse-arrowhead/core-java-spring pull request #395
Opened 2022-06-27 10:15 UTC by misterabdullahAziz

Contribution of Ah-Ditto integration to Eclipse Arrowhead.

2022-06-29 07:49 UTC, tsvetlin commented
Hello @misterabdullahAziz 

We are in the middle of the summer holiday season. We will conduct the code review after. 
Thank you for your patience.

Kind regards,
Svetlin

2022-07-11 10:08 UTC, rbocsi commented on ditto/example-demo/README.md
> +We need to run the Arrowhead core systems. You can get the working copy of these systems from [Github](https://github.com/Xarepo/core-java-spring/) specifically from branch `ditto-integration`. After
the links here should be changed to the eclipse-arrowhead/core-java-spring

2022-07-11 10:09 UTC, rbocsi commented on ditto/example-demo/README.md
> +    * Execute ``` java -jar arrowhead-serviceregistry-4.4.1.jar ```
version will be different. I think Ditto integration will be available in 4.6.0.

2022-07-11 10:10 UTC, rbocsi commented on ditto/example-demo/README.md
> +    * Execute ``` java -jar arrowhead-authorization-4.4.1.jar ```
version

2022-07-11 10:10 UTC, rbocsi commented on ditto/example-demo/README.md
> +    * Execute ``` java -jar arrowhead-orchestrator-4.4.1.jar ```
version

2022-07-11 10:11 UTC, rbocsi commented on ditto/example-demo/README.md
> +> For setting up Eclipse Arrowhead we should have set up `MySql` databases according to the guidelines provided on [Github](https://github.com/Xarepo/core-java-spring/).
change link to eclipse-arrowhead/core-java-spring

2022-07-11 10:13 UTC, rbocsi commented on ditto/example-demo/README.md
> +Once AH-Ditto recieved the request it create thing based on the model in the Eclipse Ditto. As soon as the thing is created in Eclipse Ditto, AH-Ditto register the services in service_registry based
service_registry => Service Registry (2x)

2022-07-11 10:15 UTC, rbocsi commented on ditto/example-demo/README.md
> +    "uri": "tcp://192.168.1.210:1883",
Will this uri works for everyone? It seems a local network address to me.

2022-07-11 10:16 UTC, rbocsi commented on ditto/example-demo/README.md
> +                "temperature": 0
30.67 instead of 0

2022-07-11 10:17 UTC, rbocsi commented on ditto/example-demo/README.md
> +                "hum": 0
36 instead of 0

2022-07-11 10:17 UTC, rbocsi commented on ditto/example-demo/README.md
> +    const jsonData = JSON.parse(jsonString); const thingId = jsonData.thingId.split(':');
new line before const thingId...

2022-07-11 10:20 UTC, rbocsi commented on ditto/example-demo/README.md
> +For our consumer example application we have used an actuator fan. Based on the temperature value the fan maintain its speed. There fan always want to consume the service from our device. The device
typos:
maintain => maintains
There => The (?)
thr device => the device

+ link change

2022-07-11 10:32 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +	@ApiOperation(value = "Returns the specified Ditto connections", response = String.class, tags = {
response is not a String

2022-07-11 10:32 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +	@ApiOperation(value = "Creates the given Ditto connection", response = String.class, tags = {
response is not a String

2022-07-11 11:30 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +		System.out.println(response.getBody());
remove System.println() lines or replace with log.debug(...)

2022-07-11 11:30 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +	@ApiOperation(value = "updates the given Ditto connection", response = String.class, tags = {
response is not a String

2022-07-11 11:30 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +		System.out.println(response.getBody());
remove System.println() lines or replace with log.debug(...)

2022-07-11 11:32 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +	@PostMapping(path = "/modify", consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
should be a PUT request

2022-07-11 11:32 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +	@ApiOperation(value = "open the given Ditto connection", response = String.class, tags = {
response is not a string

2022-07-11 11:33 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +	@GetMapping(path = "/open/{connectionId}")
i thinks this should be a POST request

2022-07-11 11:34 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +	@ApiOperation(value = "close the given Ditto connections", response = String.class, tags = {
response is not a String

2022-07-11 11:36 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +	@GetMapping(path = "/close/{connectionId}")
I think this should be a POST request

2022-07-11 11:36 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +		System.out.println("inside close connection api call");
remove this line

2022-07-11 11:37 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +		System.out.println("inside delete connection: "+ connectionId);
remove this line

2022-07-11 11:37 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +	@ApiOperation(value = "Deletes the specified Ditto connection", response = String.class,
response is not a string

2022-07-11 11:38 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoApplicationInitListener.java
> +	@Value("classpath:ah-ditto-policy.json")
the content of `@Value` should be a constant.

2022-07-11 11:40 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoApplicationInitListener.java
> +			InputStreamReader reader = new InputStreamReader(resourceFile.getInputStream());
resource leak. This reader should be closed after reading the content. See try with resources

2022-07-11 11:43 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoApplicationInitListener.java
> +			e.printStackTrace();
use logging instead. 

And it would be better if the server just failed to run if it can't access the policy file. So maybe the createPolicy() should throw a ServiceConfigurationError after the logging.

2022-07-11 11:45 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoApplicationInitListener.java
> +			try {
infinite retrying is a wrong idea. Introduce a retry counter. After an amount of retries the server should fail. See ApplicationInitListener.checkServiceRegistryConnection() for example.

2022-07-11 11:45 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoApplicationInitListener.java
> +				e.printStackTrace();
remove this line.

2022-07-11 11:46 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoApplicationInitListener.java
> +				Thread.sleep(500l);
value should be constant.

2022-07-11 11:49 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ConnectionManagementController.java
> +		var response = dittoDevopsHttpClient.putConnection(connectionRequest,"create");
the string "create" (and the others too) should be constant.

2022-07-11 11:50 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/DittoDevopsCommands.java
> +	public String create(final JsonNode connection, final String method) {
all the hard-coded string should be constants

2022-07-11 11:54 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ThingEvent.java
> +		Assert.notNull(source, "source is null");
not necessary, since EventObject (parent of ApplicationEvent) already checked it at this point.

2022-07-11 11:57 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/ThingManagementController.java
> +	@ApiOperation(value = "Deletes the specified Ditto Thing", response = String.class,
no need for response here

2022-07-11 12:03 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/service/DittoDevopsHttpClient.java
> +	public ResponseEntity<JsonNode> getConnection(final String connectionId, final String methode) {
typo: methode => method

2022-07-11 12:05 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/service/DittoDevopsHttpClient.java
> +	public ResponseEntity<JsonNode> putConnection(final JsonNode connection, final String methode) {
typo: methode => method

2022-07-11 12:06 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/service/DittoDevopsHttpClient.java
> +		System.out.println(command);
remove this line

2022-07-11 12:08 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/service/DittoDevopsHttpClient.java
> +	public ResponseEntity<JsonNode> putConnection(final JsonNode connection, final String methode) {
this one's implementation is the same than the getConnection() (except a console print). Why need both?

2022-07-11 12:09 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/service/DittoDevopsHttpClient.java
> +			return new ResponseEntity<>(e.getStatusCode());
it should be useful to logger.debug() this exception too before the return

2022-07-11 12:12 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/service/DittoEventListener.java
> +				Thread.sleep(1000l);
should be a constant

2022-07-11 12:12 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/service/DittoEventListener.java
> +			logger.error("Service registration for feature failed: " + ex);
wrong error message

2022-07-11 12:15 UTC, rbocsi commented on ditto/src/main/java/eu/arrowhead/core/ditto/service/DittoHttpClient.java
> +			return new ResponseEntity<T>(e.getStatusCode());
it would be wise to logger.debug the error here before the return

2022-07-11 12:27 UTC, rbocsi commented on ditto/src/test/java/eu/arrowhead/core/ditto/DittoControllerTest.java
> +import org.springframework.test.context.junit4.SpringRunner;
It is useful to put an empty file named banner.txt into the src/test/resources (see in other arrowhead systems). It removes the Spring boot banner from the test log.

2022-07-11 12:33 UTC, rbocsi requested changes
See inline comments. Also, all of the controller-related unit tests are failed in my computer with the following error:

```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NullPointerException
	at eu.arrowhead.core.ditto.DittoApplicationInitListener.createPolicy(DittoApplicationInitListener.java:92)
	at eu.arrowhead.core.ditto.DittoApplicationInitListener.customInit(DittoApplicationInitListener.java:60)
	at eu.arrowhead.common.ApplicationInitListener.onApplicationEvent(ApplicationInitListener.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:179)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 25 more

```

Tests should run without any other program or settings modifications.

2023-06-08 19:29 UTC, borditamas commented
@misterabdullahAziz 
Are the review comments and the merge conflicts planned to resolve?

2024-03-19 08:22 UTC, closed without merging