Choreographer
eclipse-arrowhead/core-java-spring pull request #41
Opened 2019-08-13 11:05 UTC by szkris

The Choreographer module with the base functions which already worked in the latest version of Arrowhead. Upcoming functions are coming later, including starting and monitoring Action plans.

2019-08-13 11:13 UTC, rbocsi commented on authorization.log
> +2019-07-29 14:12:03.374  INFO DESKTOP-HTUTBM5 --- [           main] e.a.c.a.AuthorizationMain                : Starting AuthorizationMain on DESKTOP-HTUTBM5 with PID 8684 (C:\dev\core-java-spring\aut
remove this file from the repo (add to .gitignore)

2019-08-13 11:17 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +    @ApiOperation(value = "Register one ore more ActionPlans.",
type ore -E

2019-08-13 11:18 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +        for(ChoreographerActionPlanRequestDTO request : requests) {
missing final 
need a space between for and ( (for is not a method)

2019-08-13 11:20 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +    /* @ApiOperation(value = "Register one ore more ActionPlans using already existing Action chains only.")
uncomment or delete this

2019-08-13 11:22 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +            throw new BadPayloadException(ID_NOT_VALID_ERROR_MESSAGE, HttpStatus.SC_BAD_REQUEST, CommonConstants.AUTHORIZATION_URI + CHOREOGRAPHER_ACTION_PLAN_MGMT_BY_ID_URI);
i don't think you want to use CommonConstants.AUTHORIZATION_URI here

2019-08-13 11:23 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +            throw new BadPayloadException(ID_NOT_VALID_ERROR_MESSAGE, HttpStatus.SC_BAD_REQUEST, CommonConstants.AUTHORIZATION_URI + CHOREOGRAPHER_ACTION_PLAN_MGMT_BY_ID_URI);
or here

2019-08-13 11:26 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +        int validatedPage;
there is a validatePageParameters in Utilities in the current version of development branch that handles this. Please use that (there was a lot of duplicated code and sonarqube was unhappy about them)

2019-08-13 11:27 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +        int validatedPage;
It wasn't present when I got the code from other Core-Systems. Replacing it rn.

2019-08-13 11:28 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +import org.springframework.web.bind.annotation.*;
please don't use wildcards in imports

2019-08-13 11:29 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +import eu.arrowhead.common.database.entity.*;
please don't use wildcards in imports

2019-08-13 11:31 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +
input checks (for example stepName not null and not empty, Utilities.isEmpty checks both, the set is not null, contains at least one element, and every element is a valid servicedefinition, etc.)

2019-08-13 11:39 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +        for(ChoreographerActionPlanRequestDTO request : requests) {
What and why does it have to be final? I don't like finalizing everything unless for a strong reason. I think input validation should be in ChoreographerDBService. What input validation do you think is neccesary here?

2019-08-13 11:41 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +            throw new InvalidParameterException("One or more ActionSteps with the given names already exist! ActionStep NAMES must be UNIQUE!");
Are you sure the action step name must be unique in the whole DB? What if there are two plans (created by different people) in which there are different action steps but its creator wants to name them step01, step02 and so on? Step name being unique in an action plan is not enough?

Anyway, the error message is wrong: there is only one name here.

2019-08-13 11:42 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +        List<ServiceDefinition> usedServices = new ArrayList<>(usedServiceNames.size());
use finals everywhere whenever possible (in Eclipse Ctrl+A, Ctrl+1, Enter)

2019-08-13 11:44 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +        ChoreographerActionStep stepEntry = choreographerActionStepRepository.save(step);
maybe these 2 lines can be one

ChoreographerActionStep stepEntry = choreographerActionStepRepository.save(new ChoreographerActionStep(stepName));

2019-08-13 11:45 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +
input checks

2019-08-13 11:46 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +        List<ServiceDefinition> usedServices = new ArrayList<>(usedServiceNames.size());
What difference does it make if everything is final vs nothing is final? If everything is final than the use of final is not justified anymore.

2019-08-13 11:53 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +            throw new InvalidParameterException("One or more ActionSteps with the given names already exist! ActionStep NAMES must be UNIQUE!");
Right now in my mind also considering the future front-end perspective I want to make it easy for users to distinguish Action Plans, Actions and Action Steps from one another. That's why I chose the names of each should be unique. In this way there are no ActionPlans which are the same in any perspective.

I like your proposal though but right now I don't have any idea how to achieve this on code and DB level. Composite key for the ActionStep maybe?

2019-08-13 11:54 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +
input checks

2019-08-13 11:57 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +            throw new InvalidParameterException("One or more Actions with the given names already exist! Action NAMES must be UNIQUE!");
I action name is unique then there is no such case when more than one Action has the same name in the database. So the error message is misleading.

2019-08-13 11:59 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +        for (ChoreographerActionStepRequestDTO actionStep : actionSteps) {
can you merge this two loops into one?

2019-08-13 11:59 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +            throw new InvalidParameterException("One or more Actions with the given names already exist! Action NAMES must be UNIQUE!");
But it is possible that the user input contains more than one action which are already in the database.

2019-08-13 12:01 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +    public ChoreographerAction addNextActionToChoreographerAction(final String actionName, final String nextActionName) {
missing Transactional annotation

2019-08-13 12:05 UTC, rbocsi commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +        if(Utilities.isEmpty(actionPlanName) || actions.isEmpty()) {
actions still can be null which will cause NPE here

2019-08-13 12:10 UTC, szkris commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +        for (ChoreographerActionStepRequestDTO actionStep : actionSteps) {
Inserting the second loop into the first causes an error in method "addNextStepToChoreographerActionStep" because the ChoreographerActionStep is not present in the db.

2019-08-13 12:10 UTC, rbocsi commented on choreographer/src/main/resources/log4j2.xml
> +    	<AsyncLogger name="eu.arrowhead" level="debug" additivity="true">
change the order of two element: Root first, AsyncLogger second.
We found a bug here sometimes ago, the order change fixed it.

2019-08-13 12:16 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceDefinition.java
> +import javax.persistence.*;
fixing imports

2019-08-13 12:17 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +import java.util.*;
fixing imports

2019-08-13 12:20 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +	    return new ChoreographerActionStepResponseDTO(actionStep.getId(),
input checks

2019-08-13 12:20 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +	public static List<ChoreographerActionStepResponseDTO>collectChoreographerActionStepsFromChoreographerAction(final Set<ChoreographerActionActionStepConnection> actionStepConnections) {
input checks

2019-08-13 12:21 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +    public static ChoreographerActionResponseDTO convertChoreographerActionToChoreographerActionResponseDTO(ChoreographerAction actionEntry) {
input checks

2019-08-13 12:21 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		List<ChoreographerActionResponseDTO> result = new ArrayList<>(actionConnections.size());
input checks

2019-08-13 12:21 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/DTOConverter.java
> +		return new ChoreographerActionPlanResponseDTO(actionPlanEntry.getId(),
input checks

2019-08-13 12:25 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/choreographer/ChoreographerExistingActionRequestDTO.java
> +public class ChoreographerExistingActionRequestDTO {
this type is the same as ChoreographerActionRequestDTO. Why use 2 types? You can use the first one in case of existing actions as well

2019-08-13 12:28 UTC, rbocsi commented on scripts/create_empty_arrowhead_db.sql
> +  `created_at` timestamp NOT NULL DEFAULT NOW(),
we use current timestamp everywhere, why do you change it?

2019-08-13 12:28 UTC, rbocsi commented on serviceregistry.log
> +2019-07-29 14:13:23.034  INFO DESKTOP-HTUTBM5 --- [           main] e.a.c.s.ServiceRegistryMain              : Starting ServiceRegistryMain on DESKTOP-HTUTBM5 with PID 5656 (C:\dev\core-java-spring\s
remove this file from repo (+ add to .gitignore)

2019-08-13 12:29 UTC, rbocsi requested changes
see inline comments

2019-08-13 13:00 UTC, szkris commented on scripts/create_empty_arrowhead_db.sql
> +  `created_at` timestamp NOT NULL DEFAULT NOW(),
I think I accidentally chose the wrong code when merging.

2019-08-14 14:57 UTC, borditamas commented on choreographer/src/test/java/eu/arrowhead/core/choreographer/ChoreographerControllerTest.java
> +
Without runnable methods the build at Jenkins will fail

2019-08-15 08:39 UTC, borditamas commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/database/service/ChoreographerDBService.java
> +public class ChoreographerDBService {
Database operations could throw various exceptions and as these operations mostly called via http request, therefore it's a good  practice (and used in other core services too) to transform them into ArrowheadException. There is an automatism in core-common wich is intended to handle the ArrowheadExceptions through http requests

2019-08-15 08:46 UTC, borditamas commented on choreographer/src/main/java/eu/arrowhead/core/choreographer/ChoreographerController.java
> +public class ChoreographerController {
By validating input DTOs in the controller you cloud save the expensive database oprations which would fail due to the wrong inputs

2019-08-15 08:47 UTC, borditamas requested changes
see comments

2019-09-11 09:26 UTC, tsvetlin commented
@szkris

2019-09-17 12:07 UTC, tsvetlin commented
@szkris Please group the swagger like the other core systems.

2019-09-24 17:29 UTC, szkris commented
Swagger grouping done! Please review the code and merge into develop if it's okay.

2019-10-02 12:05 UTC, merged