Orchestrator orchestration trigger inter cloud
eclipse-arrowhead/core-java-spring pull request #47
Opened 2019-08-20 14:20 UTC by MaGaMeGa

Please suggest refactoring changes, if needed, before test cases are completed.

2019-08-21 08:20 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudCloudMatchmaker.java
> +	    return partnerClouds.get(0);
I think, when there was no preferred clouds given, then it can happen, that none of the neighbor clouds send response, so in that case here I think you will get IndexOutOfBoundsException. 
Consider to check the size of partnerClouds list and return with empty CloudResponseDTO if the list is empty.

2019-08-21 08:43 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/CommonConstants.java
> +	public static final String INTER_CLOUD_CLOUD_MATCHMAKER = "interCloudCloudMatchmaker";
There is not INTRA_CLOUD_CLOUD_MATCHMAKER so I don't understand why we need the INTER_CLOUD prefix here. You should rename it to CLOUD_MATCHMAKER.

2019-08-21 08:52 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/CloudRequestDTO.java
> +	public boolean equals(final Object obj) {
equals and hashCode MUST always use the same fields. Two cloud are equals if the name and operator are the same. So you have to simplify this implementation

2019-08-21 08:52 UTC, borditamas reviewed
see my inline comment

2019-08-21 09:01 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorApplicationInitListener.java
> +	public InterCloudCloudMatchmakingAlgorithm getInterCloudCloudMatchmaker() {
rename this method by removing unnecessary "InterCloud"

2019-08-21 09:04 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorApplicationInitListener.java
> +		context.put(CommonConstants.REQUIRED_URI_LIST, getRequiredCoreSystemServiceUris());
I think thist line is unnecessary because the base class already put REQUIRED_URI_LIST into the context before the customInit() is called.

2019-08-21 09:17 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudCloudMatchmaker.java
> +public class DefaultInterCloudCloudMatchmaker implements InterCloudCloudMatchmakingAlgorithm {
rename

2019-08-21 09:19 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudCloudMatchmaker.java
> +		for (GSDPollResponseDTO gSDPollResponseDTO : gSDResult.getResults()) {
missing final

2019-08-21 09:23 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudCloudMatchmaker.java
> +		final GSDQueryResultDTO gSDResult = params.getgSDResult();
rename gSDResult to gsdResult. The first one looks weird to me

2019-08-21 09:25 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudProviderMatchmaker.java
> +			for (PreferredProviderDataDTO provider :  preferredProviderDataDTOList) {
missing final

2019-08-21 09:28 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudProviderMatchmaker.java
> +		Assert.isTrue(icnResultDTO != null && !icnResultDTO.getResponse().isEmpty(), "icnResponseDTO is null or empty.");
we can't guarantee that there is any ICN results in the DTO

2019-08-21 09:28 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    final Map<Long, List<String>> serviceDefinitionIdInterfaceIdsMap = mapInterfacesToServiceDefinitions( onlyLocalEntryList);
There are interface names in the map, not ids. Please change the name of the map.

2019-08-21 09:29 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudProviderMatchmaker.java
> +		return  new OrchestrationResponseDTO(List.of(icnResultDTO.getResponse().get(0)));
if icnResultDTO.getResponse() is empty this will cause an exception

2019-08-21 09:30 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingAlgorithm.java
> +public interface InterCloudCloudMatchmakingAlgorithm {
Rename to CloudMatchmakingAlgorithm

2019-08-21 09:30 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingParameters.java
> +public class InterCloudCloudMatchmakingParameters {
rename

2019-08-21 09:31 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingParameters.java
> +	protected GSDQueryResultDTO gSDResult;
rename member to gsdResult

2019-08-21 09:31 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingParameters.java
> +	public InterCloudCloudMatchmakingParameters(final GSDQueryResultDTO gSDResult, final List<CloudRequestDTO> preferredClouds,
rename parameter name to gsdResult

2019-08-21 09:31 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingParameters.java
> +	public GSDQueryResultDTO getgSDResult() { return gSDResult;	}
rename getter to getGsdResult()

2019-08-21 09:32 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingParameters.java
> +	public void setgSDResult( final GSDQueryResultDTO gSDResult) {	this.gSDResult = gSDResult;	}
rename setter to setGsdResult 
also rename the input parameter

2019-08-21 09:33 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorDriver.java
> +		Assert.isTrue(consumerSystemId > 0, "ConsumerSystemId is less then 1.");
typo then => than

2019-08-21 09:35 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorDriver.java
> +				Map.of(CommonConstants.COMMON_FIELD_NAME_ID, consumerSystemId + ""));
please use String.valueOf() instead of concatenation with empty string

2019-08-21 09:37 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private static final String MORE_THAN_ONE_ERROR_MESSAGE= " must not have more then one element.";
typo then => than

2019-08-21 10:20 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +			if (serviceDefinitionsInterfacesMap.containsKey(serviceDefinitionId)) {
Suggestion: Consider to use Set<String> instead of List<String> as the return of this method, because then you can swap this if-else block to the snipped code below, which consume less resource:

serviceDefinitionsInterfacesMap.putIfAbsent(serviceDefinitionId, new ArrayList<>());			
serviceDefinitionsInterfacesMap.get(serviceDefinitionId).add(interfaceName);

2019-08-21 10:26 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +			if (providersInterfacesMap.containsKey(providerSystemId)) {
same suggestion as in the method before

2019-08-21 10:54 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	final boolean useGateway = false;
after changes in the ICN process I think we don't need this here

2019-08-21 11:17 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    logger.info("currently only local entries are allowed to be returned by topPriorityOrchestration");
debug message, not info

2019-08-21 11:17 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    for (Entry<Long, String> entry : serviceDefinitionsIdsMap.entrySet()) {
missing finals in the whole class

2019-08-21 11:22 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +		final List<ServiceRegistryResponseDTO> filterdResults = new ArrayList<>();
typo filterEdResults

2019-08-21 11:22 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private List<ServiceRegistryResponseDTO> crossCheckStoreEntries(List<OrchestratorStore> entryList,
Actually this method doesn't make a cross check.  Real cross check is made in "getHighestPriorityCurrentlyWorkingStoreEntryFromEntryList". 

This method should be renamed to something else then "crossCheck". Like "getAuthorizedServiceRegistryEntries" or something similar.

2019-08-21 11:27 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +				useGateway);
we remove useGateway parameter from this constructor. For now you can just use false.

2019-08-21 11:30 UTC, rbocsi commented on orchestrator/src/test/java/eu/arrowhead/core/orchestrator/service/OrchestratorDriverTest.java
> +		final UriComponents queryBySystemIdUriForTestRequest = Utilities.createURI(CommonConstants.HTTPS, "localhost", 8443,CommonConstants.SERVICE_REGISTRY_URI + CommonConstants.OP_SERVICE_REGISTRY_QUERY_
use expand on UriComponents istead of string replace

2019-08-21 11:31 UTC, rbocsi commented on orchestrator/src/test/java/eu/arrowhead/core/orchestrator/service/OrchestratorServiceTest.java
> +	private InterCloudCloudMatchmakingAlgorithm interCloudCloudMatchmaker;
rename

2019-08-21 11:33 UTC, rbocsi commented on orchestrator/src/test/java/eu/arrowhead/core/orchestrator/service/OrchestratorServiceTest.java
> +	public void testOrchestrationFromStoreOk() {
rename test methods. A test method's name must contains the method name which is tested.

2019-08-21 11:36 UTC, borditamas requested changes
See my inline comments

2019-08-21 11:36 UTC, rbocsi requested changes
see inline comments

2019-08-21 13:59 UTC, MaGaMeGa commented on orchestrator/src/test/java/eu/arrowhead/core/orchestrator/service/OrchestratorServiceTest.java
> +	public void testOrchestrationFromStoreOk() {
done

2019-08-21 14:00 UTC, MaGaMeGa commented on orchestrator/src/test/java/eu/arrowhead/core/orchestrator/service/OrchestratorServiceTest.java
> +	private InterCloudCloudMatchmakingAlgorithm interCloudCloudMatchmaker;
done

2019-08-21 14:00 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +				useGateway);
It is a constant false now. Will be removed after merge

2019-08-21 14:01 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +		final List<ServiceRegistryResponseDTO> filterdResults = new ArrayList<>();
done

2019-08-21 14:01 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +			if (providersInterfacesMap.containsKey(providerSystemId)) {
done

2019-08-21 14:01 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +			if (serviceDefinitionsInterfacesMap.containsKey(serviceDefinitionId)) {
Would be a definite yes, if anywhere else in the codebase , there would be any other use case for the serviceInterfaceName collection, than List. Since, we would have to convert it back to List, anyway, I'm not sure if it would still worth to change?

2019-08-21 14:01 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private List<ServiceRegistryResponseDTO> crossCheckStoreEntries(List<OrchestratorStore> entryList,
I think, the crossCheck, in the sence of cross checking the store entries with the serviceregisty and authorization systems, is actually happens here >  gets the currentlyWorkingAuthorizedStoreEnties.
The "getHighestPriorityCurrentlyWorkingStoreEntryFromEntryList" only gets the first element of those working entries by the given rules. 
Would it be more clear if the name of the method would be "crossCheckLocalStoreEntries" ?

2019-08-21 14:01 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    for (Entry<Long, String> entry : serviceDefinitionsIdsMap.entrySet()) {
done

2019-08-21 14:01 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    final Map<Long, List<String>> serviceDefinitionIdInterfaceIdsMap = mapInterfacesToServiceDefinitions( onlyLocalEntryList);
done

2019-08-21 14:02 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	    logger.info("currently only local entries are allowed to be returned by topPriorityOrchestration");
done

2019-08-21 14:02 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	final boolean useGateway = false;
will be removed, once ready

2019-08-21 14:02 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private static final String MORE_THAN_ONE_ERROR_MESSAGE= " must not have more then one element.";
done

2019-08-21 14:02 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorDriver.java
> +				Map.of(CommonConstants.COMMON_FIELD_NAME_ID, consumerSystemId + ""));
done

2019-08-21 14:03 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorDriver.java
> +		Assert.isTrue(consumerSystemId > 0, "ConsumerSystemId is less then 1.");
done

2019-08-21 14:03 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingParameters.java
> +	public void setgSDResult( final GSDQueryResultDTO gSDResult) {	this.gSDResult = gSDResult;	}
done

2019-08-21 14:03 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingParameters.java
> +	public GSDQueryResultDTO getgSDResult() { return gSDResult;	}
done

2019-08-21 14:03 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingParameters.java
> +	public InterCloudCloudMatchmakingParameters(final GSDQueryResultDTO gSDResult, final List<CloudRequestDTO> preferredClouds,
done

2019-08-21 14:03 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingParameters.java
> +	protected GSDQueryResultDTO gSDResult;
done

2019-08-21 14:04 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingParameters.java
> +public class InterCloudCloudMatchmakingParameters {
done

2019-08-21 14:04 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/InterCloudCloudMatchmakingAlgorithm.java
> +public interface InterCloudCloudMatchmakingAlgorithm {
done

2019-08-21 14:04 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudProviderMatchmaker.java
> +		return  new OrchestrationResponseDTO(List.of(icnResultDTO.getResponse().get(0)));
done

2019-08-21 14:04 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudProviderMatchmaker.java
> +			for (PreferredProviderDataDTO provider :  preferredProviderDataDTOList) {
done

2019-08-21 14:04 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudProviderMatchmaker.java
> +		Assert.isTrue(icnResultDTO != null && !icnResultDTO.getResponse().isEmpty(), "icnResponseDTO is null or empty.");
done

2019-08-21 14:05 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudCloudMatchmaker.java
> +	    return partnerClouds.get(0);
done

2019-08-21 14:05 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudCloudMatchmaker.java
> +		for (GSDPollResponseDTO gSDPollResponseDTO : gSDResult.getResults()) {
done

2019-08-21 14:05 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudCloudMatchmaker.java
> +		final GSDQueryResultDTO gSDResult = params.getgSDResult();
done

2019-08-21 14:05 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/DefaultInterCloudCloudMatchmaker.java
> +public class DefaultInterCloudCloudMatchmaker implements InterCloudCloudMatchmakingAlgorithm {
done

2019-08-21 14:06 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorApplicationInitListener.java
> +		context.put(CommonConstants.REQUIRED_URI_LIST, getRequiredCoreSystemServiceUris());
done

2019-08-21 14:06 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/OrchestratorApplicationInitListener.java
> +	public InterCloudCloudMatchmakingAlgorithm getInterCloudCloudMatchmaker() {
done

2019-08-21 14:06 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/dto/CloudRequestDTO.java
> +	public boolean equals(final Object obj) {
done

2019-08-21 14:06 UTC, MaGaMeGa commented on core-common/src/main/java/eu/arrowhead/common/CommonConstants.java
> +	public static final String INTER_CLOUD_CLOUD_MATCHMAKER = "interCloudCloudMatchmaker";
done

2019-08-21 17:22 UTC, MaGaMeGa commented on orchestrator/src/test/java/eu/arrowhead/core/orchestrator/service/OrchestratorDriverTest.java
> +		final UriComponents queryBySystemIdUriForTestRequest = Utilities.createURI(CommonConstants.HTTPS, "localhost", 8443,CommonConstants.SERVICE_REGISTRY_URI + CommonConstants.OP_SERVICE_REGISTRY_QUERY_
done

2019-08-22 08:15 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +			if (serviceDefinitionsInterfacesMap.containsKey(serviceDefinitionId)) {
Not much indeed, but a little (It's less with one iteration in total ) :) It's up to you.

As I see you have already add the 'putIfAbsent' before the 'if-else' block. But in this case you don't need that block. The inner 'if" statement is enough.

2019-08-22 08:20 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private List<ServiceRegistryResponseDTO> crossCheckStoreEntries(List<OrchestratorStore> entryList,
">gets the currentlyWorkingAuthorizedStoreEnties" this is not the case i think, as I see you get all the working and authorized service registry entry for that specific service and not only those which are registered in the store as well.

2019-08-22 08:23 UTC, borditamas commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private List<ServiceRegistryResponseDTO> crossCheckStoreEntries(List<OrchestratorStore> entryList,
So you not cross checking two collection, but get a completly new collection if the other one is not empty.

2019-08-22 10:20 UTC, MaGaMeGa commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorService.java
> +	private List<ServiceRegistryResponseDTO> crossCheckStoreEntries(List<OrchestratorStore> entryList,
Thanks for alerting me to this mistake. It has been renamed and corrected.

2019-08-26 08:48 UTC, borditamas approved these changes

2019-08-26 08:56 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/CloudMatchmakingParameters.java
> +	public CloudMatchmakingParameters(final GSDQueryResultDTO gSDResult, final List<CloudRequestDTO> preferredClouds,
rename parameter gSDResult to gsdResult

2019-08-26 09:01 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/RandomWeightedCloudMatchmaker.java
> +    class RandomCollection {
i think this nested class can be private static

2019-08-26 10:04 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/RandomWeightedCloudMatchmaker.java
> +        private double total = 0;
should be int

2019-08-26 10:05 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/RandomWeightedCloudMatchmaker.java
> +        protected void add(final double weight, final CloudResponseDTO result) {
should be public
weight should be int

2019-08-26 10:08 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/RandomWeightedCloudMatchmaker.java
> +            if (weight <= 0 || map.containsValue(result)) {
If you want to use map.containsValue  please implement equals in CloudResponseDTO (id equivalence is sufficient)

2019-08-26 10:08 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/RandomWeightedCloudMatchmaker.java
> +            map.put(total, result);
after total and weight is int, here you have to cast to double

2019-08-26 10:10 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/RandomWeightedCloudMatchmaker.java
> +        protected CloudResponseDTO next() {
should be public

2019-08-26 10:11 UTC, rbocsi commented on orchestrator/src/main/java/eu/arrowhead/core/orchestrator/matchmaking/RandomWeightedCloudMatchmaker.java
> +        protected boolean isEmpty() {
should be public and you should use map.isEmpty instead()

2019-08-26 10:16 UTC, rbocsi approved these changes
Seems fine, but I write some comments (mostly about the new cloud matchmaker implementation). After the fixes you can merge without a new review.

2019-08-26 17:25 UTC, merged