Database impl
eclipse-arrowhead/core-java-spring pull request #6
Opened 2019-05-27 14:52 UTC by borditamas

Please check my DB implementation especially the bidirectional mappings I've made. Thanks

2019-05-28 07:42 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Cloud.java
> +	private Boolean secure;
use primitive boolean instead because it can't be null. Also specify the default value (it increase readability I think)

2019-05-28 07:43 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Cloud.java
> +	private Boolean neighbor;
same as the previous

2019-05-28 07:43 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Cloud.java
> +	private Boolean ownCloud;
same as the previous and the one before

2019-05-28 07:44 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Cloud.java
> +	private Set<InterCloudAuthorization> interCloudAuthorizations = new HashSet<InterCloudAuthorization>();
I don't think we need this. It connects SR db directly to authorization db which is not necessary at this point

2019-05-28 07:45 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Cloud.java
> +	public Cloud(String operator, String name, String address, int port, String gatekeeperServiceUri,
use final whenever possible

2019-05-28 07:52 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Relay.java
> +	private Boolean secure;
primitive boolean + default

2019-05-28 07:53 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceDefinition.java
> +	private Set<IntraCloudAuthorization> intraCloudAuthorizations = new HashSet<IntraCloudAuthorization>();
delete this (see Cloud.java)

2019-05-28 07:54 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceDefinition.java
> +	private Set<InterCloudAuthorization> interCloudAuthorizations = new HashSet<InterCloudAuthorization>();
see the previous comment

2019-05-28 07:59 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceInterface.java
> +	private String interface_;
rename this to interfaceName (rename the column as well: interface_name)

2019-05-28 08:03 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceInterface.java
> +	private Set<ServiceRegistryInterfaceConnection> serviceConnections = new HashSet<ServiceRegistryInterfaceConnection>();
not so useful as it contains a lot of service registry entries to different service definitions

2019-05-28 08:04 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceRegistry.java
> +	private Boolean secure;
use primitive boolean + default value

2019-05-28 08:08 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceRegistry.java
> +	private long version;
use int and default value 1 (need to modify the db script too)

2019-05-28 08:09 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceRegistryInterfaceConnection.java
> +	@ManyToOne (fetch = FetchType.LAZY)
use eager

2019-05-28 08:12 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/System.java
> +	private Set<IntraCloudAuthorization> authorizationsAsConsumer = new HashSet<IntraCloudAuthorization>();
delete this

2019-05-28 08:12 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/System.java
> +	private Set<IntraCloudAuthorization> authorizationsAsProvider = new HashSet<IntraCloudAuthorization>();
delete this

2019-05-28 08:34 UTC, rbocsi requested changes
see comments in files

2019-05-28 13:35 UTC, borditamas commented
Changes made as requested and discussed. Please review them, thanks

2019-05-28 14:19 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Cloud.java
> +	private Set<InterCloudAuthorization> interCloudAuthorizations = new HashSet<InterCloudAuthorization>();
needed for cacading

2019-05-28 14:21 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceDefinition.java
> +	private Set<IntraCloudAuthorization> intraCloudAuthorizations = new HashSet<IntraCloudAuthorization>();
needed for cascading

2019-05-28 14:21 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceDefinition.java
> +	private Set<InterCloudAuthorization> interCloudAuthorizations = new HashSet<InterCloudAuthorization>();
needed for cascading

2019-05-28 14:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/ServiceInterface.java
> +	private Set<ServiceRegistryInterfaceConnection> serviceConnections = new HashSet<ServiceRegistryInterfaceConnection>();
but needed for cascading

2019-05-28 14:24 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/System.java
> +	private Set<IntraCloudAuthorization> authorizationsAsConsumer = new HashSet<IntraCloudAuthorization>();
needed for cascading

2019-05-28 14:25 UTC, rbocsi approved these changes
it seems ok

2019-05-29 08:29 UTC, borditamas commented
Complemented with "logs" entity as discussed

2019-05-29 08:39 UTC, rbocsi approved these changes
seems fine.

2019-05-29 08:49 UTC, merged