Eventhandler implementation
eclipse-arrowhead/core-java-spring pull request #65
Opened 2019-09-16 12:09 UTC by MaGaMeGa

2019-09-17 07:47 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +					Assert.notNull(authOptional.get().getConsumerSystem(), "ConsumerSystem is null");
unnecessary assert. Data comes from the DB, consumer can't be null.

2019-09-17 07:49 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +					} catch (Exception ex) {
unnecessary try/catch, If any problem occurs in the update task, it happens in an other thread, this catch does not do anything

2019-09-17 07:55 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +				} catch (Exception ex) {
unnecessary try/catch block

2019-09-17 07:55 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +			} catch (Exception ex) {
unnecessary try/catch block

2019-09-17 07:57 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/database/service/AuthorizationDBService.java
> +		final List<AuthorizationIntraCloud> authIntraOpt = authorizationIntraCloudRepository.findAllByConsumerSystem(consumer);
rename variable, it is not an optional, it is a list.

2019-09-17 08:02 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/service/AuthorizationDriver.java
> +		Assert.isTrue(updatedConsumerSystemId > 0, "ConsumerSystemId could not be less then one.");
typo then => than

2019-09-17 08:04 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/service/AuthorizationDriver.java
> +		eventPublishRequestDTO.setPayload( Long.toString( updatedConsumerSystemId ) );
use String.valueOf() instead for consistency (we used that before)

2019-09-17 08:07 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/service/AuthorizationDriver.java
> +		final SystemRequestDTO systemRequestDTO = new SystemRequestDTO();
make this local variable to a field and use lazy init here. It is unnecessary to create the system everytime, because it does not change after initialization of the authorization core system.

2019-09-17 08:14 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/service/AuthorizationDriver.java
> +			response = httpService.sendRequest( eventHandlerAuthUpdateUri , HttpMethod.POST, ResponseEntity.class, eventPublishRequestDTO);
response type is Void.class here
you don't need the response at all, you don't have to check whether is null or not 200, because the httpService transforms every ErrorMessageDTO to an exception, see ArrowheadHttpClientResponseErrorHandler class.

2019-09-17 08:14 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/service/AuthorizationDriver.java
> +
you should check here the event handler is present in the cloud

2019-09-17 08:17 UTC, rbocsi commented on authorization/src/main/java/eu/arrowhead/core/authorization/service/PublishAuthUpdateTask.java
> +
asserts here (first parameter not null, second not zero or negative)

2019-09-17 08:23 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/core/CoreSystemService.java
>  	EVENT_PUBLISH(CommonConstants.CORE_SERVICE_EVENT_HANDLER_PUBLISH, CommonConstants.EVENT_HANDLER_URI + CommonConstants.OP_EVENT_HANDLER_PUBLISH),
rename to EVENT_PUBLISH_SERVICE for consistency

2019-09-17 08:24 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/core/CoreSystemService.java
> +	EVENT_SUBSCRIBE(CommonConstants.CORE_SERVICE_EVENT_HANDLER_SUBSCRIBE, CommonConstants.EVENT_HANDLER_URI + CommonConstants.OP_EVENT_HANDLER_SUBSCRIBE),
rename to EVENT_SUBSCRIBE_SERVICE for consistency

2019-09-17 08:30 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Subscription.java
> +	@Column(nullable = true, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
why nullable if it has a default value

2019-09-17 08:31 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/Subscription.java
> +
you don't use sources in constructor. Use it or delete the parameter.

2019-09-17 08:33 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/SubscriptionPublisherConnection.java
> +	private boolean authorized;
what is default value here?

2019-09-17 08:34 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/entity/SubscriptionPublisherConnection.java
> +	public boolean isAuhtorized() { return authorized; }
typo in the method name. IsAuTHorized

2019-09-17 08:36 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SubscriptionPublisherConnectionRepository.java
> +	public List<SubscriptionPublisherConnection> findAllBySystemAndAuthorized(final System validProviderSystem, final boolean authorized);
remove valid from param name

2019-09-17 08:37 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/database/repository/SubscriptionRepository.java
> +	public Set<Subscription> findAllByEventType(final EventType validEventType);
remove valid from param name

2019-09-17 08:49 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/SubscriptionResponseDTO.java
> +		super();
unnecessary line

2019-09-17 08:53 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
>  import io.swagger.annotations.ApiResponses;
missing @Api annotation (see other controllers), it is necessary for swagger grouping

2019-09-17 08:54 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
> +	private static final String IS_AFTER_TOLERATED_DIFF_ERROR_MESSAGE = " is further in the future then the tolerated time difference";
typo then => than

2019-09-17 08:54 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
> +	private static final String IS_BEFORE_TOLERATED_DIFF_ERROR_MESSAGE = " is further in the past then the tolerated time difference";;
the same here

2019-09-17 08:59 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
> +		final ValidatedPageParams validParameters = Utilities.validatePageParameters(page, size, direction, CommonConstants.EVENT_HANDLER_URI + EVENT_HANDLER_MGMT_URI);
validatePageParameters is moved to an other class (it is already in the development branch). So before merging the pull request into development branch I suggest to merge development into your branch and fix this problem

2019-09-17 09:02 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
> +	@ResponseBody public SubscriptionResponseDTO subscription(@RequestBody final SubscriptionRequestDTO request) {
rename this function to subscribe
method names are usually contain a verb

2019-09-17 09:03 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
> +	@ResponseBody public void unSubscription(@RequestBody final SubscriptionRequestDTO request) {
rename tihs function to unsubscribe (which is one word, so there is no need for capital S)

2019-09-17 09:06 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/SubscriptionRequestDTO.java
> +	private Boolean matchMetaData;
this should be primitive boolean with default value false. So there is no need to define it unless you want to match meta data

2019-09-17 09:07 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
> +		if (request.getMatchMetaData() == null) {
if matchMetaData is a primitive boolean with a default false value, you don't need this check

2019-09-17 09:11 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
> +		// TODO implement additional method logic here
this todo remained here
remove or implement additional method logic (and remove after)

2019-09-17 09:23 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +	public SubscriptionListResponseDTO getSubscriptionsRequest(final int page, final int size,
rename to getSubscriptionsResponse for consistency (the last word stands for the return value, we use response all the other db services)

2019-09-17 09:24 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +	public SubscriptionResponseDTO getSubscriptionByIdRequest(final long id) {
rename Request => Response

2019-09-17 09:26 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +
throw invalid parameter exception if the subscription does not exists

2019-09-17 09:26 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +		return new Subscription();
after throwing the exception this will be unreachable code so you can delete it.

2019-09-17 09:29 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +		return new Subscription(); //return empty subscription
the same as the previous method

2019-09-17 09:29 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +	@Transactional
missing rollbackFor

2019-09-17 09:30 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +				return;
unnecessary line

2019-09-17 09:30 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +		return;
unnecessary line

2019-09-17 09:31 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +	@Transactional
missing rollbackFor

2019-09-17 09:32 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +	@Transactional
missing rollbackfor

2019-09-17 09:36 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +		if (!secure) {
not being secured does not mean you don't have to authorize it just means the communication goes through unsecured (http) channel.

2019-09-17 09:38 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +	public void updateSubscriberAuthorization(final List<Subscription> involvedSubscriptions,
if this is an update you should use transactional

2019-09-17 09:39 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +		subscription.setOnlyPredefinedPublishers(request.getSources() != null && !request.getSources().isEmpty()); //TODO orginize to method
remove todo

2019-09-17 09:42 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +		//TODO validate dates by comparing to currentTime and threshold
implement this

startDate must be equal or after current time and endDate as well. Of course, startDate must precedes the endDate

2019-09-17 09:44 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +			final String validEventTypeName = eventType.toUpperCase().trim();//TODO create normalizer in Utilities
remove TODO

2019-09-17 09:46 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +	private Set<System> getPreferredPublisherSystems(final Set<SystemRequestDTO> sources) {
I don't like this method name. These systems are not preferred, these are the only ones who can send me notifications.

2019-09-17 09:50 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +					if (DTOUtilities.equalsSystemInResponseAndRequest(systemResponseDTO, DTOConverter.convertSystemToSystemRequestDTO(system))) {
convert system before the for loop
convert system to SystemResponseDTO instead of SystemRequestDTO so you can use simple equals in the condition

2019-09-17 09:52 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +			return;
unnecessary line

2019-09-17 09:54 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +				for (final SystemResponseDTO systemResponseDTO : authorizedPublishers) {
convert system before the for loop
convert system to SystemResponseDTO instead of SystemRequestDTO so you can use simple equals in the condition

2019-09-17 09:56 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +				return;
unnecessary line

2019-09-17 09:58 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +				return;
unnecessary line

2019-09-17 10:00 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +			if ( involvedSubscriptions.contains( subscription )  && !involvedSubscriptionsFromConnections.contains( subscription ) ) {
implement Subscription.equals (two subscription is equals if the their ids are equals) if you want to use contains.

2019-09-17 10:02 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +	private void checkSubscriptionUpdateUniqueConstrains(final EventType eventTypeForUpdate, final System subscriberSystemForUpdate) {
these two methods are almost the same. If fact, you can implement the first one by calling the second one using appropriate members of the subscription parameter

2019-09-17 10:19 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/metadatafiltering/DefaultMetadataFilter.java
> +		if ( metaDataFilterMap.keySet().containsAll( eventMetadata.keySet() ) ) {
this is just wrong.  Let's assume we have to map: { "a": true, "b": false} and {"a": false, "b": true}. Then this code returns true. Furthermore, the filter map can be subset of the event map and not the other way around.

Possible solution might be: eventMetadata.entrySet().containsAll(metaDataFilterMap.entrySet()), but this needs extensive testing (you can write unit tests for this)

2019-09-17 10:21 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/security/EHAccessControlFilter.java
> +
you have to make sure that echo can be called by anybody in the cloud

2019-09-17 10:27 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +	@Transactional
unnecessary, this is not a db service

2019-09-17 10:27 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +	public SubscriptionResponseDTO subscriptionRequest( final SubscriptionRequestDTO request) {
rename method to subscribe

2019-09-17 10:29 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +	@Transactional
unnecessary

2019-09-17 10:29 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +	public void unSubscriptionRequest( final SubscriptionRequestDTO request) {
rename to unsubscribe

2019-09-17 10:29 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +		return ;
unnecessary

2019-09-17 10:30 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +	@Transactional
unnecessary

2019-09-17 10:31 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +		return new EventPublishResponseDTO(); //always return empty response
if always return with empty response then we may not need a response at all. You should refactor the method to use void.

2019-09-17 10:40 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +	@Transactional
unnecessary

2019-09-17 10:43 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +	@Transactional
unnecessary

2019-09-17 10:43 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +	public SubscriptionResponseDTO updateSubscriptionRequest(final long id, final SubscriptionRequestDTO subscriptionRequestDTO) {
rename Request => Response

2019-09-17 10:47 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +			final String notifyUriForUpdate = request.getNotifyUri();
I don't think we should allow null or empty notify uri here. What is the purpose of a subscription if we can't inform the subscriber when something happened?

2019-09-17 10:50 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +			return new SubscriptionResponseDTO(); // return empty SubscriptionResponseDTO
updateSubscription should not return with null or allow empty notifyUri. Instead it should throw exception if the update failed or the request contains invalid parameter value.

2019-09-17 10:50 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +	@Transactional
unnecessary

2019-09-17 10:55 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +		final Map<String, String> requestMetadata = request.getMetaData();
this can be null. The filter class will throw exception if the metadata is null

2019-09-17 10:56 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +		return;
unnecessary

2019-09-17 10:56 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +		return;
unnecessary

2019-09-17 10:57 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java
> +		return;
unnecessary

2019-09-17 11:03 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/PublishEventTask.java
> +			final ResponseEntity response = httpService.sendRequest( subscriptionUri, HttpMethod.POST, ResponseEntity.class, DTOConverter.convertEventPublishRequestDTOToEventDTO( publishRequestDTO ));
use Void.class as payload type
no need for response at all

2019-09-17 11:03 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/PublishEventTask.java
> +			if (response == null) {
unnecessary

2019-09-17 11:03 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/PublishEventTask.java
> +			if ( !response.getStatusCode().is2xxSuccessful()) {
unnecessary

2019-09-17 11:04 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/PublishEventTask.java
> +		} catch (final InvalidParameterException | BadPayloadException ex) {
unnecessary, the other catch blcok will handle everything

2019-09-17 11:07 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/PublishEventTask.java
> +		} catch (final ClassCastException ex) {
unnecessary, no casting here

2019-09-17 11:09 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/PublishRequestExecutor.java
> +	}
check httpService as well

2019-09-17 11:11 UTC, rbocsi commented on scripts/create_empty_arrowhead_db.sql
> +  `notify_uri` text,
should be not null

2019-09-17 11:14 UTC, rbocsi commented on scripts/create_empty_arrowhead_db.sql
>  GRANT ALL PRIVILEGES ON `arrowhead`.`event_handler_event` TO 'event_handler'@'localhost';
remove event_handler_event and event_handler_event_subscriber from the script because you don't use them in the code.

2019-09-17 11:21 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
> +	@ResponseBody public EventPublishResponseDTO publish(@RequestBody final EventPublishRequestDTO request) {
we don't need a response object if it is always empty. Change to void and delete the DTO

2019-09-17 11:22 UTC, rbocsi commented on core-common/src/main/java/eu/arrowhead/common/dto/EventPublishRequestDTO.java
> +	private String deliveryCompleteUri;
we don't use this uri, so delete this.

2019-09-17 11:24 UTC, rbocsi requested changes
see inline comments. I didn't review the tests yet because they can change.

2019-09-18 02:52 UTC, MaGaMeGa commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/PublishEventTask.java
> +			final ResponseEntity response = httpService.sendRequest( subscriptionUri, HttpMethod.POST, ResponseEntity.class, DTOConverter.convertEventPublishRequestDTOToEventDTO( publishRequestDTO ));
fixed

2019-09-23 13:51 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/EventHandlerController.java
>  	@PutMapping(path = CommonConstants.OP_EVENT_HANDLER_SUBSCRIBE, consumes = MediaType.APPLICATION_JSON_VALUE)
use DELETE and query params (see SR unregister)
use different endpoint /unsubscribe

2019-09-23 13:57 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +	private void checkSubscriptionUniqueConstrains( final Subscription subscription ) {
typo ConstrainTs

2019-09-23 13:58 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +		checkSubscriptionUniqueConstrainsByEventTypeAndSubscriber( subscription.getEventType(), subscription.getSubscriberSystem());
typo ConstrainTs

2019-09-23 13:58 UTC, rbocsi commented on eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java
> +	private void checkSubscriptionUniqueConstrainsByEventTypeAndSubscriber( final EventType eventTypeForUpdate, final System subscriberSystemForUpdate ) {
typo

2019-09-23 14:11 UTC, rbocsi commented on serviceregistry/src/main/java/eu/arrowhead/core/serviceregistry/security/SRAccessControlFilter.java
> -	private static final CoreSystem[] allowedCoreSystemsForQuery = {CoreSystem.AUTHORIZATION, CoreSystem.EVENT_HANDLER, CoreSystem.ORCHESTRATOR, CoreSystem.GATEKEEPER, CoreSystem.CERTIFICATE_AUTHORITY }
possible merge error

2019-09-23 14:12 UTC, rbocsi requested changes
see inline comments

2019-09-25 10:04 UTC, rbocsi approved these changes

2019-09-25 11:55 UTC, merged